"""중1 개념(concept) 카테고리 시드 데이터 - 2022 개정 교육과정."""

from .._base import mc, concept, test


def get_concept_data() -> dict:
    """개념 카테고리 데이터 반환 (좌표평면, 정비례/반비례, 기본 도형, 평면도형, 입체도형, 자료 정리, 대푯값, 산점도)."""

    # ============================================================
    # 개념 20개 (5~12단원 세부 분화)
    # ============================================================
    concepts = [
        # 2-1: 좌표평면과 그래프 (2개)
        concept(
            id="m1-2-1-1",
            name="순서쌍과 좌표평면",
            grade="middle_1",
            category="concept",
            part="func",
            description="좌표평면, 사분면의 부호 특성, 대칭인 점(x축/y축/원점 대칭)",
        ),
        concept(
            id="m1-2-1-2",
            name="그래프 해석",
            grade="middle_1",
            category="concept",
            part="func",
            description="변화의 경향 읽기(증가/감소/일정), 정성적 추론, 실생활 그래프 해석",
        ),
        # 2-2: 정비례와 반비례 (3개)
        concept(
            id="m1-2-2-1",
            name="정비례 관계",
            grade="middle_1",
            category="concept",
            part="func",
            description="정비례(y = ax), 비례상수 구하기, 그래프가 원점을 지나는 직선",
        ),
        concept(
            id="m1-2-2-2",
            name="반비례 관계",
            grade="middle_1",
            category="concept",
            part="func",
            description="반비례(y = a/x), xy = a(일정한 곱), 그래프가 쌍곡선",
        ),
        concept(
            id="m1-2-2-3",
            name="정비례/반비례 그래프",
            grade="middle_1",
            category="concept",
            part="func",
            description="식만 보고 그래프 개형 유추, 반비례 직사각형 넓이 일정, 실생활 활용",
        ),
        # 2-3: 기본 도형과 작도 (3개)
        concept(
            id="m1-2-3-1",
            name="점/선/면과 위치관계",
            grade="middle_1",
            category="concept",
            part="geo",
            description="직선/반직선/선분 구분, 맞꼭지각, 꼬인 위치(공간)",
        ),
        concept(
            id="m1-2-3-2",
            name="평행선의 성질",
            grade="middle_1",
            category="concept",
            part="geo",
            description="동위각과 엇각, 평행할 때만 크기가 같음, 꺾인 선 문제(보조선)",
        ),
        concept(
            id="m1-2-3-3",
            name="작도와 삼각형 합동",
            grade="middle_1",
            category="concept",
            part="geo",
            description="기본 작도(눈금 없는 자+컴퍼스), 삼각형 합동 조건(SSS, SAS, ASA)",
        ),
        # 2-4: 평면도형의 성질 (2개)
        concept(
            id="m1-2-4-1",
            name="다각형의 내각과 외각",
            grade="middle_1",
            category="concept",
            part="geo",
            description="대각선의 개수, 내각의 합 (n-2)×180, 외각의 합 항상 360도",
        ),
        concept(
            id="m1-2-4-2",
            name="원과 부채꼴의 성질",
            grade="middle_1",
            category="concept",
            part="geo",
            description="원주와 넓이(2πr, πr²), 부채꼴 호의 길이와 넓이, S=½rl 공식",
        ),
        # 2-5: 입체도형의 성질 (3개)
        concept(
            id="m1-2-5-1",
            name="다면체와 회전체",
            grade="middle_1",
            category="concept",
            part="geo",
            description="오일러 다면체 정리(V-E+F=2), 회전체의 단면 성질",
        ),
        concept(
            id="m1-2-5-2",
            name="겉넓이와 부피",
            grade="middle_1",
            category="concept",
            part="geo",
            description="기둥/뿔의 겉넓이와 부피, 원뿔 전개도(부채꼴 호=밑면 둘레)",
        ),
        concept(
            id="m1-2-5-3",
            name="구",
            grade="middle_1",
            category="concept",
            part="geo",
            description="구의 겉넓이(4πr²), 부피(4/3πr³), 반지름 배수와 부피/겉넓이 관계",
        ),
        # 2-6: 자료의 정리와 해석 (3개)
        concept(
            id="m1-2-6-1",
            name="줄기와 잎 그림/도수분포표",
            grade="middle_1",
            category="concept",
            part="data",
            description="줄기와 잎 그림, 도수분포표(계급/계급값/도수)",
        ),
        concept(
            id="m1-2-6-2",
            name="히스토그램과 도수분포다각형",
            grade="middle_1",
            category="concept",
            part="data",
            description="히스토그램 막대 높이=도수, 도수분포다각형 넓이=히스토그램 넓이",
        ),
        concept(
            id="m1-2-6-3",
            name="상대도수",
            grade="middle_1",
            category="concept",
            part="data",
            description="상대도수=계급도수/전체도수, 총합=1, 두 집단 분포 비교",
        ),
        # 2-7: 대푯값 (2개)
        concept(
            id="m1-2-7-1",
            name="평균/중앙값/최빈값",
            grade="middle_1",
            category="concept",
            part="data",
            description="평균(총합/개수), 중앙값(크기순 가운데), 최빈값(최빈 관측값)",
        ),
        concept(
            id="m1-2-7-2",
            name="상황별 대푯값 선택",
            grade="middle_1",
            category="concept",
            part="data",
            description="극단값 있을 때 중앙값 선호, 맥락적 판단, 데이터 리터러시",
        ),
        # 2-8: 산점도와 상관관계 (2개)
        concept(
            id="m1-2-8-1",
            name="산점도",
            grade="middle_1",
            category="concept",
            part="data",
            description="산점도 작성, 양/음/무 상관관계 판별, 분포 경향 파악",
        ),
        concept(
            id="m1-2-8-2",
            name="상관관계와 인과관계",
            grade="middle_1",
            category="concept",
            part="data",
            description="상관관계 ≠ 인과관계, 제3변수(교란변수), 경향성 vs 원인-결과",
        ),
    ]

    # ============================================================
    # 문제: 8개 개념 × 3문제 = 24개
    # ============================================================
    questions = [
        # [m1-1-1-1] 소수와 합성수
        mc(
            id="m1-1-1-1-cc-001",
            concept_id="m1-1-1-1",
            category="concept",
            part="calc",
            difficulty=2,
            content="다음 중 소수가 아닌 것은?",
            options=["2", "9", "13", "17"],
            correct="B",
            explanation="9 = 3 × 3이므로 합성수입니다. 2는 유일한 짝수 소수입니다.",
            points=10,
        ),
        mc(
            id="m1-1-1-1-cc-002",
            concept_id="m1-1-1-1",
            category="concept",
            part="calc",
            difficulty=4,
            content="다음 중 옳은 것은?",
            options=[
                "4와 9는 서로소이다.",
                "서로소인 두 수는 반드시 모두 소수이다.",
                "1은 가장 작은 소수이다.",
                "합성수는 소인수가 2개 이상이다.",
            ],
            correct="A",
            explanation="4와 9는 공약수가 1뿐이므로 서로소입니다. 서로소는 '관계'를 나타내며 두 수 모두 소수일 필요는 없습니다. 1은 소수도 합성수도 아닙니다.",
            points=10,
        ),
        # [m1-1-2-2] 절대값과 유리수
        mc(
            id="m1-1-2-2-cc-001",
            concept_id="m1-1-2-2",
            category="concept",
            part="calc",
            difficulty=5,
            content="다음 중 옳지 않은 것은?",
            options=[
                "|-5| = 5",
                "-a는 항상 음수이다.",
                "절대값이 같은 두 수는 서로 같거나 부호가 반대이다.",
                "0의 절대값은 0이다.",
            ],
            correct="B",
            explanation="-a가 양수인지 음수인지는 a의 값에 따라 달라집니다. 예를 들어 a = -3이면 -a = 3으로 양수입니다.",
            points=10,
        ),
        # [m1-2-1-1] 순서쌍과 좌표평면
        mc(
            id="m1-2-1-1-cc-001",
            concept_id="m1-2-1-1",
            category="concept",
            part="func",
            difficulty=2,
            content="점 A(3, -2)는 제 몇 사분면에 있는가?",
            options=["제1사분면", "제2사분면", "제3사분면", "제4사분면"],
            correct="D",
            explanation="x > 0, y < 0이므로 제4사분면입니다.",
            points=10,
        ),
        mc(
            id="m1-2-1-1-cc-002",
            concept_id="m1-2-1-1",
            category="concept",
            part="func",
            difficulty=4,
            content="다음 중 옳은 것은?",
            options=[
                "점 (0, 5)는 제1사분면에 있다.",
                "점 (-3, 0)은 제2사분면에 있다.",
                "좌표축 위의 점은 어느 사분면에도 속하지 않는다.",
                "순서쌍 (2, 3)과 (3, 2)는 같은 점이다.",
            ],
            correct="C",
            explanation="좌표축(x축, y축) 위의 점은 어느 사분면에도 속하지 않습니다. (0, 5)는 y축 위, (-3, 0)은 x축 위의 점입니다.",
            points=10,
        ),
        # [m1-2-1-2] 그래프 해석
        mc(
            id="m1-2-1-2-cc-001",
            concept_id="m1-2-1-2",
            category="concept",
            part="func",
            difficulty=6,
            content="다음 그래프가 나타내는 상황으로 적절한 것은? (시간에 따라 처음에는 빠르게 증가하다가 점차 완만하게 증가하는 그래프)",
            options=[
                "일정한 속력으로 달리는 자동차의 이동 거리",
                "물이 일정한 속도로 채워지는 원기둥 모양 물통의 수면 높이",
                "물이 일정한 속도로 채워지는 밑면이 좁고 위가 넓은 물통의 수면 높이",
                "일정한 높이에서 자유낙하하는 물체의 낙하 거리",
            ],
            correct="C",
            explanation="밑면이 좁고 위가 넓은 물통은 처음에는 수면이 빠르게 올라가다가 위로 갈수록 부피가 커져 수면 상승 속도가 느려집니다.",
            points=15,
        ),
        # [m1-2-2-1] 정비례 관계
        mc(
            id="m1-2-2-1-cc-001",
            concept_id="m1-2-2-1",
            category="concept",
            part="func",
            difficulty=3,
            content="y가 x에 정비례하고 x = 2일 때 y = 6이다. x = 5일 때 y의 값은?",
            options=["10", "15", "12", "18"],
            correct="B",
            explanation="y = ax에서 6 = 2a이므로 a = 3. 따라서 y = 3x. x = 5일 때 y = 3 × 5 = 15",
            points=10,
        ),
        # [m1-2-2-2] 반비례 관계
        mc(
            id="m1-2-2-2-cc-001",
            concept_id="m1-2-2-2",
            category="concept",
            part="func",
            difficulty=5,
            content="y가 x에 반비례하고 x = 4일 때 y = 3이다. x = -6일 때 y의 값은?",
            options=["-2", "2", "-8", "8"],
            correct="A",
            explanation="y = a/x에서 3 = a/4이므로 a = 12. 따라서 y = 12/x. x = -6일 때 y = 12/(-6) = -2",
            points=10,
        ),
        # [m1-2-2-3] 정비례/반비례 그래프
        mc(
            id="m1-2-2-3-cc-001",
            concept_id="m1-2-2-3",
            category="concept",
            part="func",
            difficulty=7,
            content="반비례 관계 y = 6/x의 그래프에 대한 설명으로 옳지 않은 것은?",
            options=[
                "원점을 지나지 않는다.",
                "제1사분면과 제3사분면을 지난다.",
                "x축과 y축에 점근한다.",
                "전체 구간에서 연속이다.",
            ],
            correct="D",
            explanation="반비례 그래프는 x = 0에서 정의되지 않으므로 불연속입니다. x > 0 구간과 x < 0 구간이 분리되어 있습니다.",
            points=15,
        ),
        # [m1-2-3-2] 평행선의 성질
        mc(
            id="m1-2-3-2-cc-001",
            concept_id="m1-2-3-2",
            category="concept",
            part="geo",
            difficulty=3,
            content="두 직선이 평행하고 동위각이 40°일 때, 엇각의 크기는?",
            options=["40°", "50°", "140°", "180°"],
            correct="A",
            explanation="평행선에서 동위각과 엇각은 모두 같으므로 40°입니다.",
            points=10,
        ),
        # [m1-2-3-1] 점/선/면과 위치관계
        mc(
            id="m1-2-3-1-cc-001",
            concept_id="m1-2-3-1",
            category="concept",
            part="geo",
            difficulty=5,
            content="다음 중 옳지 않은 것은?",
            options=[
                "두 직선이 평행하면 동위각의 크기가 같다.",
                "동위각의 크기가 같으면 두 직선은 평행하다.",
                "꼬인 위치는 평면에서 나타날 수 있다.",
                "맞꼭지각의 크기는 항상 같다.",
            ],
            correct="C",
            explanation="꼬인 위치는 만나지도 않고 평행하지도 않은 위치 관계로, 공간(입체)에서만 나타납니다.",
            points=10,
        ),
        # [m1-2-3-3] 작도와 삼각형 합동
        mc(
            id="m1-2-3-3-cc-001",
            concept_id="m1-2-3-3",
            category="concept",
            part="geo",
            difficulty=8,
            content="삼각형의 합동 조건이 아닌 것은?",
            options=[
                "세 변의 길이가 각각 같다. (SSS)",
                "두 변의 길이와 그 끼인각의 크기가 같다. (SAS)",
                "두 각의 크기와 그 끼인변의 길이가 같다. (ASA)",
                "두 변의 길이와 한 각의 크기가 같다. (SSA)",
            ],
            correct="D",
            explanation="SSA는 삼각형 합동 조건이 아닙니다. 끼인각이 아닌 다른 각의 경우 두 개의 서로 다른 삼각형이 만들어질 수 있습니다.",
            points=15,
        ),
        # [m1-2-4-1] 다각형의 내각과 외각
        mc(
            id="m1-2-4-1-cc-001",
            concept_id="m1-2-4-1",
            category="concept",
            part="geo",
            difficulty=5,
            content="모든 다각형의 외각의 합은?",
            options=["180°", "360°", "540°", "다각형에 따라 다르다"],
            correct="B",
            explanation="모든 다각형의 외각의 합은 변의 개수에 관계없이 항상 360°입니다.",
            points=10,
        ),
        mc(
            id="m1-2-4-1-cc-002",
            concept_id="m1-2-4-1",
            category="concept",
            part="geo",
            difficulty=3,
            content="칠각형의 내각의 합은?",
            options=["720°", "900°", "1080°", "1260°"],
            correct="B",
            explanation="n각형 내각의 합 = (n-2) × 180°. 칠각형(n=7): (7-2) × 180° = 5 × 180° = 900°",
            points=10,
        ),
        # [m1-2-4-2] 원과 부채꼴의 성질
        mc(
            id="m1-2-4-2-cc-001",
            concept_id="m1-2-4-2",
            category="concept",
            part="geo",
            difficulty=7,
            content="반지름이 6cm인 원에서 중심각이 60°인 부채꼴의 넓이는? (π 사용)",
            options=["3π cm²", "6π cm²", "9π cm²", "12π cm²"],
            correct="B",
            explanation="부채꼴 넓이 = πr² × (중심각/360°) = π × 6² × (60/360) = 36π × (1/6) = 6π cm²",
            points=15,
        ),
        # [m1-2-5-2] 겉넓이와 부피
        mc(
            id="m1-2-5-2-cc-001",
            concept_id="m1-2-5-2",
            category="concept",
            part="geo",
            difficulty=4,
            content="밑면의 반지름이 3cm, 높이가 4cm인 원기둥의 부피는? (π 사용)",
            options=["12π cm³", "24π cm³", "36π cm³", "48π cm³"],
            correct="C",
            explanation="원기둥 부피 = πr²h = π × 3² × 4 = 36π cm³",
            points=10,
        ),
        mc(
            id="m1-2-5-2-cc-002",
            concept_id="m1-2-5-2",
            category="concept",
            part="geo",
            difficulty=6,
            content="구의 반지름이 2배가 되면 부피는 몇 배가 되는가?",
            options=["2배", "4배", "6배", "8배"],
            correct="D",
            explanation="구의 부피 = (4/3)πr³. 반지름이 2배가 되면 r³은 2³ = 8배가 되므로 부피도 8배입니다.",
            points=10,
        ),
        mc(
            id="m1-2-5-2-cc-003",
            concept_id="m1-2-5-2",
            category="concept",
            part="geo",
            difficulty=8,
            content="원뿔의 전개도에서 옆면인 부채꼴의 호의 길이는 무엇과 같은가?",
            options=[
                "원뿔의 높이",
                "원뿔 밑면의 지름",
                "원뿔 밑면의 둘레",
                "원뿔의 모선",
            ],
            correct="C",
            explanation="원뿔 전개도의 부채꼴 호의 길이는 밑면 원의 둘레와 같습니다. 이는 전개도를 접었을 때 호가 밑면 둘레와 정확히 맞닿기 때문입니다.",
            points=15,
        ),
        # [m1-2-6-1] 줄기와 잎 그림/도수분포표
        mc(
            id="m1-2-6-1-cc-001",
            concept_id="m1-2-6-1",
            category="concept",
            part="data",
            difficulty=3,
            content="계급이 '10 이상 20 미만'일 때 계급값은?",
            options=["10", "15", "20", "30"],
            correct="B",
            explanation="계급값 = (계급의 양 끝값의 합) ÷ 2 = (10 + 20) ÷ 2 = 15",
            points=10,
        ),
        # [m1-2-6-3] 상대도수
        mc(
            id="m1-2-6-3-cc-001",
            concept_id="m1-2-6-3",
            category="concept",
            part="data",
            difficulty=5,
            content="도수분포표에서 어떤 계급의 상대도수가 0.25이고 전체 도수가 40일 때, 이 계급의 도수는?",
            options=["8", "10", "12", "15"],
            correct="B",
            explanation="상대도수 = (계급의 도수) ÷ (전체 도수). 0.25 = (도수) ÷ 40이므로 도수 = 0.25 × 40 = 10",
            points=10,
        ),
        # [m1-2-6-2] 히스토그램과 도수분포다각형
        mc(
            id="m1-2-6-2-cc-001",
            concept_id="m1-2-6-2",
            category="concept",
            part="data",
            difficulty=7,
            content="히스토그램에서 막대의 높이는 무엇을 나타내는가?",
            options=["변량의 크기", "도수", "상대도수", "계급값"],
            correct="B",
            explanation="히스토그램의 막대 높이는 각 계급의 도수(빈도)를 나타냅니다.",
            points=15,
        ),
        # [m1-2-7-1] 평균/중앙값/최빈값
        mc(
            id="m1-2-7-1-cc-001",
            concept_id="m1-2-7-1",
            category="concept",
            part="data",
            difficulty=4,
            content="자료 2, 5, 3, 8, 2의 중앙값은?",
            options=["2", "3", "4", "5"],
            correct="B",
            explanation="크기순으로 정렬: 2, 2, 3, 5, 8. 가운데 값인 3이 중앙값입니다.",
            points=10,
        ),
        # [m1-2-7-2] 상황별 대푯값 선택
        mc(
            id="m1-2-7-2-cc-001",
            concept_id="m1-2-7-2",
            category="concept",
            part="data",
            difficulty=6,
            content="어느 반 학생들의 용돈 조사 결과, 평균은 5만원인데 재벌 2세 학생 한 명이 100만원을 받는다. 이 반의 대푯값으로 가장 적절한 것은?",
            options=[
                "평균 (극단값 영향 받음)",
                "중앙값 (극단값 영향 안 받음)",
                "최빈값 (가장 많이 나타나는 값)",
                "셋 다 동등하게 적절함",
            ],
            correct="B",
            explanation="극단값(outlier)이 있는 경우 평균은 왜곡되므로 중앙값이 더 대표적입니다.",
            points=10,
        ),
        mc(
            id="m1-2-7-1-cc-002",
            concept_id="m1-2-7-1",
            category="concept",
            part="data",
            difficulty=8,
            content="자료가 10개일 때 중앙값은 어떻게 구하는가?",
            options=[
                "5번째 값",
                "6번째 값",
                "5번째와 6번째 값의 평균",
                "중앙값을 구할 수 없다",
            ],
            correct="C",
            explanation="자료가 짝수 개일 때는 크기순 정렬 후 가운데 두 값의 평균을 중앙값으로 합니다.",
            points=15,
        ),
        # [m1-2-8-1] 산점도
        mc(
            id="m1-2-8-1-cc-001",
            concept_id="m1-2-8-1",
            category="concept",
            part="data",
            difficulty=4,
            content="산점도에서 점들이 우상향으로 분포할 때 이를 무엇이라 하는가?",
            options=["양의 상관관계", "음의 상관관계", "상관관계 없음", "인과관계"],
            correct="A",
            explanation="x가 증가할 때 y도 증가하는 경향을 양의 상관관계라고 합니다.",
            points=10,
        ),
        mc(
            id="m1-2-8-1-cc-002",
            concept_id="m1-2-8-1",
            category="concept",
            part="data",
            difficulty=6,
            content="다음 중 음의 상관관계를 보이는 것은?",
            options=[
                "키와 몸무게",
                "기온과 아이스크림 판매량",
                "기온과 난방비",
                "공부 시간과 성적",
            ],
            correct="C",
            explanation="기온이 올라가면 난방비는 감소하므로 음의 상관관계입니다.",
            points=10,
        ),
        # [m1-2-8-2] 상관관계와 인과관계를
        mc(
            id="m1-2-8-2-cc-001",
            concept_id="m1-2-8-2",
            category="concept",
            part="data",
            difficulty=9,
            content="다음 중 옳은 것은?",
            options=[
                "양의 상관관계가 있으면 인과관계가 있다.",
                "상관관계는 경향성일 뿐 원인-결과를 보장하지 않는다.",
                "산점도의 모든 점이 일직선 위에 있어야 상관관계가 있다.",
                "상관관계가 없으면 두 변수는 완전히 독립적이다.",
            ],
            correct="B",
            explanation="상관관계는 두 변수 사이의 경향성을 나타낼 뿐, 인과관계(원인-결과)를 의미하지는 않습니다. 예: 키와 몸무게는 양의 상관관계가 있지만 '키가 원인'이라고 단정할 수 없습니다.",
            points=20,
        ),
        # ────────────────────────────────────────────────────────
        # 1단원 개념 문제 (소인수분해, 정수와 유리수, 문자와 식, 일차방정식)
        # ────────────────────────────────────────────────────────
        # [m1-1-1-1] 소수와 합성수
        mc(
            id="m1-1-1-1-cc-003",
            concept_id="m1-1-1-1",
            category="concept",
            part="calc",
            difficulty=2,
            content="다음 중 소수(素數)의 정의로 올바른 것은?",
            options=[
                "1보다 큰 자연수 중 1과 자기 자신만을 약수로 가지는 수",
                "약수가 하나뿐인 수",
                "모든 홀수",
                "2의 배수가 아닌 자연수",
            ],
            correct="A",
            explanation="소수는 1보다 큰 자연수 중 약수가 1과 자기 자신 두 개뿐인 수입니다. 1은 소수가 아니며, 2는 유일한 짝수 소수입니다.",
            points=10,
        ),
        mc(
            id="m1-1-1-1-cc-004",
            concept_id="m1-1-1-1",
            category="concept",
            part="calc",
            difficulty=5,
            content="1에 대한 설명으로 옳은 것은?",
            options=[
                "소수도 합성수도 아니다",
                "가장 작은 소수이다",
                "가장 작은 합성수이다",
                "소수이면서 합성수이다",
            ],
            correct="A",
            explanation="1은 약수가 자기 자신뿐(1개)이므로 소수(약수 2개)에도 합성수(약수 3개 이상)에도 해당하지 않습니다.",
            points=10,
        ),
        # [m1-1-1-3] 최대공약수와 최소공배수
        mc(
            id="m1-1-1-3-cc-001",
            concept_id="m1-1-1-3",
            category="concept",
            part="calc",
            difficulty=7,
            content="두 자연수 A, B의 최대공약수가 G이고 최소공배수가 L일 때, A × B와 G × L의 관계는?",
            options=["A × B = G × L", "A × B = G + L", "A + B = G × L", "A × B = G² × L"],
            correct="A",
            explanation="두 자연수의 곱은 최대공약수와 최소공배수의 곱과 같습니다. 예: 12 × 18 = 216, GCD(12,18) = 6, LCM(12,18) = 36, 6 × 36 = 216",
            points=15,
        ),
        # [m1-1-2-1] 정수의 분류와 수직선
        mc(
            id="m1-1-2-1-cc-001",
            concept_id="m1-1-2-1",
            category="concept",
            part="calc",
            difficulty=2,
            content="다음 중 정수의 분류로 올바른 것은?",
            options=[
                "양의 정수, 0, 음의 정수",
                "자연수와 음수",
                "짝수와 홀수",
                "소수와 합성수",
            ],
            correct="A",
            explanation="정수는 양의 정수(자연수), 0, 음의 정수의 세 종류로 분류됩니다. 0은 양의 정수도 음의 정수도 아닙니다.",
            points=10,
        ),
        # [m1-1-2-2] 절대값과 유리수
        mc(
            id="m1-1-2-2-cc-002",
            concept_id="m1-1-2-2",
            category="concept",
            part="calc",
            difficulty=5,
            content="다음 중 유리수에 대한 설명으로 올바른 것은?",
            options=[
                "정수의 비(a/b, b ≠ 0)로 나타낼 수 있는 수",
                "소수점 아래가 끝나는 수만 해당된다",
                "양수만 유리수이다",
                "정수는 유리수가 아니다",
            ],
            correct="A",
            explanation="유리수는 두 정수의 비(a/b, b ≠ 0)로 나타낼 수 있는 수입니다. 정수도 a/1 형태이므로 유리수에 포함됩니다.",
            points=10,
        ),
        mc(
            id="m1-1-2-1-cc-002",
            concept_id="m1-1-2-1",
            category="concept",
            part="calc",
            difficulty=7,
            content="두 수 -5와 -3의 대소 관계로 올바른 것은?",
            options=["-5 < -3", "-5 > -3", "-5 = -3", "비교할 수 없다"],
            correct="A",
            explanation="음수끼리는 절대값이 작은 수가 더 큽니다. |-3| = 3 < |-5| = 5이므로 -3 > -5, 즉 -5 < -3입니다. 수직선에서 오른쪽에 있는 수가 더 큽니다.",
            points=15,
        ),
        # [m1-1-3-1] 문자의 사용과 대수적 관습
        mc(
            id="m1-1-3-1-cc-001",
            concept_id="m1-1-3-1",
            category="concept",
            part="algebra",
            difficulty=2,
            content="'한 개에 a원인 사과 5개의 가격'을 식으로 나타내면?",
            options=["5a원", "a + 5원", "a ÷ 5원", "a - 5원"],
            correct="A",
            explanation="문자를 사용한 식에서 숫자와 문자의 곱은 곱셈 기호를 생략하고 숫자를 문자 앞에 씁니다. 사과 5개 × a원 = 5a원",
            points=10,
        ),
        # [m1-1-3-2] 동류항과 식의 계산
        mc(
            id="m1-1-3-2-cc-001",
            concept_id="m1-1-3-2",
            category="concept",
            part="algebra",
            difficulty=5,
            content="다음 중 동류항끼리 짝지어진 것은?",
            options=["3x와 -5x", "3x와 3y", "2x²와 2x", "5와 5x"],
            correct="A",
            explanation="동류항은 문자와 차수가 같은 항입니다. 3x와 -5x는 둘 다 x에 대한 일차항이므로 동류항입니다. 3x와 3y는 문자가 다르고, 2x²와 2x는 차수가 다릅니다.",
            points=10,
        ),
        # [m1-1-3-3] 대입과 식의 값
        mc(
            id="m1-1-3-3-cc-001",
            concept_id="m1-1-3-3",
            category="concept",
            part="algebra",
            difficulty=7,
            content="식의 값을 구할 때, 문자에 수를 넣는 것을 무엇이라 하는가?",
            options=["대입", "이항", "전개", "인수분해"],
            correct="A",
            explanation="문자에 특정 수를 넣어 식의 값을 구하는 것을 '대입'이라고 합니다. 예: x = 3일 때 2x + 1의 값은 2(3) + 1 = 7",
            points=15,
        ),
        # [m1-1-4-1] 방정식과 등식의 성질
        mc(
            id="m1-1-4-1-cc-001",
            concept_id="m1-1-4-1",
            category="concept",
            part="algebra",
            difficulty=2,
            content="다음 중 방정식인 것은?",
            options=["2x + 3 = 7", "2x + 3", "x > 5", "2 + 3 = 5"],
            correct="A",
            explanation="방정식은 미지수를 포함하는 등식입니다. '2x + 3'은 식이고, 'x > 5'는 부등식이며, '2 + 3 = 5'는 등식이지만 미지수가 없습니다.",
            points=10,
        ),
        mc(
            concept_id="concept-m1-eq-01",
            category="concept",
            part="algebra",
            difficulty=5,
            content="등식의 성질로 올바른 것은?",
            options=[
                "양변에 같은 수를 더해도 등식은 성립한다",
                "양변에 다른 수를 더해도 등식은 성립한다",
                "한쪽에만 수를 더해도 등식은 성립한다",
                "양변에 0을 곱하면 등식이 성립하지 않는다",
            ],
            correct="A",
            explanation="등식의 양변에 같은 수를 더하거나 빼도, 같은 수를 곱하거나 0이 아닌 같은 수로 나누어도 등식은 성립합니다.",
            points=10,
        ),
        mc(
            id="m1-1-04-01-lv07-cc-001",
            concept_id="concept-m1-eq-01",
            category="concept",
            part="algebra",
            difficulty=7,
            content="일차방정식 3x + 2 = 11에서 x = 3이 '해'인 이유는?",
            options=[
                "x = 3을 대입하면 좌변 = 우변이 되기 때문",
                "x = 3이 가장 작은 자연수이기 때문",
                "3은 소수이기 때문",
                "좌변이 우변보다 크기 때문",
            ],
            correct="A",
            explanation="방정식의 해는 등식을 참으로 만드는 미지수의 값입니다. 3(3) + 2 = 9 + 2 = 11 = 우변이므로 x = 3은 이 방정식의 해입니다.",
            points=15,
        ),
    ]

    # ============================================================
    # 테스트
    # ============================================================
    tests = [
        test(
            id="test-m1-func",
            title="중1 함수와 좌표",
            description="좌표평면, 정비례, 반비례",
            grade="middle_1",
            concept_ids=[
                "concept-m1-coord-01",
                "concept-m1-coord-02",
                "concept-m1-prop-01",
                "concept-m1-prop-02",
                "concept-m1-prop-03",
            ],
            question_ids=[
                "m1-2-05-01-lv02-cc-001",
                "m1-2-05-01-lv04-cc-001",
                "m1-2-05-02-lv06-cc-001",
                "m1-2-06-01-lv03-cc-001",
                "m1-2-06-02-lv05-cc-001",
                "m1-2-06-03-lv07-cc-001",
            ],
            time_limit_minutes=10,
            use_question_pool=True,
            questions_per_attempt=5,
        ),
        test(
            id="test-m1-geometry",
            title="중1 도형 종합",
            description="기본 도형, 평면도형, 입체도형",
            grade="middle_1",
            concept_ids=[
                "concept-m1-geo-01",
                "concept-m1-geo-02",
                "concept-m1-geo-03",
                "concept-m1-plane-01",
                "concept-m1-plane-02",
                "concept-m1-solid-01",
                "concept-m1-solid-02",
                "concept-m1-solid-03",
            ],
            question_ids=[
                "m1-2-07-02-lv03-cc-001",
                "m1-2-07-01-lv05-cc-001",
                "m1-2-07-03-lv08-cc-001",
                "m1-2-08-01-lv03-cc-001",
                "m1-2-08-01-lv05-cc-001",
                "m1-2-08-02-lv07-cc-001",
                "m1-2-09-02-lv04-cc-001",
                "m1-2-09-02-lv06-cc-001",
                "m1-2-09-02-lv08-cc-001",
            ],
            time_limit_minutes=15,
            use_question_pool=True,
            questions_per_attempt=7,
        ),
        test(
            id="test-m1-statistics",
            title="중1 통계와 자료",
            description="자료 정리, 대푯값, 산점도",
            grade="middle_1",
            concept_ids=[
                "concept-m1-freq-01",
                "concept-m1-freq-02",
                "concept-m1-freq-03",
                "concept-m1-repr-01",
                "concept-m1-repr-02",
                "concept-m1-scat-01",
                "concept-m1-scat-02",
            ],
            question_ids=[
                "m1-2-10-01-lv03-cc-001",
                "m1-2-10-03-lv05-cc-001",
                "m1-2-10-02-lv07-cc-001",
                "m1-2-11-01-lv04-cc-001",
                "m1-2-11-02-lv06-cc-001",
                "m1-2-11-01-lv08-cc-001",
                "m1-2-12-01-lv04-cc-001",
                "m1-2-12-01-lv06-cc-001",
                "m1-2-12-02-lv09-cc-001",
            ],
            time_limit_minutes=15,
            use_question_pool=True,
            questions_per_attempt=7,
        ),
        test(
            id="test-m1-ch1-concept",
            title="중1 수와 연산 개념",
            description="소인수분해, 정수와 유리수, 문자와 식, 일차방정식의 개념 이해",
            grade="middle_1",
            concept_ids=[
                "concept-m1-prime-01",
                "concept-m1-prime-03",
                "concept-m1-int-01",
                "concept-m1-int-02",
                "concept-m1-expr-01",
                "concept-m1-expr-02",
                "concept-m1-expr-03",
                "concept-m1-eq-01",
            ],
            question_ids=[
                "m1-1-01-01-lv02-cc-002",
                "m1-1-01-01-lv05-cc-001",
                "m1-1-01-03-lv07-cc-001",
                "m1-1-02-01-lv02-cc-001",
                "m1-1-02-02-lv05-cc-002",
                "m1-1-02-01-lv07-cc-001",
                "m1-1-03-01-lv02-cc-001",
                "m1-1-03-02-lv05-cc-001",
                "m1-1-03-03-lv07-cc-001",
                "m1-1-04-01-lv02-cc-001",
                "m1-1-04-01-lv05-cc-001",
                "m1-1-04-01-lv07-cc-001",
            ],
            time_limit_minutes=15,
            use_question_pool=True,
            questions_per_attempt=8,
        ),
    ]

    return {
        "concepts": concepts,
        "questions": questions,
        "tests": tests,
    }
