"""초등 4학년 연산 문제 시드 데이터.

커버 단원:
  1학기 1단원 - 큰 수
  1학기 3단원 - 곱셈과 나눗셈
  2학기 1단원 - 분수의 덧셈과 뺄셈
  2학기 3단원 - 소수의 덧셈과 뺄셈

총 41개 문제 (개념당 5개)
"""
from app.seeds._base import mc, concept


def get_concepts():
    """연산 관련 개념 반환."""
    return [
        concept(
            id="concept-e4-big-num-01",
            name="큰 수 - 십진기수법과 자릿값",
            grade="elementary_4",
            category="computation",
            part="calc",
            description="만, 억, 조 단위의 큰 수를 읽고 쓸 수 있으며, 10배의 원리와 자릿값을 이해합니다.",
        ),
        concept(
            id="concept-e4-big-num-02",
            name="큰 수 - 수의 크기 비교",
            grade="elementary_4",
            category="computation",
            part="calc",
            description="자릿수가 같은 큰 수의 크기를 최상위 자릿수부터 비교하여 대소를 판단합니다.",
        ),
        concept(
            id="concept-e4-mul-div-01",
            name="곱셈과 나눗셈 - 곱셈 알고리즘",
            grade="elementary_4",
            category="computation",
            part="calc",
            description="(세 자리 수)×(두 자리 수) 세로셈을 이해하고 정확히 계산할 수 있습니다.",
        ),
        concept(
            id="concept-e4-mul-div-02",
            name="곱셈과 나눗셈 - 나눗셈과 검산",
            grade="elementary_4",
            category="computation",
            part="calc",
            description="(세 자리 수)÷(두 자리 수) 계산과 검산(나누는 수×몫+나머지=나누어지는 수), 나머지의 맥락적 해석을 할 수 있습니다.",
        ),
        concept(
            id="concept-e4-frac-op-01",
            name="분수의 덧셈과 뺄셈 - 동분모 진분수 연산",
            grade="elementary_4",
            category="computation",
            part="calc",
            description="분모가 같은 분수의 덧셈·뺄셈에서 분모는 그대로 두고 분자끼리 연산합니다.",
        ),
        concept(
            id="concept-e4-frac-op-02",
            name="분수의 덧셈과 뺄셈 - 대분수와 받아내림",
            grade="elementary_4",
            category="computation",
            part="calc",
            description="대분수의 덧셈·뺄셈(받아내림 포함)을 이해하고, 자연수에서 분수를 빼는 계산을 할 수 있습니다.",
        ),
        concept(
            id="concept-e4-dec-op-01",
            name="소수의 덧셈과 뺄셈 - 소수 구조와 크기 비교",
            grade="elementary_4",
            category="computation",
            part="calc",
            description="소수의 자릿값(0.01, 0.001)을 이해하고, 소수점 아래 같은 자리부터 크기를 비교합니다.",
        ),
        concept(
            id="concept-e4-dec-op-02",
            name="소수의 덧셈과 뺄셈 - 소수 덧뺄셈 계산",
            grade="elementary_4",
            category="computation",
            part="calc",
            description="소수점 위치를 맞추어 정렬한 덧셈과 뺄셈을 정확히 계산할 수 있습니다.",
        ),
    ]


def get_questions():
    """연산 문제 반환."""
    return [
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 1단원: 큰 수
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━

        # concept-e4-big-num-01: 큰 수 - 십진기수법과 자릿값 (5개)
        mc(
            id="e4-1-1-1-lv02-co-001",
            concept_id="concept-e4-big-num-01",
            category="computation",
            part="calc",
            difficulty=2,
            content="삼억 오천만을 숫자로 바르게 쓴 것은?",
            options=[
                "35000000",
                "305000000",
                "350000000",
                "3500000000",
            ],
            correct="C",
            explanation="삼억 오천만 = 3억 5000만 = 350,000,000입니다. 억 자리에 3, 천만 자리에 5를 쓰고 나머지는 0으로 채웁니다. 0이 포함된 큰 수를 쓸 때 빈 자리를 누락하지 않도록 주의합니다.",
            points=10,
        ),
        mc(
            id="e4-1-1-1-lv04-co-001",
            concept_id="concept-e4-big-num-01",
            category="computation",
            part="calc",
            difficulty=4,
            content="50000에서 숫자 5가 나타내는 값은?",
            options=[
                "5",
                "500",
                "5000",
                "50000",
            ],
            correct="D",
            explanation="50000에서 5는 만의 자리에 있으므로 5가 나타내는 값(자릿값)은 50000입니다. 숫자 자체(5)와 자릿값(50000)을 구별해야 합니다.",
            points=10,
        ),
        mc(
            id="e4-1-1-1-lv03-co-001",
            concept_id="concept-e4-big-num-01",
            category="computation",
            part="calc",
            difficulty=3,
            content="칠억 사천삼백만을 숫자로 쓰면?",
            options=[
                "74300000",
                "704300000",
                "743000000",
                "7430000000",
            ],
            correct="C",
            explanation="칠억 사천삼백만 = 7억 4300만 = 743,000,000입니다. 억 자리에 7, 천만 자리에 4, 백만 자리에 3을 쓰고 나머지는 0으로 채웁니다.",
            points=10,
        ),
        mc(
            id="e4-1-1-1-lv05-co-001",
            concept_id="concept-e4-big-num-01",
            category="computation",
            part="calc",
            difficulty=5,
            content="8000000에서 8이 나타내는 값은 800000의 몇 배인가?",
            options=[
                "10배",
                "100배",
                "1000배",
                "10000배",
            ],
            correct="A",
            explanation="8000000에서 8은 백만의 자리(1,000,000), 800000에서 8은 십만의 자리(100,000)입니다. 1,000,000 ÷ 100,000 = 10배입니다.",
            points=10,
        ),
        mc(
            id="e4-1-1-1-lv06-co-001",
            concept_id="concept-e4-big-num-01",
            category="computation",
            part="calc",
            difficulty=6,
            content="십억을 1000만으로 나타내면?",
            options=[
                "100",
                "1000",
                "10000",
                "100000",
            ],
            correct="A",
            explanation="10억 = 1,000,000,000, 1000만 = 10,000,000입니다. 1,000,000,000 ÷ 10,000,000 = 100이므로 십억은 1000만의 100배입니다.",
            points=10,
        ),

        # concept-e4-big-num-02: 큰 수 - 수의 크기 비교 (5개)
        mc(
            id="e4-1-1-2-lv06-co-001",
            concept_id="concept-e4-big-num-02",
            category="computation",
            part="calc",
            difficulty=6,
            content="다음 중 가장 큰 수는?",
            options=[
                "9억 9800만",
                "10억 50만",
                "9억 9999만",
                "10억",
            ],
            correct="B",
            explanation="각 수를 비교하면 A=998,000,000, B=1,000,500,000, C=999,900,000, D=1,000,000,000입니다. 자릿수가 같으면 최상위 자릿수부터 비교합니다. 10억 50만(B)이 가장 큽니다.",
            points=10,
        ),
        mc(
            id="e4-1-1-2-lv04-co-001",
            concept_id="concept-e4-big-num-02",
            category="computation",
            part="calc",
            difficulty=4,
            content="다음 중 가장 작은 수는?",
            options=[
                "4억 5000만",
                "4억 500만",
                "4억 5만",
                "4억 5천만",
            ],
            correct="C",
            explanation="A=450,000,000, B=405,000,000, C=400,050,000, D=450,000,000입니다. C(4억 5만)가 가장 작습니다.",
            points=10,
        ),
        mc(
            id="e4-1-1-2-lv05-co-001",
            concept_id="concept-e4-big-num-02",
            category="computation",
            part="calc",
            difficulty=5,
            content="623000000과 크기가 같은 것은?",
            options=[
                "62억 3천만",
                "6억 2300만",
                "6억 23만",
                "6억 2천3백만",
            ],
            correct="D",
            explanation="623000000 = 6억 2천3백만입니다. 억 자리에 6, 천만 자리에 2, 백만 자리에 3이 있습니다.",
            points=10,
        ),
        mc(
            id="e4-1-1-2-lv07-co-001",
            concept_id="concept-e4-big-num-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="빈칸에 들어갈 수 있는 수는 몇 개인가? (5억 3천만 < □억 < 6억)",
            options=[
                "5개",
                "6개",
                "7개",
                "8개",
            ],
            correct="B",
            explanation="5억 3천만 = 530,000,000 < □억 < 600,000,000입니다. □억은 540,000,000(5억 4천만), 550,000,000(5억 5천만), 560,000,000(5억 6천만), 570,000,000(5억 7천만), 580,000,000(5억 8천만), 590,000,000(5억 9천만) 총 6개입니다.",
            points=10,
        ),
        mc(
            id="e4-1-1-2-lv08-co-001",
            concept_id="concept-e4-big-num-02",
            category="computation",
            part="calc",
            difficulty=8,
            content="다음 중 작은 것부터 순서대로 나열한 것은? (가: 7억 80만, 나: 7억 8백만, 다: 7억 8만)",
            options=[
                "다 < 가 < 나",
                "가 < 다 < 나",
                "다 < 나 < 가",
                "나 < 가 < 다",
            ],
            correct="A",
            explanation="가=700,800,000, 나=708,000,000, 다=700,080,000입니다. 다(7억 8만) < 가(7억 80만) < 나(7억 8백만) 순서입니다.",
            points=10,
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 3단원: 곱셈과 나눗셈
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━

        # concept-e4-mul-div-01: 곱셈 알고리즘 (5개)
        mc(
            id="e4-1-3-1-lv03-co-001",
            concept_id="concept-e4-mul-div-01",
            category="computation",
            part="calc",
            difficulty=3,
            content="245 × 13을 계산하세요.",
            options=[
                "3085",
                "3185",
                "3285",
                "3385",
            ],
            correct="B",
            explanation="245 × 13 = 3185입니다. 245×3=735, 245×10=2450, 735+2450=3185입니다. 세로셈에서 자릿수를 정확히 맞추어야 합니다.",
            points=10,
        ),
        mc(
            id="e4-1-3-1-lv04-co-001",
            concept_id="concept-e4-mul-div-01",
            category="computation",
            part="calc",
            difficulty=4,
            content="328 × 25를 계산하세요.",
            options=[
                "7900",
                "8100",
                "8200",
                "8300",
            ],
            correct="C",
            explanation="328 × 25 = 8200입니다. 328×5=1640, 328×20=6560, 1640+6560=8200입니다.",
            points=10,
        ),
        mc(
            id="e4-1-3-1-lv05-co-001",
            concept_id="concept-e4-mul-div-01",
            category="computation",
            part="calc",
            difficulty=5,
            content="467 × 38을 계산하세요.",
            options=[
                "17546",
                "17646",
                "17746",
                "17846",
            ],
            correct="A",
            explanation="467 × 38 = 17546입니다. 467×8=3736, 467×30=14010, 3736+14010=17546입니다.",
            points=10,
        ),
        mc(
            id="e4-1-3-1-lv06-co-001",
            concept_id="concept-e4-mul-div-01",
            category="computation",
            part="calc",
            difficulty=6,
            content="592 × 47을 계산하세요.",
            options=[
                "27724",
                "27824",
                "27924",
                "28024",
            ],
            correct="B",
            explanation="592 × 47 = 27824입니다. 592×7=4144, 592×40=23680, 4144+23680=27824입니다.",
            points=10,
        ),
        mc(
            id="e4-1-3-1-lv07-co-001",
            concept_id="concept-e4-mul-div-01",
            category="computation",
            part="calc",
            difficulty=7,
            content="835 × 64를 계산하세요.",
            options=[
                "53340",
                "53440",
                "53540",
                "53640",
            ],
            correct="B",
            explanation="835 × 64 = 53440입니다. 835×4=3340, 835×60=50100, 3340+50100=53440입니다.",
            points=10,
        ),

        # concept-e4-mul-div-02: 나눗셈과 검산 (5개)
        mc(
            id="e4-1-3-2-lv05-co-001",
            concept_id="concept-e4-mul-div-02",
            category="computation",
            part="calc",
            difficulty=5,
            content="756 ÷ 12를 계산하세요.",
            options=[
                "61",
                "62",
                "63",
                "64",
            ],
            correct="C",
            explanation="756 ÷ 12 = 63입니다. 검산: 12 × 63 = 756이므로 정답입니다. 몫을 가늠할 때 12×60=720, 12×70=840이므로 몫은 60~70 사이입니다.",
            points=10,
        ),
        mc(
            id="e4-1-3-2-lv08-co-001",
            concept_id="concept-e4-mul-div-02",
            category="computation",
            part="calc",
            difficulty=8,
            content="빵 365개를 한 상자에 24개씩 담으려 합니다. 모든 빵을 담으려면 상자는 최소 몇 개 필요한가요?",
            options=[
                "14개",
                "15개",
                "16개",
                "17개",
            ],
            correct="C",
            explanation="365 ÷ 24 = 15 나머지 5입니다. 나머지 5개도 상자에 담아야 하므로 15+1=16개가 필요합니다. 나머지를 맥락에 맞게 해석(올림)하는 것이 중요합니다.",
            points=10,
        ),
        mc(
            id="e4-1-3-2-lv04-co-001",
            concept_id="concept-e4-mul-div-02",
            category="computation",
            part="calc",
            difficulty=4,
            content="936 ÷ 18을 계산하세요.",
            options=[
                "50",
                "51",
                "52",
                "53",
            ],
            correct="C",
            explanation="936 ÷ 18 = 52입니다. 검산: 18 × 52 = 936이므로 정답입니다.",
            points=10,
        ),
        mc(
            id="e4-1-3-2-lv06-co-001",
            concept_id="concept-e4-mul-div-02",
            category="computation",
            part="calc",
            difficulty=6,
            content="845 ÷ 25를 계산하면 몫과 나머지는?",
            options=[
                "몫 33, 나머지 20",
                "몫 33, 나머지 15",
                "몫 34, 나머지 5",
                "몫 34, 나머지 0",
            ],
            correct="A",
            explanation="845 ÷ 25 = 33 나머지 20입니다. 검산: 25 × 33 + 20 = 825 + 20 = 845로 정답입니다.",
            points=10,
        ),
        mc(
            id="e4-1-3-2-lv07-co-001",
            concept_id="concept-e4-mul-div-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="427 ÷ 32를 계산하면 몫과 나머지는?",
            options=[
                "몫 13, 나머지 11",
                "몫 13, 나머지 12",
                "몫 13, 나머지 13",
                "몫 14, 나머지 11",
            ],
            correct="A",
            explanation="427 ÷ 32 = 13 나머지 11입니다. 검산: 32 × 13 + 11 = 416 + 11 = 427로 정답입니다.",
            points=10,
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 1단원: 분수의 덧셈과 뺄셈
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━

        # concept-e4-frac-op-01: 동분모 진분수 연산 (5개)
        mc(
            id="e4-2-1-1-lv02-co-001",
            concept_id="concept-e4-frac-op-01",
            category="computation",
            part="calc",
            difficulty=2,
            content="3/8 + 2/8을 계산하세요.",
            options=[
                "5/16",
                "5/8",
                "6/8",
                "1/8",
            ],
            correct="B",
            explanation="분모가 같은 분수의 덧셈은 분모는 그대로 두고 분자끼리 더합니다. 3/8 + 2/8 = 5/8입니다. 5/16(분모끼리 더한 결과)은 틀린 답입니다.",
            points=10,
        ),
        mc(
            id="e4-2-1-1-lv05-co-001",
            concept_id="concept-e4-frac-op-01",
            category="computation",
            part="calc",
            difficulty=5,
            content="1/3 + 1/3의 계산으로 올바른 것은?",
            options=[
                "2/6",
                "2/3",
                "1/6",
                "1/3",
            ],
            correct="B",
            explanation="분모가 같은 분수의 덧셈은 분자끼리만 더합니다. 1/3 + 1/3 = 2/3입니다. 분모끼리 더해 2/6으로 계산하는 것은 가장 흔한 오류입니다.",
            points=10,
        ),
        mc(
            id="e4-2-1-1-lv03-co-001",
            concept_id="concept-e4-frac-op-01",
            category="computation",
            part="calc",
            difficulty=3,
            content="7/9 - 4/9를 계산하세요.",
            options=[
                "3/9",
                "3/0",
                "11/9",
                "11/18",
            ],
            correct="A",
            explanation="분모가 같은 분수의 뺄셈은 분모는 그대로 두고 분자끼리 뺍니다. 7/9 - 4/9 = 3/9입니다. 3/9는 1/3으로 약분할 수 있습니다.",
            points=10,
        ),
        mc(
            id="e4-2-1-1-lv04-co-001",
            concept_id="concept-e4-frac-op-01",
            category="computation",
            part="calc",
            difficulty=4,
            content="5/12 + 7/12를 계산하세요.",
            options=[
                "1",
                "12/24",
                "12/12",
                "2/12",
            ],
            correct="C",
            explanation="5/12 + 7/12 = 12/12입니다. 12/12 = 1이므로 답은 1입니다.",
            points=10,
        ),
        mc(
            id="e4-2-1-1-lv06-co-001",
            concept_id="concept-e4-frac-op-01",
            category="computation",
            part="calc",
            difficulty=6,
            content="11/15 - 4/15를 계산하세요.",
            options=[
                "7/15",
                "7/0",
                "15/15",
                "7/30",
            ],
            correct="A",
            explanation="11/15 - 4/15 = 7/15입니다. 분모는 그대로 두고 분자끼리 뺍니다.",
            points=10,
        ),

        # concept-e4-frac-op-02: 대분수와 받아내림 (5개)
        mc(
            id="e4-2-1-2-lv08-co-001",
            concept_id="concept-e4-frac-op-02",
            category="computation",
            part="calc",
            difficulty=8,
            content="3 - 2/5를 계산하세요.",
            options=[
                "1/5",
                "2 3/5",
                "1 2/5",
                "2 2/5",
            ],
            correct="B",
            explanation="자연수에서 분수를 빼려면 3을 2 5/5로 바꿉니다. 2 5/5 - 2/5 = 2 3/5입니다. 자연수에서 1을 빌려와 분모와 같은 분자의 가분수로 만드는 것이 핵심입니다.",
            points=10,
        ),
        mc(
            id="e4-2-1-2-lv06-co-001",
            concept_id="concept-e4-frac-op-02",
            category="computation",
            part="calc",
            difficulty=6,
            content="2 1/4 + 1 2/4를 계산하세요.",
            options=[
                "3 3/4",
                "3 3/8",
                "4 1/4",
                "3 1/4",
            ],
            correct="A",
            explanation="2 1/4 + 1 2/4 = (2+1) + (1/4+2/4) = 3 + 3/4 = 3 3/4입니다. 자연수 부분과 분수 부분을 따로 더합니다.",
            points=10,
        ),
        mc(
            id="e4-2-1-2-lv07-co-001",
            concept_id="concept-e4-frac-op-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="3 1/6 - 1 4/6을 계산하세요.",
            options=[
                "1 3/6",
                "2 3/6",
                "1 5/6",
                "2 5/6",
            ],
            correct="A",
            explanation="3 1/6 - 1 4/6을 계산하려면 받아내림이 필요합니다. 3 1/6 = 2 7/6으로 바꾸면 2 7/6 - 1 4/6 = 1 3/6입니다. 1 3/6 = 1 1/2로 약분할 수 있습니다.",
            points=10,
        ),
        mc(
            id="e4-2-1-2-lv08-co-002",
            concept_id="concept-e4-frac-op-02",
            category="computation",
            part="calc",
            difficulty=8,
            content="4 - 1 3/7을 계산하세요.",
            options=[
                "2 4/7",
                "3 4/7",
                "2 3/7",
                "3 3/7",
            ],
            correct="A",
            explanation="4를 3 7/7로 바꿉니다. 3 7/7 - 1 3/7 = (3-1) + (7/7-3/7) = 2 + 4/7 = 2 4/7입니다.",
            points=10,
        ),
        mc(
            id="e4-2-1-2-lv07-co-002",
            concept_id="concept-e4-frac-op-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="1 2/9 + 2 8/9를 계산하세요.",
            options=[
                "3 10/9",
                "4 1/9",
                "3 1/9",
                "4",
            ],
            correct="B",
            explanation="1 2/9 + 2 8/9 = (1+2) + (2/9+8/9) = 3 + 10/9 = 3 + 1 1/9 = 4 1/9입니다. 분수 부분이 가분수가 되면 자연수로 받아올림합니다.",
            points=10,
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 3단원: 소수의 덧셈과 뺄셈
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━

        # concept-e4-dec-op-01: 소수 구조와 크기 비교 (5개)
        mc(
            id="e4-2-3-1-lv03-co-001",
            concept_id="concept-e4-dec-op-01",
            category="computation",
            part="calc",
            difficulty=3,
            content="0.7과 0.4 중 더 큰 수는?",
            options=[
                "0.7",
                "0.4",
                "같다",
                "비교할 수 없다",
            ],
            correct="A",
            explanation="소수 첫째 자리끼리 비교하면 7 > 4이므로 0.7이 더 큽니다.",
            points=10,
        ),
        mc(
            id="e4-2-3-1-lv05-co-001",
            concept_id="concept-e4-dec-op-01",
            category="computation",
            part="calc",
            difficulty=5,
            content="0.125와 0.5 중 더 큰 수는?",
            options=[
                "0.125 (자릿수가 더 많으므로)",
                "0.5",
                "같다",
                "비교할 수 없다",
            ],
            correct="B",
            explanation="소수의 크기를 비교할 때는 소수점 아래 같은 자리부터 비교합니다. 0.125=0.125, 0.5=0.500이므로 0.5가 더 큽니다. '소수가 길면 크다'는 착각은 흔한 오류입니다.",
            points=10,
        ),
        mc(
            id="e4-2-3-1-lv04-co-001",
            concept_id="concept-e4-dec-op-01",
            category="computation",
            part="calc",
            difficulty=4,
            content="다음 중 가장 작은 수는?",
            options=[
                "0.8",
                "0.08",
                "0.008",
                "0.80",
            ],
            correct="C",
            explanation="소수점 아래 자릿수를 맞추면 0.800, 0.080, 0.008, 0.800입니다. 0.008이 가장 작습니다.",
            points=10,
        ),
        mc(
            id="e4-2-3-1-lv06-co-001",
            concept_id="concept-e4-dec-op-01",
            category="computation",
            part="calc",
            difficulty=6,
            content="0.25와 0.3 중 더 큰 수는?",
            options=[
                "0.25 (자릿수가 더 많으므로)",
                "0.3",
                "같다",
                "비교할 수 없다",
            ],
            correct="B",
            explanation="0.25=0.25, 0.3=0.30이므로 첫째 자리에서 3 > 2이므로 0.3이 더 큽니다.",
            points=10,
        ),
        mc(
            id="e4-2-3-1-lv07-co-001",
            concept_id="concept-e4-dec-op-01",
            category="computation",
            part="calc",
            difficulty=7,
            content="다음 중 0.6과 0.7 사이에 있는 수는?",
            options=[
                "0.58",
                "0.65",
                "0.75",
                "0.8",
            ],
            correct="B",
            explanation="0.6 < 0.65 < 0.7이므로 0.65가 0.6과 0.7 사이에 있습니다.",
            points=10,
        ),

        # concept-e4-dec-op-02: 소수 덧뺄셈 계산 (5개)
        mc(
            id="e4-2-3-2-lv02-co-001",
            concept_id="concept-e4-dec-op-02",
            category="computation",
            part="calc",
            difficulty=2,
            content="0.3 + 0.5를 계산하세요.",
            options=[
                "0.2",
                "0.8",
                "0.35",
                "8",
            ],
            correct="B",
            explanation="0.3 + 0.5 = 0.8입니다. 소수 첫째 자리끼리 더하면 3+5=8이므로 0.8입니다.",
            points=10,
        ),
        mc(
            id="e4-2-3-2-lv07-co-001",
            concept_id="concept-e4-dec-op-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="2.5 + 1.38을 계산하세요.",
            options=[
                "3.43",
                "3.88",
                "1.63",
                "3.83",
            ],
            correct="B",
            explanation="소수점을 맞추어 세로로 정렬합니다. 2.50 + 1.38 = 3.88입니다. 2.5를 2.50으로 바꾸어 자릿수를 맞추는 것이 핵심입니다.",
            points=10,
        ),
        mc(
            id="e4-2-3-2-lv04-co-001",
            concept_id="concept-e4-dec-op-02",
            category="computation",
            part="calc",
            difficulty=4,
            content="1.4 + 2.3을 계산하세요.",
            options=[
                "3.7",
                "3.1",
                "4.3",
                "2.9",
            ],
            correct="A",
            explanation="1.4 + 2.3 = 3.7입니다. 소수 첫째 자리끼리 더하면 4+3=7이므로 0.7, 자연수 부분은 1+2=3이므로 3.7입니다.",
            points=10,
        ),
        mc(
            id="e4-2-3-2-lv05-co-001",
            concept_id="concept-e4-dec-op-02",
            category="computation",
            part="calc",
            difficulty=5,
            content="5.6 - 2.4를 계산하세요.",
            options=[
                "3.2",
                "3.0",
                "2.2",
                "8.0",
            ],
            correct="A",
            explanation="5.6 - 2.4 = 3.2입니다. 소수 첫째 자리는 6-4=2, 자연수 부분은 5-2=3이므로 3.2입니다.",
            points=10,
        ),
        mc(
            id="e4-2-3-2-lv06-co-001",
            concept_id="concept-e4-dec-op-02",
            category="computation",
            part="calc",
            difficulty=6,
            content="4.12 - 1.8을 계산하세요.",
            options=[
                "2.32",
                "3.32",
                "2.94",
                "3.94",
            ],
            correct="A",
            explanation="소수점을 맞추어 세로로 정렬합니다. 4.12 - 1.80 = 2.32입니다. 1.8을 1.80으로 바꾸어 자릿수를 맞추는 것이 핵심입니다.",
            points=10,
        ),
        mc(
            id="e4-2-3-2-lv08-co-001",
            concept_id="concept-e4-dec-op-02",
            category="computation",
            part="calc",
            difficulty=8,
            content="7.03 + 2.574를 계산하세요.",
            options=[
                "9.604",
                "9.574",
                "9.314",
                "10.604",
            ],
            correct="A",
            explanation="소수점을 맞추어 세로로 정렬합니다. 7.030 + 2.574 = 9.604입니다. 빈 자리를 0으로 채워 자릿수를 맞춥니다.",
            points=10,
        ),
    ]
