"""초등 4학년 빈칸 채우기 문제 시드 데이터."""
from app.seeds._base import fb


def get_questions():
    """빈칸 채우기 문제 반환."""
    return [
        # 난이도 1-3: 기초
        fb(
            id="e4-fb-001",
            concept_id="concept-e4-comp",
            category="computation",
            part="arithmetic",
            difficulty=2,
            content="156 × 4 = ____",
            answer="624",
            explanation="156 × 4 = 624입니다. 6×4=24(2 올림), 5×4+2=22(2 올림), 1×4+2=6이므로 624입니다.",
            points=10,
            accept_formats=["624"],
        ),
        fb(
            id="e4-fb-002",
            concept_id="concept-e4-comp",
            category="computation",
            part="arithmetic",
            difficulty=3,
            content="144 ÷ 12 = ____",
            answer="12",
            explanation="144 ÷ 12 = 12입니다.",
            points=10,
            accept_formats=["12"],
        ),
        fb(
            id="e4-fb-003",
            concept_id="concept-e4-comp",
            category="computation",
            part="arithmetic",
            difficulty=3,
            content="3/8 + 2/8 = ____",
            answer="5/8",
            explanation="분모가 같은 분수의 덧셈은 분자끼리 더합니다. 3/8 + 2/8 = 5/8입니다.",
            points=10,
            accept_formats=["5/8"],
        ),

        # 난이도 4-6: 중급
        fb(
            id="e4-fb-004",
            concept_id="concept-e4-conc",
            category="concept",
            part="geometry",
            difficulty=4,
            content="직각보다 크고 180도보다 작은 각을 ____이라고 합니다.",
            answer="둔각",
            explanation="직각(90도)보다 크고 180도보다 작은 각을 둔각이라고 합니다.",
            points=10,
            accept_formats=["둔각"],
        ),
        fb(
            id="e4-fb-005",
            concept_id="concept-e4-comp",
            category="computation",
            part="arithmetic",
            difficulty=5,
            content="217 × 23 = ____",
            answer="4991",
            explanation="217 × 23 = 4991입니다. 217×3=651, 217×20=4340, 651+4340=4991입니다.",
            points=10,
            accept_formats=["4991"],
        ),
        fb(
            id="e4-fb-006",
            concept_id="concept-e4-comp",
            category="computation",
            part="arithmetic",
            difficulty=6,
            content="468 ÷ 18 = ____",
            answer="26",
            explanation="468 ÷ 18 = 26입니다.",
            points=10,
            accept_formats=["26"],
        ),

        # 난이도 7-10: 고급
        fb(
            id="e4-fb-007",
            concept_id="concept-e4-conc",
            category="concept",
            part="geometry",
            difficulty=7,
            content="삼각형의 세 각의 크기의 합은 ____도입니다.",
            answer="180",
            explanation="삼각형의 세 각의 크기의 합은 항상 180도입니다.",
            points=10,
            accept_formats=["180"],
        ),
        fb(
            id="e4-fb-008",
            concept_id="concept-e4-comp",
            category="computation",
            part="arithmetic",
            difficulty=8,
            content="6/11 - 4/11 = ____",
            answer="2/11",
            explanation="분모가 같은 분수의 뺄셈은 분자끼리 뺍니다. 6/11 - 4/11 = 2/11입니다.",
            points=10,
            accept_formats=["2/11"],
        ),
        fb(
            id="e4-fb-009",
            concept_id="concept-e4-comp",
            category="computation",
            part="arithmetic",
            difficulty=9,
            content="456 × 38 = ____",
            answer="17328",
            explanation="456 × 38 = 17328입니다. 456×8=3648, 456×30=13680, 3648+13680=17328입니다.",
            points=10,
            accept_formats=["17328"],
        ),
        fb(
            id="e4-fb-010",
            concept_id="concept-e4-conc",
            category="concept",
            part="geometry",
            difficulty=10,
            content="사각형의 네 각의 크기의 합은 ____도입니다.",
            answer="360",
            explanation="사각형의 네 각의 크기의 합은 항상 360도입니다.",
            points=10,
            accept_formats=["360"],
        ),
        fb(
            id="e4-fb-011",
            concept_id="concept-e4-comp",
            category="computation",
            part="arithmetic",
            difficulty=10,
            content="1872 ÷ 24 = ____",
            answer="78",
            explanation="1872 ÷ 24 = 78입니다.",
            points=10,
            accept_formats=["78"],
        ),
    ]
