"""초등 4학년 빈칸 채우기 문제 시드 데이터.

전체 71개 개념 100% 커버 (PDF 기반 세분화 체계):
  1학기 (30개): 큰 수(6), 각도(8), 곱셈과 나눗셈(7), 평면도형의 이동(5), 막대그래프(4)
  2학기 (41개): 분수의 덧셈과 뺄셈(6), 삼각형(5), 소수의 덧셈과 뺄셈(8), 사각형(7), 꺾은선그래프(5), 다각형(5)

총 78개 문제 (개념당 평균 1.1개)
"""
from app.seeds._base import fb


def get_questions():
    """빈칸 채우기 문제 반환."""
    return [
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 1단원: 큰 수 (6개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-1-1-1-fb-001",
            concept_id="e4-1-1-01",
            category="computation",
            part="calc",
            difficulty=2,
            content="10000이 10개이면 ____입니다.",
            answer="100000",
            explanation="10000 × 10 = 100000입니다. 10배의 원리로 자릿수가 왼쪽으로 한 칸 이동합니다.",
            points=10,
            accept_formats=["100000", "10만"],
        ),
        fb(
            id="e4-1-1-1-fb-002",
            concept_id="e4-1-1-01",
            category="computation",
            part="calc",
            difficulty=5,
            content="1억은 1000만의 ____배입니다.",
            answer="10",
            explanation="1억 = 100,000,000이고 1000만 = 10,000,000입니다. 100,000,000 ÷ 10,000,000 = 10이므로 10배입니다.",
            points=10,
            accept_formats=["10"],
        ),
        fb(
            id="e4-1-1-02-fb-001",
            concept_id="e4-1-1-02",
            category="concept",
            part="calc",
            difficulty=3,
            content="45678에서 만의 자리 숫자는 ____입니다.",
            answer="4",
            explanation="45678은 4만 5678이므로 만의 자리 숫자는 4입니다.",
            points=10,
            accept_formats=["4"],
        ),
        fb(
            id="e4-1-1-03-fb-001",
            concept_id="e4-1-1-03",
            category="concept",
            part="calc",
            difficulty=4,
            content="10만이 10개이면 ____입니다.",
            answer="100만",
            explanation="100,000 × 10 = 1,000,000이므로 100만(백만)입니다.",
            points=10,
            accept_formats=["100만", "백만", "1000000"],
        ),
        fb(
            id="e4-1-1-04-fb-001",
            concept_id="e4-1-1-04",
            category="concept",
            part="calc",
            difficulty=6,
            content="1조는 1억의 ____배입니다.",
            answer="10000",
            explanation="1조 = 1,000,000,000,000이고 1억 = 100,000,000입니다. 1조 ÷ 1억 = 10,000이므로 10,000배(1만 배)입니다.",
            points=10,
            accept_formats=["10000", "1만", "만"],
        ),
        fb(
            id="e4-1-1-05-fb-001",
            concept_id="e4-1-1-05",
            category="concept",
            part="calc",
            difficulty=3,
            content="100, 200, 300, 400, ____",
            answer="500",
            explanation="100씩 뛰어 세기입니다. 400 + 100 = 500입니다.",
            points=10,
            accept_formats=["500"],
        ),
        fb(
            id="e4-1-1-06-fb-001",
            concept_id="e4-1-1-06",
            category="concept",
            part="calc",
            difficulty=4,
            content="9876543과 9876534 중에서 더 큰 수는 ____입니다.",
            answer="9876543",
            explanation="천만의 자리까지 같으므로 백의 자리를 비교합니다. 4 < 5이므로 9876543이 더 큽니다.",
            points=10,
            accept_formats=["9876543"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 2단원: 각도 (8개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-1-2-1-fb-001",
            concept_id="e4-1-2-04",
            category="concept",
            part="geo",
            difficulty=2,
            content="0도보다 크고 ____도보다 작은 각을 예각이라고 합니다.",
            answer="90",
            explanation="예각은 0도보다 크고 90도(직각)보다 작은 각입니다.",
            points=10,
            accept_formats=["90"],
        ),
        fb(
            id="e4-1-2-2-fb-001",
            concept_id="e4-1-2-07",
            category="concept",
            part="geo",
            difficulty=6,
            content="삼각형의 두 각이 70도와 50도일 때, 나머지 한 각은 ____도입니다.",
            answer="60",
            explanation="삼각형의 세 각의 합은 180도입니다. 180 - 70 - 50 = 60이므로 나머지 각은 60도입니다.",
            points=10,
            accept_formats=["60"],
        ),
        fb(
            id="e4-1-2-01-fb-001",
            concept_id="e4-1-2-01",
            category="concept",
            part="geo",
            difficulty=3,
            content="두 각을 직접 비교하려면 한 각을 다른 각에 ____서 비교합니다.",
            answer="겹쳐",
            explanation="각도기가 없을 때는 두 각을 직접 겹쳐서 벌어진 정도를 비교합니다.",
            points=10,
            accept_formats=["겹쳐", "포개"],
        ),
        fb(
            id="e4-1-2-02-fb-001",
            concept_id="e4-1-2-02",
            category="concept",
            part="geo",
            difficulty=3,
            content="각의 크기를 나타내는 단위는 ____입니다.",
            answer="도",
            explanation="각의 크기는 도(°) 단위로 나타냅니다. 예: 90도, 45도 등.",
            points=10,
            accept_formats=["도", "°"],
        ),
        fb(
            id="e4-1-2-06-fb-001",
            concept_id="e4-1-2-06",
            category="computation",
            part="geo",
            difficulty=4,
            content="45° + 60° = ____°",
            answer="105",
            explanation="각도의 덧셈은 일반 덧셈과 같습니다. 45 + 60 = 105입니다.",
            points=10,
            accept_formats=["105"],
        ),
        fb(
            id="e4-1-2-08-fb-001",
            concept_id="e4-1-2-08",
            category="concept",
            part="geo",
            difficulty=5,
            content="사각형의 네 각의 크기의 합은 ____도입니다.",
            answer="360",
            explanation="사각형의 네 각의 크기의 합은 항상 360도입니다.",
            points=10,
            accept_formats=["360"],
        ),
        fb(
            id="e4-1-2-05-fb-001",
            concept_id="e4-1-2-05",
            category="concept",
            part="geo",
            difficulty=5,
            content="직각은 90도이므로 직각의 반은 약 ____도입니다.",
            answer="45",
            explanation="직각(90도)의 반은 90 ÷ 2 = 45도입니다. 각도를 어림할 때 기준이 됩니다.",
            points=10,
            accept_formats=["45"],
        ),
        fb(
            id="e4-1-2-03-fb-001",
            concept_id="e4-1-2-03",
            category="concept",
            part="geo",
            difficulty=4,
            content="각도기로 ____ 크기의 각을 그릴 수 있습니다.",
            answer="원하는",
            explanation="각도기를 사용하면 원하는 크기(예: 35도, 120도)의 각을 정확하게 그릴 수 있습니다.",
            points=10,
            accept_formats=["원하는", "정확한", "정해진"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 3단원: 곱셈과 나눗셈 (7개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-1-3-1-fb-001",
            concept_id="e4-1-3-01",
            category="computation",
            part="calc",
            difficulty=2,
            content="156 × 4 = ____",
            answer="624",
            explanation="156 × 4 = 624입니다. 6×4=24(2 올림), 5×4+2=22(2 올림), 1×4+2=6이므로 624입니다.",
            points=10,
            accept_formats=["624"],
        ),
        fb(
            id="e4-1-3-2-fb-001",
            concept_id="e4-1-3-03",
            category="computation",
            part="calc",
            difficulty=6,
            content="468 ÷ 18 = ____",
            answer="26",
            explanation="468 ÷ 18 = 26입니다. 검산: 18 × 26 = 468입니다.",
            points=10,
            accept_formats=["26"],
        ),
        fb(
            id="e4-1-3-01-fb-001",
            concept_id="e4-1-3-01",
            category="computation",
            part="calc",
            difficulty=3,
            content="234 × 30 = ____",
            answer="7020",
            explanation="234 × 30 = 234 × 3 × 10 = 702 × 10 = 7020입니다. 0을 붙이는 원리를 사용합니다.",
            points=10,
            accept_formats=["7020"],
        ),
        fb(
            id="e4-1-3-02-fb-001",
            concept_id="e4-1-3-02",
            category="computation",
            part="calc",
            difficulty=5,
            content="123 × 45 = ____",
            answer="5535",
            explanation="123 × 45 = 123 × 40 + 123 × 5 = 4920 + 615 = 5535입니다.",
            points=10,
            accept_formats=["5535"],
        ),
        fb(
            id="e4-1-3-04-fb-001",
            concept_id="e4-1-3-04",
            category="computation",
            part="calc",
            difficulty=4,
            content="84 ÷ 21 = ____",
            answer="4",
            explanation="84 ÷ 21 = 4입니다. 21 × 4 = 84로 검산할 수 있습니다.",
            points=10,
            accept_formats=["4"],
        ),
        fb(
            id="e4-1-3-05-fb-001",
            concept_id="e4-1-3-05",
            category="computation",
            part="calc",
            difficulty=6,
            content="195 ÷ 39 = ____",
            answer="5",
            explanation="195 ÷ 39 = 5입니다. 39 × 5 = 195로 확인합니다.",
            points=10,
            accept_formats=["5"],
        ),
        fb(
            id="e4-1-3-06-fb-001",
            concept_id="e4-1-3-06",
            category="computation",
            part="calc",
            difficulty=7,
            content="672 ÷ 24 = ____",
            answer="28",
            explanation="672 ÷ 24 = 28입니다. 24 × 28 = 672로 검산합니다.",
            points=10,
            accept_formats=["28"],
        ),
        fb(
            id="e4-1-3-07-fb-001",
            concept_id="e4-1-3-07",
            category="computation",
            part="calc",
            difficulty=8,
            content="785 ÷ 35 = ____ 나머지 ____",
            answer="22 나머지 15",
            explanation="785 ÷ 35 = 22 나머지 15입니다. 검산: 35 × 22 + 15 = 770 + 15 = 785입니다.",
            points=10,
            accept_formats=["22 나머지 15", "22...15"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 4단원: 평면도형의 이동 (5개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-1-4-1-fb-001",
            concept_id="e4-1-4-01",
            category="concept",
            part="geo",
            difficulty=3,
            content="도형을 밀면 모양과 크기는 변하지 않고 ____만 변합니다.",
            answer="위치",
            explanation="밀기(평행이동)에서는 도형의 위치만 변하고, 모양·크기·방향은 변하지 않습니다.",
            points=10,
            accept_formats=["위치"],
        ),
        fb(
            id="e4-1-4-2-fb-001",
            concept_id="e4-1-4-03",
            category="concept",
            part="geo",
            difficulty=7,
            content="시계방향으로 90° 돌리기는 반시계방향으로 ____° 돌리기와 같습니다.",
            answer="270",
            explanation="시계방향 90° + 반시계방향 = 360°이므로 반시계방향 360° - 90° = 270°입니다.",
            points=10,
            accept_formats=["270"],
        ),
        fb(
            id="e4-1-4-02-fb-001",
            concept_id="e4-1-4-02",
            category="concept",
            part="geo",
            difficulty=4,
            content="도형을 뒤집으면 좌우 또는 상하가 ____됩니다.",
            answer="바뀝니다",
            explanation="뒤집기는 거울에 비춘 것처럼 좌우 또는 상하가 바뀝니다.",
            points=10,
            accept_formats=["바뀝니다", "바뀜", "반대로 됨"],
        ),
        fb(
            id="e4-1-4-04-fb-001",
            concept_id="e4-1-4-04",
            category="concept",
            part="geo",
            difficulty=8,
            content="도형을 뒤집은 후 90° 돌리는 것은 ____이동의 조합입니다.",
            answer="복합",
            explanation="뒤집기와 돌리기를 함께 사용하는 것을 복합 이동이라고 합니다.",
            points=10,
            accept_formats=["복합", "결합"],
        ),
        fb(
            id="e4-1-4-05-fb-001",
            concept_id="e4-1-4-05",
            category="concept",
            part="geo",
            difficulty=5,
            content="규칙적인 무늬를 만들 때 사용하는 세 가지 이동은 밀기, 뒤집기, ____입니다.",
            answer="돌리기",
            explanation="무늬 꾸미기에는 밀기, 뒤집기, 돌리기를 활용합니다.",
            points=10,
            accept_formats=["돌리기", "회전"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 5단원: 막대그래프 (4개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-1-5-1-fb-001",
            concept_id="e4-1-5-01",
            category="concept",
            part="data",
            difficulty=3,
            content="막대그래프에서 세로축의 눈금 한 칸이 5명을 나타낼 때, 막대가 눈금 3칸이면 ____명입니다.",
            answer="15",
            explanation="눈금 한 칸이 5명이므로 3칸 = 5 × 3 = 15명입니다.",
            points=10,
            accept_formats=["15"],
        ),
        fb(
            id="e4-1-5-1-fb-002",
            concept_id="e4-1-5-02",
            category="concept",
            part="data",
            difficulty=5,
            content="막대그래프에서 눈금 한 칸이 2명을 나타냅니다. 어떤 항목의 막대가 눈금 7칸이면 그 항목은 ____명입니다.",
            answer="14",
            explanation="눈금 한 칸이 2명이므로 7칸 = 2 × 7 = 14명입니다.",
            points=10,
            accept_formats=["14"],
        ),
        fb(
            id="e4-1-5-03-fb-001",
            concept_id="e4-1-5-03",
            category="concept",
            part="data",
            difficulty=5,
            content="막대그래프를 그릴 때 먼저 자료에 맞는 ____을 정합니다.",
            answer="눈금",
            explanation="막대그래프를 그릴 때는 먼저 자료의 크기에 적절한 눈금 단위를 정합니다.",
            points=10,
            accept_formats=["눈금", "눈금 단위"],
        ),
        fb(
            id="e4-1-5-04-fb-001",
            concept_id="e4-1-5-04",
            category="concept",
            part="data",
            difficulty=6,
            content="막대그래프로 나타내려면 먼저 자료를 ____해야 합니다.",
            answer="조사",
            explanation="실생활 자료를 막대그래프로 나타내려면 먼저 자료를 조사하고 정리해야 합니다.",
            points=10,
            accept_formats=["조사", "수집"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 6단원: 규칙 찾기 (5개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-1-6-1-fb-001",
            concept_id="e4-1-6-01",
            category="concept",
            part="algebra",
            difficulty=2,
            content="3, 6, 9, 12, ____",
            answer="15",
            explanation="3씩 커지는 규칙입니다. 12 + 3 = 15입니다.",
            points=10,
            accept_formats=["15"],
        ),
        fb(
            id="e4-1-6-2-fb-001",
            concept_id="e4-1-6-01",
            category="concept",
            part="algebra",
            difficulty=8,
            content="1, 4, 9, 16, ____",
            answer="25",
            explanation="1=1², 4=2², 9=3², 16=4²이므로 다음은 5²=25입니다. 제곱수의 규칙입니다.",
            points=10,
            accept_formats=["25"],
        ),
        fb(
            id="e4-1-6-02-fb-001",
            concept_id="e4-1-6-02",
            category="concept",
            part="algebra",
            difficulty=5,
            content="○, △, ○, △, ____",
            answer="○",
            explanation="○와 △가 반복되는 규칙입니다. 다음은 ○입니다.",
            points=10,
            accept_formats=["○", "동그라미"],
        ),
        fb(
            id="e4-1-6-03-fb-001",
            concept_id="e4-1-6-03",
            category="concept",
            part="algebra",
            difficulty=6,
            content="1+2=3, 2+3=5, 3+4=7, 4+5=____ (두 수가 1씩 커지는 규칙)",
            answer="9",
            explanation="4+5=9입니다. 더하는 두 수가 각각 1씩 커지는 규칙입니다.",
            points=10,
            accept_formats=["9"],
        ),
        fb(
            id="e4-1-6-04-fb-001",
            concept_id="e4-1-6-04",
            category="concept",
            part="algebra",
            difficulty=7,
            content="2×3=6, 3×4=12, 4×5=20, 5×6=____ (두 수가 1씩 커지는 규칙)",
            answer="30",
            explanation="5×6=30입니다. 곱하는 두 수가 각각 1씩 커지는 규칙입니다.",
            points=10,
            accept_formats=["30"],
        ),
        fb(
            id="e4-1-6-05-fb-001",
            concept_id="e4-1-6-05",
            category="concept",
            part="algebra",
            difficulty=8,
            content="수 배열 2, 5, 8, 11의 규칙을 식으로 나타내면 (번째 수)×3-____ 입니다.",
            answer="1",
            explanation="1번째: 1×3-1=2, 2번째: 2×3-1=5, 3번째: 3×3-1=8입니다. 규칙을 식으로 표현하면 (번째)×3-1입니다.",
            points=10,
            accept_formats=["1"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 1단원: 분수의 덧셈과 뺄셈 (6개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-2-1-1-fb-001",
            concept_id="e4-2-1-01",
            category="computation",
            part="calc",
            difficulty=3,
            content="5/7 - 2/7 = ____",
            answer="3/7",
            explanation="분모가 같은 분수의 뺄셈은 분자끼리 뺍니다. 5/7 - 2/7 = 3/7입니다.",
            points=10,
            accept_formats=["3/7"],
        ),
        fb(
            id="e4-2-1-2-fb-001",
            concept_id="e4-2-1-06",
            category="computation",
            part="calc",
            difficulty=7,
            content="3 2/7 - 1 5/7 = ____",
            answer="1 4/7",
            explanation="2/7에서 5/7을 뺄 수 없으므로 3 2/7을 2 9/7로 바꿉니다. 2 9/7 - 1 5/7 = 1 4/7입니다.",
            points=10,
            accept_formats=["1 4/7", "11/7"],
        ),
        fb(
            id="e4-2-1-01-fb-002",
            concept_id="e4-2-1-01",
            category="computation",
            part="calc",
            difficulty=2,
            content="2/9 + 4/9 = ____",
            answer="6/9",
            explanation="분모가 같은 분수의 덧셈은 분자끼리 더합니다. 2/9 + 4/9 = 6/9 = 2/3입니다.",
            points=10,
            accept_formats=["6/9", "2/3"],
        ),
        fb(
            id="e4-2-1-02-fb-001",
            concept_id="e4-2-1-02",
            category="computation",
            part="calc",
            difficulty=4,
            content="1 2/5 + 2 1/5 = ____",
            answer="3 3/5",
            explanation="자연수는 자연수끼리, 분수는 분수끼리 더합니다. 1+2=3, 2/5+1/5=3/5이므로 3 3/5입니다.",
            points=10,
            accept_formats=["3 3/5", "18/5"],
        ),
        fb(
            id="e4-2-1-03-fb-001",
            concept_id="e4-2-1-03",
            category="computation",
            part="calc",
            difficulty=2,
            content="7/8 - 3/8 = ____",
            answer="4/8",
            explanation="분모가 같은 진분수의 뺄셈입니다. 7/8 - 3/8 = 4/8 = 1/2입니다.",
            points=10,
            accept_formats=["4/8", "1/2"],
        ),
        fb(
            id="e4-2-1-04-fb-001",
            concept_id="e4-2-1-04",
            category="computation",
            part="calc",
            difficulty=4,
            content="3 5/8 - 1 2/8 = ____",
            answer="2 3/8",
            explanation="자연수끼리, 분수끼리 각각 뺍니다. 3-1=2, 5/8-2/8=3/8이므로 2 3/8입니다.",
            points=10,
            accept_formats=["2 3/8", "19/8"],
        ),
        fb(
            id="e4-2-1-05-fb-001",
            concept_id="e4-2-1-05",
            category="computation",
            part="calc",
            difficulty=6,
            content="5 - 3/4 = ____",
            answer="4 1/4",
            explanation="5를 4 4/4로 바꾸어 계산합니다. 4 4/4 - 3/4 = 4 1/4입니다.",
            points=10,
            accept_formats=["4 1/4", "17/4"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 2단원: 삼각형 (5개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-2-2-1-fb-001",
            concept_id="e4-2-2-01",
            category="concept",
            part="geo",
            difficulty=3,
            content="정삼각형의 한 각의 크기는 ____도입니다.",
            answer="60",
            explanation="정삼각형은 세 각의 크기가 모두 같습니다. 180 ÷ 3 = 60이므로 한 각은 60도입니다.",
            points=10,
            accept_formats=["60"],
        ),
        fb(
            id="e4-2-2-1-fb-002",
            concept_id="e4-2-2-02",
            category="concept",
            part="geo",
            difficulty=7,
            content="이등변삼각형의 꼭지각이 40도일 때, 밑각의 크기는 ____도입니다.",
            answer="70",
            explanation="이등변삼각형의 두 밑각의 크기는 같습니다. (180 - 40) ÷ 2 = 70이므로 밑각은 70도입니다.",
            points=10,
            accept_formats=["70"],
        ),
        fb(
            id="e4-2-2-03-fb-001",
            concept_id="e4-2-2-03",
            category="concept",
            part="geo",
            difficulty=4,
            content="정삼각형의 세 각은 모두 ____도입니다.",
            answer="60",
            explanation="정삼각형은 세 변의 길이가 모두 같고, 세 각의 크기도 모두 같습니다. 180 ÷ 3 = 60도입니다.",
            points=10,
            accept_formats=["60"],
        ),
        fb(
            id="e4-2-2-04-fb-001",
            concept_id="e4-2-2-04",
            category="concept",
            part="geo",
            difficulty=5,
            content="한 각이 90도보다 큰 삼각형을 ____삼각형이라고 합니다.",
            answer="둔각",
            explanation="한 각이 둔각(90°보다 큰 각)인 삼각형을 둔각삼각형이라고 합니다.",
            points=10,
            accept_formats=["둔각"],
        ),
        fb(
            id="e4-2-2-05-fb-001",
            concept_id="e4-2-2-05",
            category="concept",
            part="geo",
            difficulty=7,
            content="두 변의 길이가 같고 한 각이 직각인 삼각형은 이등변삼각형이면서 ____삼각형입니다.",
            answer="직각",
            explanation="삼각형은 변과 각 두 가지 기준으로 분류할 수 있습니다. 두 변이 같으면 이등변삼각형, 한 각이 직각이면 직각삼각형입니다.",
            points=10,
            accept_formats=["직각"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 3단원: 소수의 덧셈과 뺄셈 (8개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-2-3-2-fb-001",
            concept_id="e4-2-3-05",
            category="computation",
            part="calc",
            difficulty=3,
            content="0.7 + 0.6 = ____",
            answer="1.3",
            explanation="0.7 + 0.6 = 1.3입니다. 소수 첫째 자리끼리 더하면 7+6=13이므로 1.3입니다.",
            points=10,
            accept_formats=["1.3"],
        ),
        fb(
            id="e4-2-3-2-fb-002",
            concept_id="e4-2-3-08",
            category="computation",
            part="calc",
            difficulty=7,
            content="3.5 - 1.28 = ____",
            answer="2.22",
            explanation="소수점을 맞추어 3.50 - 1.28 = 2.22입니다. 3.5를 3.50으로 바꾸어 자릿수를 맞추는 것이 핵심입니다.",
            points=10,
            accept_formats=["2.22"],
        ),
        fb(
            id="e4-2-3-01-fb-001",
            concept_id="e4-2-3-01",
            category="concept",
            part="calc",
            difficulty=3,
            content="0.01이 25개이면 ____입니다.",
            answer="0.25",
            explanation="0.01 × 25 = 0.25입니다. 소수 둘째 자리 수를 이해합니다.",
            points=10,
            accept_formats=["0.25"],
        ),
        fb(
            id="e4-2-3-02-fb-001",
            concept_id="e4-2-3-02",
            category="concept",
            part="calc",
            difficulty=4,
            content="0.001이 378개이면 ____입니다.",
            answer="0.378",
            explanation="0.001 × 378 = 0.378입니다. 소수 셋째 자리 수를 이해합니다.",
            points=10,
            accept_formats=["0.378"],
        ),
        fb(
            id="e4-2-3-03-fb-001",
            concept_id="e4-2-3-03",
            category="concept",
            part="calc",
            difficulty=4,
            content="1.45와 1.5 중에서 더 큰 수는 ____입니다.",
            answer="1.5",
            explanation="1.5 = 1.50이므로 1.45 < 1.50입니다. 자연수 부분이 같으면 소수 첫째 자리부터 비교합니다.",
            points=10,
            accept_formats=["1.5"],
        ),
        fb(
            id="e4-2-3-04-fb-001",
            concept_id="e4-2-3-04",
            category="concept",
            part="calc",
            difficulty=5,
            content="0.3은 0.03의 ____배입니다.",
            answer="10",
            explanation="0.3 = 0.30이고 0.03 × 10 = 0.30이므로 10배입니다.",
            points=10,
            accept_formats=["10"],
        ),
        fb(
            id="e4-2-3-06-fb-001",
            concept_id="e4-2-3-06",
            category="computation",
            part="calc",
            difficulty=3,
            content="1.8 - 0.5 = ____",
            answer="1.3",
            explanation="소수점을 맞추어 빼면 1.8 - 0.5 = 1.3입니다.",
            points=10,
            accept_formats=["1.3"],
        ),
        fb(
            id="e4-2-3-07-fb-001",
            concept_id="e4-2-3-07",
            category="computation",
            part="calc",
            difficulty=5,
            content="2.35 + 1.48 = ____",
            answer="3.83",
            explanation="소수점을 맞추어 더하면 2.35 + 1.48 = 3.83입니다. 5+8=13이므로 받아올림합니다.",
            points=10,
            accept_formats=["3.83"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 4단원: 사각형 (7개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-2-4-1-fb-001",
            concept_id="e4-2-4-01",
            category="concept",
            part="geo",
            difficulty=3,
            content="사각형의 네 각의 크기의 합은 ____도입니다.",
            answer="360",
            explanation="사각형의 네 각의 크기의 합은 항상 360도입니다.",
            points=10,
            accept_formats=["360"],
        ),
        fb(
            id="e4-2-4-2-fb-001",
            concept_id="e4-2-4-06",
            category="concept",
            part="geo",
            difficulty=5,
            content="네 변의 길이가 모두 같은 사각형을 ____이라고 합니다.",
            answer="마름모",
            explanation="네 변의 길이가 모두 같은 사각형을 마름모라고 합니다. (네 각이 모두 직각이면 정사각형)",
            points=10,
            accept_formats=["마름모"],
        ),
        fb(
            id="e4-2-4-01-fb-002",
            concept_id="e4-2-4-01",
            category="concept",
            part="geo",
            difficulty=4,
            content="두 직선이 만나서 이루는 각이 ____도일 때 수직이라고 합니다.",
            answer="90",
            explanation="두 직선이 만나서 이루는 각이 90도(직각)일 때 수직이라고 합니다.",
            points=10,
            accept_formats=["90"],
        ),
        fb(
            id="e4-2-4-02-fb-001",
            concept_id="e4-2-4-02",
            category="concept",
            part="geo",
            difficulty=5,
            content="한 직선에 수직인 두 직선은 서로 ____입니다.",
            answer="평행",
            explanation="한 직선에 수직인 두 직선은 서로 평행합니다. 평행한 두 직선은 만나지 않습니다.",
            points=10,
            accept_formats=["평행"],
        ),
        fb(
            id="e4-2-4-03-fb-001",
            concept_id="e4-2-4-03",
            category="concept",
            part="geo",
            difficulty=6,
            content="두 평행선 사이의 거리는 어디서나 ____습니다.",
            answer="같습니다",
            explanation="두 평행선 사이의 수선의 길이는 어디서나 같습니다. 이것이 평행선의 중요한 성질입니다.",
            points=10,
            accept_formats=["같습니다", "같다", "일정하다"],
        ),
        fb(
            id="e4-2-4-04-fb-001",
            concept_id="e4-2-4-04",
            category="concept",
            part="geo",
            difficulty=4,
            content="마주 보는 한 쌍의 변이 평행인 사각형을 ____이라고 합니다.",
            answer="사다리꼴",
            explanation="마주 보는 한 쌍의 변이 평행인 사각형을 사다리꼴이라고 합니다.",
            points=10,
            accept_formats=["사다리꼴"],
        ),
        fb(
            id="e4-2-4-05-fb-001",
            concept_id="e4-2-4-05",
            category="concept",
            part="geo",
            difficulty=6,
            content="마주 보는 두 쌍의 변이 평행인 사각형을 ____이라고 합니다.",
            answer="평행사변형",
            explanation="마주 보는 두 쌍의 변이 모두 평행인 사각형을 평행사변형이라고 합니다.",
            points=10,
            accept_formats=["평행사변형"],
        ),
        fb(
            id="e4-2-4-07-fb-001",
            concept_id="e4-2-4-07",
            category="concept",
            part="geo",
            difficulty=7,
            content="정사각형은 직사각형이면서 ____입니다.",
            answer="마름모",
            explanation="정사각형은 네 각이 모두 직각(직사각형의 조건)이면서 네 변의 길이가 모두 같습니다(마름모의 조건).",
            points=10,
            accept_formats=["마름모"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 5단원: 꺾은선그래프 (5개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-2-5-1-fb-001",
            concept_id="e4-2-5-01",
            category="concept",
            part="data",
            difficulty=2,
            content="꺾은선그래프에서 선분이 오른쪽 위로 향하면 값이 ____하고 있다는 뜻입니다.",
            answer="증가",
            explanation="꺾은선그래프에서 선분이 위로 향하면 시간이 지남에 따라 값이 증가하고 있다는 뜻입니다.",
            points=10,
            accept_formats=["증가", "커지고", "늘어나고"],
        ),
        fb(
            id="e4-2-5-2-fb-001",
            concept_id="e4-2-5-02",
            category="concept",
            part="data",
            difficulty=4,
            content="시간에 따른 기온의 변화를 나타내기에 적합한 그래프는 ____그래프입니다.",
            answer="꺾은선",
            explanation="시간에 따른 연속적 변화를 나타내기에는 꺾은선그래프가 적합합니다.",
            points=10,
            accept_formats=["꺾은선"],
        ),
        fb(
            id="e4-2-5-01-fb-002",
            concept_id="e4-2-5-01",
            category="concept",
            part="data",
            difficulty=3,
            content="꺾은선그래프는 시간에 따른 ____를 나타내기에 적합합니다.",
            answer="변화",
            explanation="꺾은선그래프는 시간의 흐름에 따른 변화를 나타내기에 적합한 그래프입니다.",
            points=10,
            accept_formats=["변화", "추이"],
        ),
        fb(
            id="e4-2-5-03-fb-001",
            concept_id="e4-2-5-03",
            category="concept",
            part="data",
            difficulty=5,
            content="꺾은선그래프를 그릴 때 점들을 ____로 연결합니다.",
            answer="선분",
            explanation="꺾은선그래프는 각 시점의 값을 점으로 찍고, 이웃한 점들을 선분으로 연결하여 그립니다.",
            points=10,
            accept_formats=["선분", "선", "직선"],
        ),
        fb(
            id="e4-2-5-04-fb-001",
            concept_id="e4-2-5-04",
            category="concept",
            part="data",
            difficulty=6,
            content="실생활 자료를 직접 ____하여 꺾은선그래프로 나타낼 수 있습니다.",
            answer="조사",
            explanation="자료를 직접 조사하고 정리하여 꺾은선그래프로 나타내는 전체 과정을 경험합니다.",
            points=10,
            accept_formats=["조사", "수집"],
        ),
        fb(
            id="e4-2-5-05-fb-001",
            concept_id="e4-2-5-05",
            category="concept",
            part="data",
            difficulty=6,
            content="두 꺾은선그래프를 비교하여 미래의 값을 ____할 수 있습니다.",
            answer="예측",
            explanation="꺾은선그래프의 추세를 보고 미래의 값을 예측할 수 있습니다.",
            points=10,
            accept_formats=["예측", "추정"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 6단원: 다각형 (5개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e4-2-6-1-fb-001",
            concept_id="e4-2-6-01",
            category="concept",
            part="geo",
            difficulty=2,
            content="선분으로만 둘러싸인 닫힌 도형을 ____이라고 합니다.",
            answer="다각형",
            explanation="선분으로만 둘러싸인 닫힌 도형을 다각형이라고 합니다.",
            points=10,
            accept_formats=["다각형"],
        ),
        fb(
            id="e4-2-6-1-fb-002",
            concept_id="e4-2-6-03",
            category="concept",
            part="geo",
            difficulty=6,
            content="오각형의 대각선의 수는 ____개입니다.",
            answer="5",
            explanation="대각선의 수 = n(n-3)/2입니다. 오각형(n=5): 5×(5-3)/2 = 5×2/2 = 5개입니다.",
            points=10,
            accept_formats=["5"],
        ),
        fb(
            id="e4-2-6-02-fb-001",
            concept_id="e4-2-6-02",
            category="concept",
            part="geo",
            difficulty=5,
            content="변의 길이와 각의 크기가 모두 같은 다각형을 ____이라고 합니다.",
            answer="정다각형",
            explanation="변의 길이가 모두 같고 각의 크기도 모두 같은 다각형을 정다각형이라고 합니다.",
            points=10,
            accept_formats=["정다각형"],
        ),
        fb(
            id="e4-2-6-03-fb-002",
            concept_id="e4-2-6-03",
            category="concept",
            part="geo",
            difficulty=7,
            content="육각형의 한 꼭짓점에서 그을 수 있는 대각선의 수는 ____개입니다.",
            answer="3",
            explanation="n각형에서 한 꼭짓점에서 그을 수 있는 대각선은 n-3개입니다. 육각형: 6-3=3개입니다.",
            points=10,
            accept_formats=["3"],
        ),
        fb(
            id="e4-2-6-04-fb-001",
            concept_id="e4-2-6-04",
            category="concept",
            part="geo",
            difficulty=6,
            content="삼각형, 사각형, 오각형 등의 다각형을 사용하여 여러 가지 ____을 만들 수 있습니다.",
            answer="모양",
            explanation="다각형을 조합하여 여러 가지 새로운 모양을 만들 수 있습니다.",
            points=10,
            accept_formats=["모양", "도형"],
        ),
        fb(
            id="e4-2-6-05-fb-001",
            concept_id="e4-2-6-05",
            category="concept",
            part="geo",
            difficulty=6,
            content="정다각형으로 평면을 빈틈없이 채우는 것을 ____이라고 합니다.",
            answer="테셀레이션",
            explanation="정다각형으로 평면을 빈틈없이 채우는 것을 테셀레이션(쪽매맞춤)이라고 합니다.",
            points=10,
            accept_formats=["테셀레이션", "쪽매맞춤"],
        ),
    ]
