"""add_retry_and_focus_check_fields

Revision ID: 0c3f3f7c7d0c
Revises: 8577adedf933
Create Date: 2026-02-08 15:07:25.195661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3f3f7c7d0c'
down_revision: Union[str, None] = '8577adedf933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_check_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focus_check_items_question_id'), 'focus_check_items', ['question_id'], unique=False)
    op.create_index(op.f('ix_focus_check_items_student_id'), 'focus_check_items', ['student_id'], unique=False)
    op.add_column('test_attempts', sa.Column('retry_queue', sa.JSON(), nullable=True))
    op.add_column('test_attempts', sa.Column('retry_counts', sa.JSON(), nullable=True))
    op.add_column('test_attempts', sa.Column('current_question_index', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempts', 'current_question_index')
    op.drop_column('test_attempts', 'retry_counts')
    op.drop_column('test_attempts', 'retry_queue')
    op.drop_index(op.f('ix_focus_check_items_student_id'), table_name='focus_check_items')
    op.drop_index(op.f('ix_focus_check_items_question_id'), table_name='focus_check_items')
    op.drop_table('focus_check_items')
    # ### end Alembic commands ###
