"""add concept_method and fading_level

Revision ID: a01b1107ee09
Revises: f680d99f3780
Create Date: 2026-02-09 00:38:52.539849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01b1107ee09'
down_revision: Union[str, None] = 'f680d99f3780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum 타입 생성 (PostgreSQL 대응)
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'conceptmethod') THEN CREATE TYPE conceptmethod AS ENUM ('GRADUAL_FADING', 'ERROR_ANALYSIS', 'VISUAL_DECODING', 'STANDARD'); END IF; END $$;")

    op.add_column('questions', sa.Column('concept_method', sa.Enum('GRADUAL_FADING', 'ERROR_ANALYSIS', 'VISUAL_DECODING', 'STANDARD', name='conceptmethod'), nullable=True, comment='개념 문항 생성 방식 (Gradual Fading 등)'))
    op.add_column('questions', sa.Column('fading_level', sa.Integer(), nullable=True, comment='빈칸 레벨 (1~4)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'fading_level')
    op.drop_column('questions', 'concept_method')
    
    # Enum 타입 삭제
    op.execute("DROP TYPE IF EXISTS conceptmethod")
    # ### end Alembic commands ###
