"""add_achievement_model

Revision ID: d702ba05949b
Revises: 0c3f3f7c7d0c
Create Date: 2026-02-08 17:08:37.427585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd702ba05949b'
down_revision: Union[str, None] = '0c3f3f7c7d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('achievement_type', sa.String(length=50), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'achievement_type', name='uq_student_achievement')
    )
    op.create_index(op.f('ix_achievements_achievement_type'), 'achievements', ['achievement_type'], unique=False)
    op.create_index(op.f('ix_achievements_student_id'), 'achievements', ['student_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_student_id'), 'assignments', ['student_id'], unique=False)
    op.alter_column('test_attempts', 'current_question_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('users', sa.Column('teacher_memo', sa.String(length=2000), nullable=True, comment='강사 메모 (학생에 대한 특이사항 등)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'teacher_memo')
    op.alter_column('test_attempts', 'current_question_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_assignments_student_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_achievements_student_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_achievement_type'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
