"""add hint column to questions

Revision ID: f680d99f3780
Revises: 330e2f2894a9
Create Date: 2026-02-09 00:24:43.860658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f680d99f3780'
down_revision: Union[str, None] = '330e2f2894a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('hint', sa.Text(), nullable=True, comment='문제 힌트'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'hint')
    # ### end Alembic commands ###
