"""초등 5학년 연산 문제 - 2022 개정 교육과정 기준."""

from .._base import mc, concept, test


def get_computation_data() -> dict:
    """초등 5학년 연산 개념/문제/테스트 반환."""
    concepts = [
        concept(
            id="concept-e5-mixed-calc",
            name="자연수의 혼합 계산",
            grade="elementary_5",
            category="computation",
            part="calc",
            description="연산 우선순위(괄호→곱셈/나눗셈→덧셈/뺄셈)를 이해하고 혼합 계산을 수행합니다.",
        ),
        concept(
            id="concept-e5-divisor",
            name="약수와 배수",
            grade="elementary_5",
            category="computation",
            part="calc",
            description="약수와 배수의 정의, 최대공약수(GCD), 최소공배수(LCM)를 구하고 활용합니다.",
        ),
        concept(
            id="concept-e5-reduce",
            name="약분과 통분",
            grade="elementary_5",
            category="computation",
            part="calc",
            description="분수의 기본 성질을 이용하여 약분과 통분을 수행하고 기약분수를 만듭니다.",
        ),
        concept(
            id="concept-e5-frac-add",
            name="분수의 덧셈과 뺄셈",
            grade="elementary_5",
            category="computation",
            part="calc",
            description="이분모 분수의 덧셈과 뺄셈을 통분을 통해 계산하고 대분수 연산을 수행합니다.",
        ),
        concept(
            id="concept-e5-frac-mul",
            name="분수의 곱셈",
            grade="elementary_5",
            category="computation",
            part="calc",
            description="분자끼리, 분모끼리 곱하여 분수의 곱셈을 수행하고 대분수는 가분수로 변환합니다.",
        ),
        concept(
            id="concept-e5-dec-mul",
            name="소수의 곱셈",
            grade="elementary_5",
            category="computation",
            part="calc",
            description="소수점 이동 원리를 이해하고 소수의 곱셈을 수행하며 결과를 어림합니다.",
        ),
    ]

    questions = [
        # 1. 자연수의 혼합 계산 (3문제, 난이도 2~4)
        mc(
            id="e5-comp-001",
            concept_id="concept-e5-mixed-calc",
            category="computation",
            part="calc",
            difficulty=2,
            content="다음 식을 계산하시오.\n\n5 + 3 × 4",
            options=["12", "17", "20", "32"],
            correct="B",
            explanation="곱셈을 먼저 계산합니다. 5 + (3 × 4) = 5 + 12 = 17입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-002",
            concept_id="concept-e5-mixed-calc",
            category="computation",
            part="calc",
            difficulty=3,
            content="다음 식을 계산하시오.\n\n(8 + 4) × 3 - 6",
            options=["24", "30", "36", "42"],
            correct="B",
            explanation="괄호 안을 먼저: (8 + 4) = 12, 곱셈: 12 × 3 = 36, 뺄셈: 36 - 6 = 30입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-003",
            concept_id="concept-e5-mixed-calc",
            category="computation",
            part="calc",
            difficulty=4,
            content="다음 식을 계산하시오.\n\n72 ÷ 4 × 3",
            options=["6", "18", "54", "216"],
            correct="C",
            explanation="좌결합성: 왼쪽부터 계산. 72 ÷ 4 = 18, 18 × 3 = 54입니다. (72 ÷ 12 = 6은 오답)",
            points=10,
        ),

        # 2. 약수와 배수 (3문제, 난이도 3~6)
        mc(
            id="e5-comp-004",
            concept_id="concept-e5-divisor",
            category="computation",
            part="calc",
            difficulty=3,
            content="12의 약수는 모두 몇 개입니까?",
            options=["4개", "5개", "6개", "7개"],
            correct="C",
            explanation="12의 약수는 1, 2, 3, 4, 6, 12로 총 6개입니다. (1과 자기 자신 포함 주의)",
            points=10,
        ),
        mc(
            id="e5-comp-005",
            concept_id="concept-e5-divisor",
            category="computation",
            part="calc",
            difficulty=5,
            content="12와 18의 최대공약수(GCD)를 구하시오.",
            options=["3", "6", "9", "18"],
            correct="B",
            explanation="12의 약수: 1,2,3,4,6,12 / 18의 약수: 1,2,3,6,9,18 / 공약수 중 가장 큰 수는 6입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-006",
            concept_id="concept-e5-divisor",
            category="computation",
            part="calc",
            difficulty=6,
            content="4와 6의 최소공배수(LCM)를 구하시오.",
            options=["10", "12", "18", "24"],
            correct="B",
            explanation="4의 배수: 4,8,12,16,... / 6의 배수: 6,12,18,... / 공배수 중 가장 작은 수는 12입니다.",
            points=10,
        ),

        # 3. 약분과 통분 (3문제, 난이도 4~7)
        mc(
            id="e5-comp-007",
            concept_id="concept-e5-reduce",
            category="computation",
            part="calc",
            difficulty=4,
            content="6/8을 기약분수로 나타내시오.",
            options=["2/3", "3/4", "4/5", "5/6"],
            correct="B",
            explanation="분자와 분모를 최대공약수 2로 나눕니다. 6÷2/8÷2 = 3/4입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-008",
            concept_id="concept-e5-reduce",
            category="computation",
            part="calc",
            difficulty=5,
            content="1/2와 1/3을 통분하면 분모는?",
            options=["5", "6", "8", "12"],
            correct="B",
            explanation="2와 3의 최소공배수는 6입니다. 1/2 = 3/6, 1/3 = 2/6으로 통분합니다.",
            points=10,
        ),
        mc(
            id="e5-comp-009",
            concept_id="concept-e5-reduce",
            category="computation",
            part="calc",
            difficulty=7,
            content="15/20을 약분한 후, 다시 분모를 12로 통분하면?",
            options=["6/12", "8/12", "9/12", "10/12"],
            correct="C",
            explanation="15/20 = 3/4 (약분), 3/4 = 9/12 (통분: 분자도 3배)입니다.",
            points=10,
        ),

        # 4. 분수의 덧셈과 뺄셈 (3문제, 난이도 5~8)
        mc(
            id="e5-comp-010",
            concept_id="concept-e5-frac-add",
            category="computation",
            part="calc",
            difficulty=5,
            content="1/2 + 1/3을 계산하시오.",
            options=["2/5", "3/6", "5/6", "1"],
            correct="C",
            explanation="통분: 1/2 = 3/6, 1/3 = 2/6. 따라서 3/6 + 2/6 = 5/6입니다. (1/2+1/3≠2/5 주의)",
            points=10,
        ),
        mc(
            id="e5-comp-011",
            concept_id="concept-e5-frac-add",
            category="computation",
            part="calc",
            difficulty=7,
            content="3/4 - 1/3을 계산하시오.",
            options=["2/1", "5/12", "7/12", "11/12"],
            correct="C",
            explanation="통분: 3/4 = 9/12, 1/3 = 4/12. 따라서 9/12 - 4/12 = 5/12입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-012",
            concept_id="concept-e5-frac-add",
            category="computation",
            part="calc",
            difficulty=8,
            content="3(1/4) - 1(2/3)을 계산하시오. (대분수 뺄셈)",
            options=["1(7/12)", "1(5/12)", "2(7/12)", "2(1/12)"],
            correct="A",
            explanation="통분: 3(3/12) - 1(8/12) = 2(15/12) - 1(8/12) = 1(7/12). (받아내림: 3에서 1을 빌려 12/12)",
            points=10,
        ),

        # 5. 분수의 곱셈 (3문제, 난이도 6~9)
        mc(
            id="e5-comp-013",
            concept_id="concept-e5-frac-mul",
            category="computation",
            part="calc",
            difficulty=6,
            content="2/3 × 3/4를 계산하시오.",
            options=["1/2", "5/7", "6/12", "9/12"],
            correct="A",
            explanation="(2×3)/(3×4) = 6/12 = 1/2입니다. (중간에 약분하면 더 간단)",
            points=10,
        ),
        mc(
            id="e5-comp-014",
            concept_id="concept-e5-frac-mul",
            category="computation",
            part="calc",
            difficulty=8,
            content="3/4 × 2를 계산하시오.",
            options=["3/2", "6/4", "3/8", "5/4"],
            correct="A",
            explanation="3/4 × 2/1 = 6/4 = 3/2입니다. (기약분수로 나타냄)",
            points=10,
        ),
        mc(
            id="e5-comp-015",
            concept_id="concept-e5-frac-mul",
            category="computation",
            part="calc",
            difficulty=9,
            content="1(1/2) × 2(2/3)을 계산하시오. (대분수는 가분수로 변환)",
            options=["2", "3", "4", "5"],
            correct="C",
            explanation="1(1/2) = 3/2, 2(2/3) = 8/3. (3/2) × (8/3) = 24/6 = 4입니다.",
            points=10,
        ),

        # 6. 소수의 곱셈 (3문제, 난이도 7~10)
        mc(
            id="e5-comp-016",
            concept_id="concept-e5-dec-mul",
            category="computation",
            part="calc",
            difficulty=7,
            content="1.2 × 3을 계산하시오.",
            options=["3.6", "4.2", "36", "42"],
            correct="A",
            explanation="12 × 3 = 36, 소수점 1자리 → 3.6입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-017",
            concept_id="concept-e5-dec-mul",
            category="computation",
            part="calc",
            difficulty=9,
            content="0.2 × 0.3을 계산하시오.",
            options=["0.06", "0.6", "6", "60"],
            correct="A",
            explanation="2 × 3 = 6, 소수점 2자리(0.1×2) → 0.06입니다. (0 처리 주의)",
            points=10,
        ),
        mc(
            id="e5-comp-018",
            concept_id="concept-e5-dec-mul",
            category="computation",
            part="calc",
            difficulty=10,
            content="2.5 × 1.2를 계산하시오. (어림: 2×1=2, 3×2=6 사이)",
            options=["2.0", "3.0", "3.7", "30"],
            correct="B",
            explanation="25 × 12 = 300, 소수점 2자리 → 3.00 = 3.0입니다. (어림으로 검증)",
            points=10,
        ),
    ]

    tests = [
        test(
            id="test-e5-computation",
            title="초5 연산 종합 테스트",
            description="혼합 계산, 약수/배수, 약분/통분, 분수 덧뺄셈/곱셈, 소수 곱셈",
            grade="elementary_5",
            concept_ids=[
                "concept-e5-mixed-calc",
                "concept-e5-divisor",
                "concept-e5-reduce",
                "concept-e5-frac-add",
                "concept-e5-frac-mul",
                "concept-e5-dec-mul",
            ],
            question_ids=[f"e5-comp-{str(i).zfill(3)}" for i in range(1, 19)],
            time_limit_minutes=25,
            use_question_pool=True,
            questions_per_attempt=12,
        ),
    ]

    return {"concepts": concepts, "questions": questions, "tests": tests}
