"""초등 5학년 연산 문제 - 약수와 배수, 분수의 곱셈, 소수의 곱셈."""
from app.seeds._base import mc, concept


def get_concepts():
    """초등 5학년 연산 개념 반환."""
    return [
        concept(
            id="concept-e5-comp",
            name="약수와 배수, 분수·소수의 곱셈",
            grade="elementary_5",
            category="computation",
            part="연산",
            description="약수와 배수의 개념, 최대공약수와 최소공배수, 분수의 곱셈, 소수의 곱셈을 다룹니다.",
        ),
    ]


def get_questions():
    """초등 5학년 연산 문제 반환."""
    return [
        # 약수와 배수 (난이도 1-3)
        mc(
            id="e5-comp-001",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=1,
            content="12의 약수는 모두 몇 개입니까?",
            options=[
                ("4개",),
                ("5개",),
                ("6개",),
                ("7개",),
            ],
            correct="C",
            explanation="12의 약수는 1, 2, 3, 4, 6, 12로 총 6개입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-002",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=2,
            content="18과 24의 공약수를 모두 고르세요.",
            options=[
                ("1, 2, 3, 6",),
                ("1, 2, 3, 4, 6",),
                ("1, 2, 4, 6",),
                ("1, 3, 6, 9",),
            ],
            correct="A",
            explanation="18의 약수: 1, 2, 3, 6, 9, 18 / 24의 약수: 1, 2, 3, 4, 6, 8, 12, 24 / 공통된 약수는 1, 2, 3, 6입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-003",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=3,
            content="12와 18의 최대공약수를 구하세요.",
            options=[
                ("3",),
                ("6",),
                ("9",),
                ("12",),
            ],
            correct="B",
            explanation="12의 약수: 1, 2, 3, 4, 6, 12 / 18의 약수: 1, 2, 3, 6, 9, 18 / 공약수 중 가장 큰 수는 6입니다.",
            points=10,
        ),
        # 분수의 곱셈 (난이도 4-6)
        mc(
            id="e5-comp-004",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=4,
            content="2/3 × 4/5를 계산하세요.",
            options=[
                ("6/8",),
                ("8/15",),
                ("6/15",),
                ("10/12",),
            ],
            correct="B",
            explanation="2/3 × 4/5 = (2×4)/(3×5) = 8/15입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-005",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=5,
            content="3/4 × 2를 계산하면 얼마입니까?",
            options=[
                ("3/2",),
                ("5/4",),
                ("6/4",),
                ("3/8",),
            ],
            correct="A",
            explanation="3/4 × 2 = 3/4 × 2/1 = 6/4 = 3/2입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-006",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=6,
            content="5/6 × 3/10을 기약분수로 나타내세요.",
            options=[
                ("1/4",),
                ("15/60",),
                ("1/2",),
                ("3/12",),
            ],
            correct="A",
            explanation="5/6 × 3/10 = 15/60 = 1/4입니다.",
            points=10,
        ),
        # 소수의 곱셈 (난이도 7-10)
        mc(
            id="e5-comp-007",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=7,
            content="1.2 × 3.5를 계산하세요.",
            options=[
                ("4.2",),
                ("3.7",),
                ("4.7",),
                ("42",),
            ],
            correct="A",
            explanation="1.2 × 3.5 = 4.2입니다. (12 × 35 = 420, 소수점 2자리)",
            points=10,
        ),
        mc(
            id="e5-comp-008",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=8,
            content="0.25 × 0.8을 계산하면?",
            options=[
                ("0.2",),
                ("2.0",),
                ("0.02",),
                ("20",),
            ],
            correct="A",
            explanation="0.25 × 0.8 = 0.2입니다. (25 × 8 = 200, 소수점 3자리)",
            points=10,
        ),
        mc(
            id="e5-comp-009",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=9,
            content="24와 36의 최소공배수는 얼마입니까?",
            options=[
                ("72",),
                ("144",),
                ("48",),
                ("96",),
            ],
            correct="A",
            explanation="24 = 2³ × 3, 36 = 2² × 3². 최소공배수 = 2³ × 3² = 8 × 9 = 72입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-010",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=10,
            content="2.4 × 1.25를 계산하세요.",
            options=[
                ("3.0",),
                ("3.6",),
                ("2.5",),
                ("30",),
            ],
            correct="A",
            explanation="2.4 × 1.25 = 3.0입니다. (24 × 125 = 3000, 소수점 3자리)",
            points=10,
        ),
        # 추가 문제 (난이도 다양화)
        mc(
            id="e5-comp-011",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=2,
            content="3의 배수 중에서 20보다 작은 수는 모두 몇 개입니까?",
            options=[
                ("5개",),
                ("6개",),
                ("7개",),
                ("8개",),
            ],
            correct="B",
            explanation="3, 6, 9, 12, 15, 18로 총 6개입니다.",
            points=10,
        ),
        mc(
            id="e5-comp-012",
            concept_id="concept-e5-comp",
            category="computation",
            part="연산",
            difficulty=5,
            content="1과 1/2 × 2/3를 계산하세요.",
            options=[
                ("1",),
                ("3/2",),
                ("2/3",),
                ("1과 1/3",),
            ],
            correct="A",
            explanation="1과 1/2 = 3/2이므로, 3/2 × 2/3 = 6/6 = 1입니다.",
            points=10,
        ),
    ]
