"""초등 5학년 개념 문제 - 합동과 대칭, 규칙과 대응, 평균."""
from app.seeds._base import mc, concept


def get_concepts():
    """초등 5학년 개념 반환."""
    return [
        concept(
            id="concept-e5-conc",
            name="합동과 대칭, 규칙과 대응, 평균",
            grade="elementary_5",
            category="concept",
            part="개념",
            description="합동의 조건, 선대칭과 점대칭, 대응 관계, 평균의 의미를 다룹니다.",
        ),
    ]


def get_questions():
    """초등 5학년 개념 문제 반환."""
    return [
        # 합동 (난이도 1-3)
        mc(
            id="e5-conc-001",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=1,
            content="두 도형이 합동이 되려면 어떤 조건을 만족해야 합니까?",
            options=[
                ("모양만 같으면 된다",),
                ("크기만 같으면 된다",),
                ("모양과 크기가 모두 같아야 한다",),
                ("색깔이 같아야 한다",),
            ],
            correct="C",
            explanation="합동은 모양과 크기가 완전히 같은 도형을 말합니다.",
            points=10,
        ),
        mc(
            id="e5-conc-002",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=2,
            content="삼각형 ABC와 삼각형 DEF가 합동일 때, 각 A의 대응각은 무엇입니까?",
            options=[
                ("각 D",),
                ("각 E",),
                ("각 F",),
                ("알 수 없다",),
            ],
            correct="A",
            explanation="합동인 두 도형에서 대응하는 꼭짓점의 각은 서로 같습니다. A는 D에 대응합니다.",
            points=10,
        ),
        mc(
            id="e5-conc-003",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=3,
            content="합동인 두 삼각형에서 대응하는 변의 길이는 어떤 관계입니까?",
            options=[
                ("항상 다르다",),
                ("항상 같다",),
                ("2배 관계이다",),
                ("관계가 없다",),
            ],
            correct="B",
            explanation="합동인 도형의 대응변의 길이는 항상 같습니다.",
            points=10,
        ),
        # 선대칭과 점대칭 (난이도 4-6)
        mc(
            id="e5-conc-004",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=4,
            content="선대칭도형에서 대칭축을 기준으로 접었을 때 어떻게 됩니까?",
            options=[
                ("완전히 겹친다",),
                ("전혀 겹치지 않는다",),
                ("일부만 겹친다",),
                ("2배로 커진다",),
            ],
            correct="A",
            explanation="선대칭도형은 대칭축을 기준으로 접으면 완전히 겹치는 도형입니다.",
            points=10,
        ),
        mc(
            id="e5-conc-005",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=5,
            content="다음 중 점대칭도형이 아닌 것은?",
            options=[
                ("정삼각형",),
                ("정사각형",),
                ("정육각형",),
                ("원",),
            ],
            correct="A",
            explanation="정삼각형은 선대칭도형이지만 점대칭도형은 아닙니다.",
            points=10,
        ),
        mc(
            id="e5-conc-006",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=6,
            content="점대칭도형을 대칭의 중심을 기준으로 180도 돌리면?",
            options=[
                ("원래 도형과 완전히 겹친다",),
                ("전혀 겹치지 않는다",),
                ("90도만 돌린 모양이 된다",),
                ("크기가 2배가 된다",),
            ],
            correct="A",
            explanation="점대칭도형은 대칭의 중심을 기준으로 180도 돌리면 원래 도형과 완전히 겹칩니다.",
            points=10,
        ),
        # 규칙과 대응 (난이도 7-8)
        mc(
            id="e5-conc-007",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=7,
            content="x와 y의 대응 관계가 y = 3x + 2일 때, x가 5이면 y는?",
            options=[
                ("15",),
                ("17",),
                ("13",),
                ("18",),
            ],
            correct="B",
            explanation="y = 3 × 5 + 2 = 15 + 2 = 17입니다.",
            points=10,
        ),
        mc(
            id="e5-conc-008",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=8,
            content="수의 배열이 1, 4, 7, 10, ... 일 때, 5번째 수는?",
            options=[
                ("12",),
                ("13",),
                ("14",),
                ("15",),
            ],
            correct="B",
            explanation="규칙은 3씩 더하기입니다. 10 + 3 = 13이 5번째 수입니다.",
            points=10,
        ),
        # 평균 (난이도 9-10)
        mc(
            id="e5-conc-009",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=9,
            content="10, 15, 20, 25의 평균은?",
            options=[
                ("15",),
                ("17.5",),
                ("18",),
                ("20",),
            ],
            correct="B",
            explanation="평균 = (10 + 15 + 20 + 25) ÷ 4 = 70 ÷ 4 = 17.5입니다.",
            points=10,
        ),
        mc(
            id="e5-conc-010",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=10,
            content="5개의 수의 평균이 12일 때, 5개의 수의 합은?",
            options=[
                ("50",),
                ("55",),
                ("60",),
                ("65",),
            ],
            correct="C",
            explanation="평균 = 합 ÷ 개수이므로, 합 = 평균 × 개수 = 12 × 5 = 60입니다.",
            points=10,
        ),
        # 추가 문제
        mc(
            id="e5-conc-011",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=3,
            content="다음 중 선대칭도형인 것은?",
            options=[
                ("직각삼각형",),
                ("이등변삼각형",),
                ("평행사변형",),
                ("일반 사각형",),
            ],
            correct="B",
            explanation="이등변삼각형은 밑변의 중점을 지나는 수직선을 대칭축으로 하는 선대칭도형입니다.",
            points=10,
        ),
        mc(
            id="e5-conc-012",
            concept_id="concept-e5-conc",
            category="concept",
            part="개념",
            difficulty=6,
            content="80, 85, 90, 95의 평균을 구하세요.",
            options=[
                ("85",),
                ("87.5",),
                ("90",),
                ("92.5",),
            ],
            correct="B",
            explanation="평균 = (80 + 85 + 90 + 95) ÷ 4 = 350 ÷ 4 = 87.5입니다.",
            points=10,
        ),
    ]
