"""초등 5학년 빈칸 채우기 문제 - 2022 개정 교육과정 기준 (PDF 기반 70개 세분화 개념).

전체 70개 개념 커버:
  1학기 (33개): 혼합 계산(5), 약수와 배수(6), 규칙과 대응(3), 약분과 통분(6), 분수의 덧셈과 뺄셈(6), 다각형의 둘레와 넓이(9)
  2학기 (37개): 수의 범위와 어림하기(7), 분수의 곱셈(5), 합동과 대칭(4), 소수의 곱셈(7), 직육면체(6), 평균과 가능성(6)

총 70개 문제 (개념당 1개)
"""
from .._base import fb


def get_questions() -> list[dict]:
    """빈칸 채우기 문제 70개 반환."""
    return [
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 1단원: 혼합 계산 (5개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-1-1-01-fb-001",
            concept_id="e5-1-1-01",
            category="computation",
            part="calc",
            difficulty=3,
            content="5 + 3 × 4 = ____",
            answer="17",
            explanation="곱셈을 먼저 계산합니다. 5 + (3 × 4) = 5 + 12 = 17입니다.",
            accept_formats=["17"],
        ),
        fb(
            id="e5-1-1-02-fb-001",
            concept_id="e5-1-1-02",
            category="computation",
            part="calc",
            difficulty=4,
            content="20 - 4 × 3 = ____",
            answer="8",
            explanation="곱셈을 먼저 계산합니다. 20 - (4 × 3) = 20 - 12 = 8입니다.",
            accept_formats=["8"],
        ),
        fb(
            id="e5-1-1-03-fb-001",
            concept_id="e5-1-1-03",
            category="computation",
            part="calc",
            difficulty=5,
            content="72 ÷ 4 × 3 = ____",
            answer="54",
            explanation="좌결합성: 왼쪽부터 계산합니다. 72 ÷ 4 = 18, 18 × 3 = 54입니다.",
            accept_formats=["54"],
        ),
        fb(
            id="e5-1-1-04-fb-001",
            concept_id="e5-1-1-04",
            category="computation",
            part="calc",
            difficulty=6,
            content="(12 + 8) ÷ 4 = ____",
            answer="5",
            explanation="괄호를 먼저 계산합니다. (12 + 8) = 20, 20 ÷ 4 = 5입니다.",
            accept_formats=["5"],
        ),
        fb(
            id="e5-1-1-05-fb-001",
            concept_id="e5-1-1-05",
            category="computation",
            part="calc",
            difficulty=7,
            content="30 - (12 - 5) × 2 = ____",
            answer="16",
            explanation="괄호 먼저, 그 다음 곱셈, 마지막 뺄셈. (12 - 5) = 7, 7 × 2 = 14, 30 - 14 = 16입니다.",
            accept_formats=["16"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 2단원: 약수와 배수 (6개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-1-2-01-fb-001",
            concept_id="e5-1-2-01",
            category="concept",
            part="calc",
            difficulty=4,
            content="12의 약수는 모두 ____개입니다.",
            answer="6",
            explanation="12의 약수는 1, 2, 3, 4, 6, 12로 총 6개입니다.",
            accept_formats=["6"],
        ),
        fb(
            id="e5-1-2-02-fb-001",
            concept_id="e5-1-2-02",
            category="concept",
            part="calc",
            difficulty=5,
            content="5의 배수는 ____의 자리 숫자가 0 또는 5입니다.",
            answer="일",
            explanation="5의 배수는 일의 자리 숫자가 0 또는 5입니다. 예: 10, 15, 20, 25",
            accept_formats=["일"],
        ),
        fb(
            id="e5-1-2-03-fb-001",
            concept_id="e5-1-2-03",
            category="concept",
            part="calc",
            difficulty=6,
            content="12와 18의 공약수는 1, 2, 3, ____입니다.",
            answer="6",
            explanation="12의 약수: 1,2,3,4,6,12. 18의 약수: 1,2,3,6,9,18. 공약수: 1,2,3,6입니다.",
            accept_formats=["6"],
        ),
        fb(
            id="e5-1-2-04-fb-001",
            concept_id="e5-1-2-04",
            category="computation",
            part="calc",
            difficulty=6,
            content="12와 18의 최대공약수는 ____입니다.",
            answer="6",
            explanation="거꾸로 나눗셈: 2)12 18 → 3)6 9 → 2 3. GCD = 2 × 3 = 6입니다.",
            accept_formats=["6"],
        ),
        fb(
            id="e5-1-2-05-fb-001",
            concept_id="e5-1-2-05",
            category="concept",
            part="calc",
            difficulty=5,
            content="4와 6의 공배수는 12, 24, 36, ____입니다.",
            answer="48",
            explanation="4와 6의 최소공배수는 12이므로, 공배수는 12의 배수입니다. 36 다음은 48입니다.",
            accept_formats=["48"],
        ),
        fb(
            id="e5-1-2-06-fb-001",
            concept_id="e5-1-2-06",
            category="computation",
            part="calc",
            difficulty=6,
            content="4와 6의 최소공배수는 ____입니다.",
            answer="12",
            explanation="거꾸로 나눗셈: 2)4 6 → 2 3. LCM = 2 × 2 × 3 = 12입니다.",
            accept_formats=["12"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 3단원: 규칙과 대응 (3개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-1-3-01-fb-001",
            concept_id="e5-1-3-01",
            category="concept",
            part="algebra",
            difficulty=4,
            content="자전거가 5대 있을 때 바퀴는 모두 ____개입니다. (1대당 2개)",
            answer="10",
            explanation="바퀴 수 = 자전거 수 × 2 = 5 × 2 = 10개입니다.",
            accept_formats=["10"],
        ),
        fb(
            id="e5-1-3-02-fb-001",
            concept_id="e5-1-3-02",
            category="concept",
            part="algebra",
            difficulty=6,
            content="y = ○ × 3 + 1일 때, ○ = 4이면 y = ____입니다.",
            answer="13",
            explanation="y = 4 × 3 + 1 = 12 + 1 = 13입니다.",
            accept_formats=["13"],
        ),
        fb(
            id="e5-1-3-03-fb-001",
            concept_id="e5-1-3-03",
            category="concept",
            part="algebra",
            difficulty=7,
            content="한 변이 n cm인 정사각형의 둘레는 ____×n cm입니다.",
            answer="4",
            explanation="정사각형의 둘레 = 한 변 × 4 = 4n cm입니다.",
            accept_formats=["4"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 4단원: 약분과 통분 (6개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-1-4-01-fb-001",
            concept_id="e5-1-4-01",
            category="concept",
            part="calc",
            difficulty=4,
            content="6/9를 약분할 수 있는 수는 ____입니다.",
            answer="3",
            explanation="6과 9의 공약수는 1과 3입니다. 약분할 수 있는 수는 3입니다.",
            accept_formats=["3"],
        ),
        fb(
            id="e5-1-4-02-fb-001",
            concept_id="e5-1-4-02",
            category="computation",
            part="calc",
            difficulty=4,
            content="6/9를 기약분수로 나타내면 ____입니다. (분수 형태로 입력)",
            answer="2/3",
            explanation="6과 9의 최대공약수는 3입니다. 6÷3 / 9÷3 = 2/3입니다.",
            accept_formats=["2/3"],
        ),
        fb(
            id="e5-1-4-03-fb-001",
            concept_id="e5-1-4-03",
            category="computation",
            part="calc",
            difficulty=5,
            content="1/2를 분모가 8인 분수로 나타내면 ____입니다.",
            answer="4/8",
            explanation="1/2 = (1×4)/(2×4) = 4/8입니다.",
            accept_formats=["4/8"],
        ),
        fb(
            id="e5-1-4-04-fb-001",
            concept_id="e5-1-4-04",
            category="concept",
            part="calc",
            difficulty=5,
            content="1/2와 1/4를 통분하면 분모는 ____입니다.",
            answer="4",
            explanation="2와 4의 최소공배수는 4입니다. 1/2 = 2/4, 1/4 = 1/4입니다.",
            accept_formats=["4"],
        ),
        fb(
            id="e5-1-4-05-fb-001",
            concept_id="e5-1-4-05",
            category="computation",
            part="calc",
            difficulty=6,
            content="2/3와 3/4를 통분하면 분모는 ____입니다.",
            answer="12",
            explanation="3과 4의 최소공배수는 12입니다. 2/3 = 8/12, 3/4 = 9/12입니다.",
            accept_formats=["12"],
        ),
        fb(
            id="e5-1-4-06-fb-001",
            concept_id="e5-1-4-06",
            category="concept",
            part="calc",
            difficulty=5,
            content="2/5와 3/5 중에서 더 큰 분수는 ____입니다.",
            answer="3/5",
            explanation="분모가 같은 분수는 분자가 클수록 큽니다. 2 < 3이므로 2/5 < 3/5입니다.",
            accept_formats=["3/5"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 5단원: 분수의 덧셈과 뺄셈 (6개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-1-5-01-fb-001",
            concept_id="e5-1-5-01",
            category="computation",
            part="calc",
            difficulty=5,
            content="1/2 + 1/4 = ____ (분수 형태로 입력)",
            answer="3/4",
            explanation="통분: 1/2 = 2/4, 2/4 + 1/4 = 3/4입니다.",
            accept_formats=["3/4"],
        ),
        fb(
            id="e5-1-5-02-fb-001",
            concept_id="e5-1-5-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="5/6 - 1/3 = ____ (분수 형태로 입력)",
            answer="1/2",
            explanation="통분: 1/3 = 2/6, 5/6 - 2/6 = 3/6 = 1/2입니다.",
            accept_formats=["1/2", "3/6"],
        ),
        fb(
            id="e5-1-5-03-fb-001",
            concept_id="e5-1-5-03",
            category="computation",
            part="calc",
            difficulty=6,
            content="1과 1/4 + 2와 1/2 = ____ (대분수로 입력)",
            answer="3과 3/4",
            explanation="1/2 = 2/4이므로, 자연수: 1+2=3, 분수: 1/4+2/4=3/4. 답: 3과 3/4입니다.",
            accept_formats=["3과 3/4", "3 3/4", "15/4"],
        ),
        fb(
            id="e5-1-5-04-fb-001",
            concept_id="e5-1-5-04",
            category="computation",
            part="calc",
            difficulty=7,
            content="2와 1/3 - 1과 2/3 = ____ (분수로 입력)",
            answer="2/3",
            explanation="1/3에서 2/3을 뺄 수 없으므로, 2와 1/3 = 1과 4/3. 1과 4/3 - 1과 2/3 = 2/3입니다.",
            accept_formats=["2/3"],
        ),
        fb(
            id="e5-1-5-05-fb-001",
            concept_id="e5-1-5-05",
            category="computation",
            part="calc",
            difficulty=8,
            content="3 - 1과 2/5 = ____ (대분수로 입력)",
            answer="1과 3/5",
            explanation="3 = 2와 5/5. 2와 5/5 - 1과 2/5 = 1과 3/5입니다.",
            accept_formats=["1과 3/5", "1 3/5", "8/5"],
        ),
        fb(
            id="e5-1-5-06-fb-001",
            concept_id="e5-1-5-06",
            category="application",
            part="calc",
            difficulty=7,
            content="밧줄 2와 1/4 m에서 1과 3/4 m를 사용했습니다. 남은 밧줄은 ____ m입니다.",
            answer="1/2",
            explanation="2와 1/4 - 1과 3/4 = 2/4 = 1/2 m입니다.",
            accept_formats=["1/2", "2/4"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 6단원: 다각형의 둘레와 넓이 (9개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-1-6-01-fb-001",
            concept_id="e5-1-6-01",
            category="concept",
            part="geo",
            difficulty=4,
            content="한 변이 5cm인 정사각형의 둘레는 ____cm입니다.",
            answer="20",
            explanation="정사각형 둘레 = 한 변 × 4 = 5 × 4 = 20cm입니다.",
            accept_formats=["20"],
        ),
        fb(
            id="e5-1-6-02-fb-001",
            concept_id="e5-1-6-02",
            category="concept",
            part="geo",
            difficulty=5,
            content="가로가 8cm, 세로가 5cm인 직사각형의 넓이는 ____cm²입니다.",
            answer="40",
            explanation="직사각형 넓이 = 가로 × 세로 = 8 × 5 = 40cm²입니다.",
            accept_formats=["40"],
        ),
        fb(
            id="e5-1-6-03-fb-001",
            concept_id="e5-1-6-03",
            category="concept",
            part="geo",
            difficulty=5,
            content="밑변이 8cm, 높이가 5cm인 평행사변형의 넓이는 ____cm²입니다.",
            answer="40",
            explanation="평행사변형 넓이 = 밑변 × 높이 = 8 × 5 = 40cm²입니다.",
            accept_formats=["40"],
        ),
        fb(
            id="e5-1-6-04-fb-001",
            concept_id="e5-1-6-04",
            category="concept",
            part="geo",
            difficulty=6,
            content="밑변이 10cm, 높이가 6cm인 삼각형의 넓이는 ____cm²입니다.",
            answer="30",
            explanation="삼각형 넓이 = 밑변 × 높이 ÷ 2 = 10 × 6 ÷ 2 = 30cm²입니다.",
            accept_formats=["30"],
        ),
        fb(
            id="e5-1-6-05-fb-001",
            concept_id="e5-1-6-05",
            category="concept",
            part="geo",
            difficulty=7,
            content="두 대각선의 길이가 각각 8cm, 6cm인 마름모의 넓이는 ____cm²입니다.",
            answer="24",
            explanation="마름모 넓이 = 대각선 × 대각선 ÷ 2 = 8 × 6 ÷ 2 = 24cm²입니다.",
            accept_formats=["24"],
        ),
        fb(
            id="e5-1-6-06-fb-001",
            concept_id="e5-1-6-06",
            category="concept",
            part="geo",
            difficulty=7,
            content="윗변 4cm, 아랫변 6cm, 높이 5cm인 사다리꼴의 넓이는 ____cm²입니다.",
            answer="25",
            explanation="사다리꼴 넓이 = (윗변 + 아랫변) × 높이 ÷ 2 = (4 + 6) × 5 ÷ 2 = 25cm²입니다.",
            accept_formats=["25"],
        ),
        fb(
            id="e5-1-6-07-fb-001",
            concept_id="e5-1-6-07",
            category="application",
            part="geo",
            difficulty=8,
            content="직사각형에서 삼각형을 잘라낸 도형의 넓이를 구할 때 사용하는 방법은 ____입니다.",
            answer="뺄셈",
            explanation="전체 직사각형 넓이에서 잘라낸 삼각형 넓이를 빼면 됩니다.",
            accept_formats=["뺄셈", "빼기", "차"],
        ),
        fb(
            id="e5-1-6-08-fb-001",
            concept_id="e5-1-6-08",
            category="application",
            part="geo",
            difficulty=8,
            content="평행사변형 2개로 나눈 도형의 전체 넓이를 구할 때 사용하는 방법은 ____입니다.",
            answer="덧셈",
            explanation="각 평행사변형의 넓이를 구한 후 더하면 됩니다.",
            accept_formats=["덧셈", "더하기", "합"],
        ),
        fb(
            id="e5-1-6-09-fb-001",
            concept_id="e5-1-6-09",
            category="application",
            part="geo",
            difficulty=9,
            content="밑변 12cm, 높이 8cm인 평행사변형을 밑변이 6cm인 삼각형으로 바꾸면, 높이는 ____cm입니다.",
            answer="16",
            explanation="평행사변형 넓이 = 12 × 8 = 96cm². 삼각형: 6 × h ÷ 2 = 96, 3h = 96, h = 16cm입니다.",
            accept_formats=["16"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 1단원: 수의 범위와 어림하기 (7개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-2-1-01-fb-001",
            concept_id="e5-2-1-01",
            category="concept",
            part="calc",
            difficulty=4,
            content="10 이상 15 미만인 자연수는 모두 ____개입니다.",
            answer="5",
            explanation="10 이상(포함) 15 미만(불포함): 10, 11, 12, 13, 14로 총 5개입니다.",
            accept_formats=["5"],
        ),
        fb(
            id="e5-2-1-02-fb-001",
            concept_id="e5-2-1-02",
            category="concept",
            part="calc",
            difficulty=5,
            content="8 초과 12 이하인 자연수는 모두 ____개입니다.",
            answer="4",
            explanation="8 초과(불포함) 12 이하(포함): 9, 10, 11, 12로 총 4개입니다.",
            accept_formats=["4"],
        ),
        fb(
            id="e5-2-1-03-fb-001",
            concept_id="e5-2-1-03",
            category="concept",
            part="calc",
            difficulty=5,
            content="743을 십의 자리에서 올림하면 ____입니다.",
            answer="800",
            explanation="십의 자리(4)를 올림하면 백의 자리가 1 증가합니다. 743 → 800입니다.",
            accept_formats=["800"],
        ),
        fb(
            id="e5-2-1-04-fb-001",
            concept_id="e5-2-1-04",
            category="concept",
            part="calc",
            difficulty=5,
            content="867을 십의 자리에서 버림하면 ____입니다.",
            answer="800",
            explanation="십의 자리 아래를 모두 0으로 만듭니다. 867 → 800입니다.",
            accept_formats=["800"],
        ),
        fb(
            id="e5-2-1-05-fb-001",
            concept_id="e5-2-1-05",
            category="concept",
            part="calc",
            difficulty=6,
            content="345를 십의 자리에서 반올림하면 ____입니다.",
            answer="300",
            explanation="십의 자리(4)가 5 미만이므로 버림합니다. 345 → 300입니다.",
            accept_formats=["300"],
        ),
        fb(
            id="e5-2-1-06-fb-001",
            concept_id="e5-2-1-06",
            category="concept",
            part="calc",
            difficulty=6,
            content="876을 십의 자리에서 반올림하면 ____입니다.",
            answer="900",
            explanation="십의 자리(7)가 5 이상이므로 올림합니다. 876 → 900입니다.",
            accept_formats=["900"],
        ),
        fb(
            id="e5-2-1-07-fb-001",
            concept_id="e5-2-1-07",
            category="application",
            part="calc",
            difficulty=7,
            content="사과 23개를 한 상자에 5개씩 담으려면 최소 ____상자가 필요합니다.",
            answer="5",
            explanation="23 ÷ 5 = 4 나머지 3. 나머지가 있으므로 올림하여 5상자가 필요합니다.",
            accept_formats=["5"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 2단원: 분수의 곱셈 (5개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-2-2-01-fb-001",
            concept_id="e5-2-2-01",
            category="computation",
            part="calc",
            difficulty=5,
            content="2/5 × 3 = ____ (분수 형태로 입력)",
            answer="6/5",
            explanation="2/5 × 3 = 2/5 × 3/1 = (2×3)/(5×1) = 6/5입니다.",
            accept_formats=["6/5", "1 1/5"],
        ),
        fb(
            id="e5-2-2-02-fb-001",
            concept_id="e5-2-2-02",
            category="computation",
            part="calc",
            difficulty=5,
            content="1/2 × 1/3 = ____ (분수 형태로 입력)",
            answer="1/6",
            explanation="(1×1) / (2×3) = 1/6입니다.",
            accept_formats=["1/6"],
        ),
        fb(
            id="e5-2-2-03-fb-001",
            concept_id="e5-2-2-03",
            category="computation",
            part="calc",
            difficulty=6,
            content="2와 1/3 × 3 = ____ (대분수로 입력)",
            answer="7",
            explanation="2와 1/3 = 7/3. 7/3 × 3 = 21/3 = 7입니다.",
            accept_formats=["7"],
        ),
        fb(
            id="e5-2-2-04-fb-001",
            concept_id="e5-2-2-04",
            category="computation",
            part="calc",
            difficulty=7,
            content="1과 1/2 × 2와 1/3 = ____ (대분수로 입력)",
            answer="3과 1/2",
            explanation="3/2 × 7/3 = 21/6 = 7/2 = 3과 1/2입니다.",
            accept_formats=["3과 1/2", "3 1/2", "7/2"],
        ),
        fb(
            id="e5-2-2-05-fb-001",
            concept_id="e5-2-2-05",
            category="application",
            part="calc",
            difficulty=7,
            content="리본 1m의 무게가 2/5 kg입니다. 리본 3m의 무게는 ____ kg입니다.",
            answer="6/5",
            explanation="2/5 × 3 = 6/5 kg = 1과 1/5 kg입니다.",
            accept_formats=["6/5", "1 1/5"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 3단원: 합동과 대칭 (4개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-2-3-01-fb-001",
            concept_id="e5-2-3-01",
            category="concept",
            part="geo",
            difficulty=5,
            content="모양과 크기가 같아 완전히 겹쳐지는 두 도형을 서로 ____이라고 합니다.",
            answer="합동",
            explanation="합동: 모양과 크기가 같아 완전히 겹쳐지는 관계입니다.",
            accept_formats=["합동"],
        ),
        fb(
            id="e5-2-3-02-fb-001",
            concept_id="e5-2-3-02",
            category="concept",
            part="geo",
            difficulty=6,
            content="선대칭도형을 대칭축으로 접으면 ____하게 겹칩니다.",
            answer="완전",
            explanation="선대칭도형은 대칭축을 따라 접으면 완전히 겹치는 도형입니다.",
            accept_formats=["완전", "완전히"],
        ),
        fb(
            id="e5-2-3-03-fb-001",
            concept_id="e5-2-3-03",
            category="concept",
            part="geo",
            difficulty=6,
            content="점대칭도형은 대칭의 중심을 기준으로 ____도 돌렸을 때 완전히 겹칩니다.",
            answer="180",
            explanation="점대칭도형은 대칭의 중심을 기준으로 180도 회전하면 완전히 겹칩니다.",
            accept_formats=["180"],
        ),
        fb(
            id="e5-2-3-04-fb-001",
            concept_id="e5-2-3-04",
            category="application",
            part="geo",
            difficulty=7,
            content="선대칭이면서 점대칭인 도형의 예는 ____입니다.",
            answer="정사각형",
            explanation="정사각형, 원 등은 선대칭이면서 동시에 점대칭입니다.",
            accept_formats=["정사각형", "원", "마름모"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 4단원: 소수의 곱셈 (7개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-2-4-01-fb-001",
            concept_id="e5-2-4-01",
            category="computation",
            part="calc",
            difficulty=5,
            content="0.4 × 5 = ____",
            answer="2",
            explanation="4 × 5 = 20, 소수점 1자리 → 2.0 = 2입니다.",
            accept_formats=["2", "2.0"],
        ),
        fb(
            id="e5-2-4-02-fb-001",
            concept_id="e5-2-4-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="0.3 × 0.4 = ____",
            answer="0.12",
            explanation="3 × 4 = 12, 소수점 2자리 → 0.12입니다.",
            accept_formats=["0.12"],
        ),
        fb(
            id="e5-2-4-03-fb-001",
            concept_id="e5-2-4-03",
            category="computation",
            part="calc",
            difficulty=6,
            content="1.5 × 6 = ____",
            answer="9",
            explanation="15 × 6 = 90, 소수점 1자리 → 9.0 = 9입니다.",
            accept_formats=["9", "9.0"],
        ),
        fb(
            id="e5-2-4-04-fb-001",
            concept_id="e5-2-4-04",
            category="computation",
            part="calc",
            difficulty=7,
            content="1.2 × 0.5 = ____",
            answer="0.6",
            explanation="12 × 5 = 60, 소수점 2자리 → 0.60 = 0.6입니다.",
            accept_formats=["0.6"],
        ),
        fb(
            id="e5-2-4-05-fb-001",
            concept_id="e5-2-4-05",
            category="computation",
            part="calc",
            difficulty=8,
            content="2.3 × 1.4 = ____",
            answer="3.22",
            explanation="23 × 14 = 322, 소수점 2자리 → 3.22입니다.",
            accept_formats=["3.22"],
        ),
        fb(
            id="e5-2-4-06-fb-001",
            concept_id="e5-2-4-06",
            category="application",
            part="calc",
            difficulty=7,
            content="한 개에 0.8kg인 수박 3개의 무게는 ____ kg입니다.",
            answer="2.4",
            explanation="0.8 × 3 = 2.4 kg입니다.",
            accept_formats=["2.4"],
        ),
        fb(
            id="e5-2-4-07-fb-001",
            concept_id="e5-2-4-07",
            category="application",
            part="calc",
            difficulty=8,
            content="가로 1.5m, 세로 2.4m인 직사각형의 넓이는 ____ m²입니다.",
            answer="3.6",
            explanation="1.5 × 2.4 = 3.6 m²입니다.",
            accept_formats=["3.6"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 5단원: 직육면체 (6개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-2-5-01-fb-001",
            concept_id="e5-2-5-01",
            category="concept",
            part="geo",
            difficulty=5,
            content="직육면체의 면은 모두 ____개입니다.",
            answer="6",
            explanation="직육면체는 6개의 면으로 이루어져 있습니다.",
            accept_formats=["6"],
        ),
        fb(
            id="e5-2-5-02-fb-001",
            concept_id="e5-2-5-02",
            category="concept",
            part="geo",
            difficulty=4,
            content="직육면체의 꼭짓점은 모두 ____개입니다.",
            answer="8",
            explanation="직육면체는 8개의 꼭짓점으로 이루어져 있습니다.",
            accept_formats=["8"],
        ),
        fb(
            id="e5-2-5-03-fb-001",
            concept_id="e5-2-5-03",
            category="concept",
            part="geo",
            difficulty=6,
            content="직육면체의 모서리는 모두 ____개입니다.",
            answer="12",
            explanation="직육면체는 12개의 모서리로 이루어져 있습니다.",
            accept_formats=["12"],
        ),
        fb(
            id="e5-2-5-04-fb-001",
            concept_id="e5-2-5-04",
            category="concept",
            part="geo",
            difficulty=7,
            content="직육면체의 겨냥도는 보이지 않는 모서리를 ____선으로 그립니다.",
            answer="점",
            explanation="겨냥도는 보이는 모서리를 실선, 보이지 않는 모서리를 점선으로 그립니다.",
            accept_formats=["점", "점선"],
        ),
        fb(
            id="e5-2-5-05-fb-001",
            concept_id="e5-2-5-05",
            category="concept",
            part="geo",
            difficulty=7,
            content="직육면체를 잘라서 펼쳐 놓은 그림을 ____라고 합니다.",
            answer="전개도",
            explanation="전개도: 직육면체를 잘라서 펼쳐 놓은 그림입니다.",
            accept_formats=["전개도"],
        ),
        fb(
            id="e5-2-5-06-fb-001",
            concept_id="e5-2-5-06",
            category="application",
            part="geo",
            difficulty=8,
            content="가로 3cm, 세로 4cm, 높이 5cm인 직육면체의 모든 모서리의 길이의 합은 ____cm입니다.",
            answer="48",
            explanation="(가로 + 세로 + 높이) × 4 = (3 + 4 + 5) × 4 = 12 × 4 = 48cm입니다.",
            accept_formats=["48"],
        ),

        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 6단원: 평균과 가능성 (6개)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e5-2-6-01-fb-001",
            concept_id="e5-2-6-01",
            category="concept",
            part="data",
            difficulty=5,
            content="5, 7, 9, 11의 평균은 ____입니다.",
            answer="8",
            explanation="평균 = (5 + 7 + 9 + 11) ÷ 4 = 32 ÷ 4 = 8입니다.",
            accept_formats=["8"],
        ),
        fb(
            id="e5-2-6-02-fb-001",
            concept_id="e5-2-6-02",
            category="application",
            part="data",
            difficulty=6,
            content="3개의 수의 평균이 12일 때, 세 수의 합은 ____입니다.",
            answer="36",
            explanation="평균 × 개수 = 합. 12 × 3 = 36입니다.",
            accept_formats=["36"],
        ),
        fb(
            id="e5-2-6-03-fb-001",
            concept_id="e5-2-6-03",
            category="application",
            part="data",
            difficulty=7,
            content="5개의 수 6, 8, 10, 12, ○의 평균이 10일 때, ○ = ____입니다.",
            answer="14",
            explanation="합 = 평균 × 개수 = 10 × 5 = 50. 6+8+10+12+○ = 50, ○ = 14입니다.",
            accept_formats=["14"],
        ),
        fb(
            id="e5-2-6-04-fb-001",
            concept_id="e5-2-6-04",
            category="concept",
            part="data",
            difficulty=7,
            content="동전을 던질 때 앞면이 나올 가능성을 수치로 표현하면 ____입니다. (분수 형태)",
            answer="1/2",
            explanation="동전은 앞면/뒷면 2가지 경우. 앞면 1가지 / 전체 2가지 = 1/2입니다.",
            accept_formats=["1/2", "0.5"],
        ),
        fb(
            id="e5-2-6-05-fb-001",
            concept_id="e5-2-6-05",
            category="concept",
            part="data",
            difficulty=6,
            content="일어날 수 없는 일의 가능성은 ____입니다.",
            answer="0",
            explanation="불가능한 일의 가능성은 0입니다. 예: 주사위에서 7이 나올 가능성",
            accept_formats=["0"],
        ),
        fb(
            id="e5-2-6-06-fb-001",
            concept_id="e5-2-6-06",
            category="concept",
            part="data",
            difficulty=6,
            content="반드시 일어나는 일의 가능성은 ____입니다.",
            answer="1",
            explanation="확실한 일의 가능성은 1입니다. 예: 주사위에서 6 이하의 수가 나올 가능성",
            accept_formats=["1"],
        ),
    ]
