"""초등 5학년 빈칸 채우기 문제 - 2022 개정 교육과정 기준 (전 12단원)."""

from .._base import fb, test


def get_fill_blank_data() -> dict:
    """초등 5학년 빈칸 채우기 문제/테스트 반환."""
    questions = [
        # 1단원: 자연수의 혼합 계산 (2문제)
        fb(
            id="e5-1-1-1-fb-001",
            concept_id="e5-1-1-1",
            category="computation",
            part="calc",
            difficulty=3,
            content="5 + 3 × 4 = [answer]",
            answer="17",
            explanation="곱셈을 먼저 계산: 5 + (3 × 4) = 5 + 12 = 17입니다.",
            points=10,
            accept_formats=["17"],
        ),
        fb(
            id="e5-1-1-1-fb-002",
            concept_id="e5-1-1-1",
            category="computation",
            part="calc",
            difficulty=5,
            content="72 ÷ 4 × 3 = [answer]",
            answer="54",
            explanation="좌결합성: 72 ÷ 4 = 18, 18 × 3 = 54입니다.",
            points=10,
            accept_formats=["54"],
        ),

        # 2단원: 약수와 배수 (2문제)
        fb(
            id="e5-1-2-1-fb-001",
            concept_id="e5-1-2-1",
            category="computation",
            part="calc",
            difficulty=4,
            content="12의 약수는 모두 [answer]개입니다.",
            answer="6",
            explanation="12의 약수: 1, 2, 3, 4, 6, 12로 총 6개입니다.",
            points=10,
            accept_formats=["6"],
        ),
        fb(
            id="e5-1-2-2-fb-001",
            concept_id="e5-1-2-2",
            category="computation",
            part="calc",
            difficulty=6,
            content="12와 18의 최대공약수는 [answer]입니다.",
            answer="6",
            explanation="거꾸로 나눗셈: 2)12 18 → 3)6 9 → 2 3. GCD = 2 × 3 = 6입니다.",
            points=10,
            accept_formats=["6"],
        ),

        # 3단원: 규칙과 대응 (2문제)
        fb(
            id="e5-1-3-1-fb-001",
            concept_id="e5-1-3-1",
            category="concept",
            part="algebra",
            difficulty=4,
            content="자전거가 5대 있을 때 바퀴는 모두 [answer]개입니다. (1대당 2개)",
            answer="10",
            explanation="바퀴 수 = 자전거 수 × 2 = 5 × 2 = 10개입니다.",
            points=10,
            accept_formats=["10"],
        ),
        fb(
            id="e5-1-3-2-fb-001",
            concept_id="e5-1-3-2",
            category="concept",
            part="algebra",
            difficulty=6,
            content="y = ○ × 3 + 1일 때, ○ = 4이면 y = [answer]입니다.",
            answer="13",
            explanation="y = 4 × 3 + 1 = 12 + 1 = 13입니다.",
            points=10,
            accept_formats=["13"],
        ),

        # 4단원: 약분과 통분 (2문제)
        fb(
            id="e5-1-4-1-fb-001",
            concept_id="e5-1-4-1",
            category="computation",
            part="calc",
            difficulty=4,
            content="6/9를 기약분수로 나타내면 [answer]입니다. (분수 형태로 입력)",
            answer="2/3",
            explanation="6과 9의 최대공약수는 3입니다. 6÷3 / 9÷3 = 2/3입니다.",
            points=10,
            accept_formats=["2/3"],
        ),
        fb(
            id="e5-1-4-2-fb-001",
            concept_id="e5-1-4-2",
            category="computation",
            part="calc",
            difficulty=5,
            content="1/2와 1/4를 통분하면 분모는 [answer]입니다.",
            answer="4",
            explanation="2와 4의 최소공배수는 4입니다. 1/2 = 2/4, 1/4 = 1/4입니다.",
            points=10,
            accept_formats=["4"],
        ),

        # 5단원: 분수의 덧셈과 뺄셈 (2문제)
        fb(
            id="e5-1-5-1-fb-001",
            concept_id="e5-1-5-1",
            category="computation",
            part="calc",
            difficulty=5,
            content="1/2 + 1/4 = [answer] (분수 형태로 입력)",
            answer="3/4",
            explanation="통분: 1/2 = 2/4, 2/4 + 1/4 = 3/4입니다.",
            points=10,
            accept_formats=["3/4"],
        ),
        fb(
            id="e5-1-5-1-fb-002",
            concept_id="e5-1-5-1",
            category="computation",
            part="calc",
            difficulty=7,
            content="5/6 - 1/3 = [answer] (분수 형태로 입력)",
            answer="1/2",
            explanation="통분: 1/3 = 2/6, 5/6 - 2/6 = 3/6 = 1/2입니다.",
            points=10,
            accept_formats=["1/2", "3/6"],
        ),

        # 6단원: 다각형의 둘레와 넓이 (2문제)
        fb(
            id="e5-1-6-1-fb-001",
            concept_id="e5-1-6-1",
            category="concept",
            part="geo",
            difficulty=5,
            content="밑변이 8cm, 높이가 5cm인 평행사변형의 넓이는 [answer]cm²입니다.",
            answer="40",
            explanation="평행사변형 넓이 = 밑변 × 높이 = 8 × 5 = 40cm²입니다.",
            points=10,
            accept_formats=["40"],
        ),
        fb(
            id="e5-1-6-1-fb-002",
            concept_id="e5-1-6-1",
            category="concept",
            part="geo",
            difficulty=6,
            content="밑변이 10cm, 높이가 6cm인 삼각형의 넓이는 [answer]cm²입니다.",
            answer="30",
            explanation="삼각형 넓이 = 밑변 × 높이 ÷ 2 = 10 × 6 ÷ 2 = 30cm²입니다.",
            points=10,
            accept_formats=["30"],
        ),

        # 7단원: 수의 범위와 어림하기 (2문제)
        fb(
            id="e5-2-1-1-fb-001",
            concept_id="e5-2-1-1",
            category="concept",
            part="calc",
            difficulty=4,
            content="10 이상 15 미만인 자연수는 모두 [answer]개입니다.",
            answer="5",
            explanation="10 이상(포함) 15 미만(불포함): 10, 11, 12, 13, 14로 총 5개입니다.",
            points=10,
            accept_formats=["5"],
        ),
        fb(
            id="e5-2-1-2-fb-001",
            concept_id="e5-2-1-2",
            category="concept",
            part="calc",
            difficulty=6,
            content="345를 십의 자리에서 반올림하면 [answer]입니다.",
            answer="300",
            explanation="십의 자리(4)가 5 미만이므로 버림합니다. 345 → 300입니다.",
            points=10,
            accept_formats=["300"],
        ),

        # 8단원: 분수의 곱셈 (2문제)
        fb(
            id="e5-2-2-2-fb-001",
            concept_id="e5-2-2-2",
            category="computation",
            part="calc",
            difficulty=5,
            content="1/2 × 1/3 = [answer] (분수 형태로 입력)",
            answer="1/6",
            explanation="(1×1) / (2×3) = 1/6입니다.",
            points=10,
            accept_formats=["1/6"],
        ),
        fb(
            id="e5-2-2-1-fb-001",
            concept_id="e5-2-2-1",
            category="computation",
            part="calc",
            difficulty=7,
            content="2/5 × 3 = [answer] (분수 형태로 입력)",
            answer="6/5",
            explanation="2/5 × 3/1 = 6/5입니다.",
            points=10,
            accept_formats=["6/5", "1.2"],
        ),

        # 9단원: 합동과 대칭 (2문제)
        fb(
            id="e5-2-5-1-fb-001",
            concept_id="e5-2-5-1",
            category="concept",
            part="geo",
            difficulty=5,
            content="직육면체의 면은 모두 [answer]개입니다.",
            answer="6",
            explanation="직육면체는 6개의 면으로 이루어져 있습니다.",
            points=10,
            accept_formats=["6"],
        ),
        fb(
            id="e5-2-3-2-fb-001",
            concept_id="e5-2-3-2",
            category="concept",
            part="geo",
            difficulty=6,
            content="선대칭도형을 대칭축으로 접으면 [answer]하게 겹칩니다. (완전/부분/전혀 중 선택)",
            answer="완전",
            explanation="선대칭도형은 대칭축을 따라 접으면 완전히 겹치는 도형입니다.",
            points=10,
            accept_formats=["완전", "완전히"],
        ),

        # 10단원: 소수의 곱셈 (2문제)
        fb(
            id="e5-2-4-1-fb-001",
            concept_id="e5-2-4-1",
            category="computation",
            part="calc",
            difficulty=5,
            content="0.4 × 5 = [answer]",
            answer="2",
            explanation="4 × 5 = 20, 소수점 1자리 → 2.0 = 2입니다.",
            points=10,
            accept_formats=["2", "2.0"],
        ),
        fb(
            id="e5-2-4-2-fb-001",
            concept_id="e5-2-4-2",
            category="computation",
            part="calc",
            difficulty=7,
            content="0.3 × 0.4 = [answer]",
            answer="0.12",
            explanation="3 × 4 = 12, 소수점 2자리 → 0.12입니다.",
            points=10,
            accept_formats=["0.12"],
        ),

        # 11단원: 직육면체 (2문제)
        fb(
            id="e5-2-5-1-fb-002",
            concept_id="e5-2-5-1",
            category="concept",
            part="geo",
            difficulty=4,
            content="직육면체의 꼭짓점은 모두 [answer]개입니다.",
            answer="8",
            explanation="직육면체는 8개의 꼭짓점으로 이루어져 있습니다. (면 6개, 모서리 12개)",
            points=10,
            accept_formats=["8"],
        ),
        fb(
            id="e5-2-5-1-fb-003",
            concept_id="e5-2-5-1",
            category="concept",
            part="geo",
            difficulty=6,
            content="직육면체의 모서리는 모두 [answer]개입니다.",
            answer="12",
            explanation="직육면체는 12개의 모서리로 이루어져 있습니다.",
            points=10,
            accept_formats=["12"],
        ),

        # 12단원: 평균과 가능성 (2문제)
        fb(
            id="e5-2-6-1-fb-001",
            concept_id="e5-2-6-1",
            category="concept",
            part="data",
            difficulty=5,
            content="5, 7, 9, 11의 평균은 [answer]입니다.",
            answer="8",
            explanation="평균 = (5 + 7 + 9 + 11) ÷ 4 = 32 ÷ 4 = 8입니다.",
            points=10,
            accept_formats=["8"],
        ),
        fb(
            id="e5-2-6-2-fb-001",
            concept_id="e5-2-6-2",
            category="concept",
            part="data",
            difficulty=7,
            content="동전을 던질 때 앞면이 나올 가능성을 수치로 표현하면 [answer]입니다. (분수 형태)",
            answer="1/2",
            explanation="동전은 앞면/뒷면 2가지 경우. 앞면 1가지 / 전체 2가지 = 1/2입니다.",
            points=10,
            accept_formats=["1/2", "0.5"],
        ),
    ]

    tests = [
        test(
            id="test-e5-fill-blank-all",
            title="초5 빈칸 채우기 종합 테스트",
            description="전 12단원 빈칸 채우기 (연산/개념/도형/자료)",
            grade="elementary_5",
            concept_ids=[
                "e5-1-1-1", "e5-1-1-2",
                "e5-1-2-1", "e5-1-2-2",
                "e5-1-3-1", "e5-1-3-2",
                "e5-1-4-1", "e5-1-4-2",
                "e5-1-5-1", "e5-1-5-2",
                "e5-1-6-1", "e5-1-6-2",
                "e5-2-1-1", "e5-2-1-2",
                "e5-2-2-1", "e5-2-2-2",
                "e5-2-3-1", "e5-2-3-2",
                "e5-2-4-1", "e5-2-4-2",
                "e5-2-5-1", "e5-2-5-2",
                "e5-2-6-1", "e5-2-6-2",
            ],
            question_ids=[
                "e5-1-1-1-fb-001", "e5-1-1-1-fb-002", "e5-1-2-1-fb-001", 
                "e5-1-2-2-fb-001", "e5-1-3-1-fb-001", "e5-1-3-2-fb-001", 
                "e5-1-4-1-fb-001", "e5-1-4-2-fb-001", "e5-1-5-1-fb-001", 
                "e5-1-5-1-fb-002", "e5-1-6-1-fb-001", "e5-1-6-1-fb-002", 
                "e5-2-1-1-fb-001", "e5-2-1-2-fb-001", "e5-2-2-2-fb-001", 
                "e5-2-2-1-fb-001", "e5-2-5-1-fb-001", "e5-2-3-2-fb-001", 
                "e5-2-4-1-fb-001", "e5-2-4-2-fb-001", "e5-2-5-1-fb-002", 
                "e5-2-5-1-fb-003", "e5-2-6-1-fb-001", "e5-2-6-2-fb-001",
            ],
            time_limit_minutes=30,
            use_question_pool=True,
            questions_per_attempt=12,
        ),
    ]

    return {"questions": questions, "tests": tests}
