# Schemas module

from .common import (
    ApiResponse,
    Difficulty,
    ErrorDetail,
    ErrorResponse,
    Grade,
    PaginatedResponse,
    QuestionType,
    UserRole,
)
from .auth import (
    LoginRequest,
    LoginResponse,
    LogoutRequest,
    LogoutResponse,
    RegisterResponse,
    RegisterStudentRequest,
    RegisterTeacherRequest,
    TokenRefreshRequest,
    TokenRefreshResponse,
    UserCreate,
    UserResponse,
    UserUpdate,
)
from .test import (
    AnswerLogResponse,
    AvailableTestResponse,
    CompleteTestResponse,
    ConceptCreate,
    ConceptResponse,
    GetAttemptResponse,
    QuestionCreate,
    QuestionOption,
    QuestionResponse,
    QuestionWithAnswer,
    StartTestResponse,
    SubmitAnswerRequest,
    SubmitAnswerResponse,
    TestAttemptResponse,
    TestCreate,
    TestResponse,
    TestUpdate,
    TestWithQuestionsResponse,
)
from .stats import (
    ClassDetailStats,
    ClassStats,
    ConceptDetailStat,
    ConceptStat,
    DailyActivity,
    DailyClassStat,
    DashboardAlert,
    DashboardStats,
    RecentTest,
    StudentDetailStats,
    StudentStats,
    StudentStatsSummary,
    TodayStats,
    TopStudent,
    WeekStats,
)

__all__ = [
    # common
    "ApiResponse",
    "Difficulty",
    "ErrorDetail",
    "ErrorResponse",
    "Grade",
    "PaginatedResponse",
    "QuestionType",
    "UserRole",
    # auth
    "LoginRequest",
    "LoginResponse",
    "LogoutRequest",
    "LogoutResponse",
    "RegisterResponse",
    "RegisterStudentRequest",
    "RegisterTeacherRequest",
    "TokenRefreshRequest",
    "TokenRefreshResponse",
    "UserCreate",
    "UserResponse",
    "UserUpdate",
    # test
    "AnswerLogResponse",
    "AvailableTestResponse",
    "CompleteTestResponse",
    "ConceptCreate",
    "ConceptResponse",
    "GetAttemptResponse",
    "QuestionCreate",
    "QuestionOption",
    "QuestionResponse",
    "QuestionWithAnswer",
    "StartTestResponse",
    "SubmitAnswerRequest",
    "SubmitAnswerResponse",
    "TestAttemptResponse",
    "TestCreate",
    "TestResponse",
    "TestUpdate",
    "TestWithQuestionsResponse",
    # stats
    "ClassDetailStats",
    "ClassStats",
    "ConceptDetailStat",
    "ConceptStat",
    "DailyActivity",
    "DailyClassStat",
    "DashboardAlert",
    "DashboardStats",
    "RecentTest",
    "StudentDetailStats",
    "StudentStats",
    "StudentStatsSummary",
    "TodayStats",
    "TopStudent",
    "WeekStats",
]
