"""초등 6학년 연산 문제 - 분수의 나눗셈, 소수의 나눗셈."""
from app.seeds._base import mc, concept


def get_concepts():
    """초등 6학년 연산 개념 반환."""
    return [
        concept(
            id="concept-e6-comp",
            name="분수·소수의 나눗셈",
            grade="elementary_6",
            category="computation",
            part="연산",
            description="분수의 나눗셈과 소수의 나눗셈을 다룹니다.",
        ),
    ]


def get_questions():
    """초등 6학년 연산 문제 반환."""
    return [
        # 분수의 나눗셈 (난이도 1-3)
        mc(
            id="e6-comp-001",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=1,
            content="1/2 ÷ 2를 계산하세요.",
            options=[
                ("1/4",),
                ("1",),
                ("2",),
                ("1/3",),
            ],
            correct="A",
            explanation="1/2 ÷ 2 = 1/2 × 1/2 = 1/4입니다.",
            points=10,
        ),
        mc(
            id="e6-comp-002",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=2,
            content="2/3 ÷ 1/3을 계산하세요.",
            options=[
                ("1",),
                ("2",),
                ("3",),
                ("2/9",),
            ],
            correct="B",
            explanation="2/3 ÷ 1/3 = 2/3 × 3/1 = 6/3 = 2입니다.",
            points=10,
        ),
        mc(
            id="e6-comp-003",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=3,
            content="3/4 ÷ 2/5를 계산하세요.",
            options=[
                ("15/8",),
                ("6/20",),
                ("5/8",),
                ("3/10",),
            ],
            correct="A",
            explanation="3/4 ÷ 2/5 = 3/4 × 5/2 = 15/8입니다.",
            points=10,
        ),
        # 분수 나눗셈 심화 (난이도 4-6)
        mc(
            id="e6-comp-004",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=4,
            content="5/6 ÷ 1/2를 기약분수로 나타내세요.",
            options=[
                ("5/3",),
                ("5/12",),
                ("10/6",),
                ("1/3",),
            ],
            correct="A",
            explanation="5/6 ÷ 1/2 = 5/6 × 2/1 = 10/6 = 5/3입니다.",
            points=10,
        ),
        mc(
            id="e6-comp-005",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=5,
            content="4 ÷ 2/3를 계산하면?",
            options=[
                ("6",),
                ("8/3",),
                ("2/3",),
                ("12",),
            ],
            correct="A",
            explanation="4 ÷ 2/3 = 4 × 3/2 = 12/2 = 6입니다.",
            points=10,
        ),
        mc(
            id="e6-comp-006",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=6,
            content="7/8 ÷ 3/4를 계산하세요.",
            options=[
                ("7/6",),
                ("21/32",),
                ("28/24",),
                ("3/2",),
            ],
            correct="A",
            explanation="7/8 ÷ 3/4 = 7/8 × 4/3 = 28/24 = 7/6입니다.",
            points=10,
        ),
        # 소수의 나눗셈 (난이도 7-10)
        mc(
            id="e6-comp-007",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=7,
            content="2.4 ÷ 0.6을 계산하세요.",
            options=[
                ("4",),
                ("0.4",),
                ("40",),
                ("0.04",),
            ],
            correct="A",
            explanation="2.4 ÷ 0.6 = 24 ÷ 6 = 4입니다.",
            points=10,
        ),
        mc(
            id="e6-comp-008",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=8,
            content="3.6 ÷ 0.4를 계산하면?",
            options=[
                ("9",),
                ("0.9",),
                ("90",),
                ("0.09",),
            ],
            correct="A",
            explanation="3.6 ÷ 0.4 = 36 ÷ 4 = 9입니다.",
            points=10,
        ),
        mc(
            id="e6-comp-009",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=9,
            content="1.5 ÷ 0.25를 계산하세요.",
            options=[
                ("6",),
                ("0.6",),
                ("60",),
                ("0.06",),
            ],
            correct="A",
            explanation="1.5 ÷ 0.25 = 150 ÷ 25 = 6입니다.",
            points=10,
        ),
        mc(
            id="e6-comp-010",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=10,
            content="4.8 ÷ 1.6을 계산하세요.",
            options=[
                ("3",),
                ("0.3",),
                ("30",),
                ("0.03",),
            ],
            correct="A",
            explanation="4.8 ÷ 1.6 = 48 ÷ 16 = 3입니다.",
            points=10,
        ),
        # 추가 문제 (난이도 다양화)
        mc(
            id="e6-comp-011",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=3,
            content="1 ÷ 1/4를 계산하면?",
            options=[
                ("4",),
                ("1/4",),
                ("2",),
                ("1/2",),
            ],
            correct="A",
            explanation="1 ÷ 1/4 = 1 × 4/1 = 4입니다.",
            points=10,
        ),
        mc(
            id="e6-comp-012",
            concept_id="concept-e6-comp",
            category="computation",
            part="연산",
            difficulty=7,
            content="0.8 ÷ 0.2를 계산하세요.",
            options=[
                ("4",),
                ("0.4",),
                ("40",),
                ("0.16",),
            ],
            correct="A",
            explanation="0.8 ÷ 0.2 = 8 ÷ 2 = 4입니다.",
            points=10,
        ),
    ]
