"""초등 6학년 연산 개념 및 문제."""

from .._base import concept, mc


def get_concepts() -> list[dict]:
    """연산 개념 5개 반환."""
    return [
        concept(
            id="concept-e6-frac-div1",
            name="분수의 나눗셈 (자연수÷자연수, 분수÷자연수)",
            grade="elementary_6",
            category="computation",
            part="calc",
            description="나눗셈의 몫을 분수로 표현하고, 분수를 자연수로 나누는 연산 원리 이해",
        ),
        concept(
            id="concept-e6-dec-div1",
            name="소수의 나눗셈 (소수÷자연수)",
            grade="elementary_6",
            category="computation",
            part="calc",
            description="소수를 자연수로 나누는 연산, 몫의 소수점 위치와 중간 0 처리",
        ),
        concept(
            id="concept-e6-ratio",
            name="비와 비율",
            grade="elementary_6",
            category="computation",
            part="calc",
            description="비의 구조 이해, 기준량 찾기, 비율과 백분율로 표현",
        ),
        concept(
            id="concept-e6-frac-div2",
            name="분수의 나눗셈 (분수÷분수)",
            grade="elementary_6",
            category="computation",
            part="calc",
            description="통분과 역수를 이용한 분수 나눗셈, 대분수 계산",
        ),
        concept(
            id="concept-e6-dec-div2",
            name="소수의 나눗셈 (소수÷소수)",
            grade="elementary_6",
            category="computation",
            part="calc",
            description="소수점 이동의 동치성, 반올림 조건 구분",
        ),
    ]


def get_questions() -> list[dict]:
    """연산 문제 15개 반환 (단원당 3개)."""
    return [
        # 1학기 1단원: 분수의 나눗셈1 (e6-comp-001 ~ 003)
        mc(
            id="e6-comp-001",
            concept_id="concept-e6-frac-div1",
            category="computation",
            part="calc",
            difficulty=3,
            content="2m 길이의 끈을 5등분하려고 합니다. 한 도막의 길이는 몇 m입니까?",
            options=[
                ("5/2 m", "5/2 m"),
                ("2/5 m", "2/5 m"),
                ("2/3 m", "2/3 m"),
                ("3/5 m", "3/5 m"),
            ],
            correct="2",
            explanation="2m를 5등분 → 2÷5 = 2/5m입니다. '작은 수÷큰 수' 상황에서 순서를 뒤바꾸는 오개념에 주의하세요. 정답은 2/5m입니다.",
        ),
        mc(
            id="e6-comp-002",
            concept_id="concept-e6-frac-div1",
            category="computation",
            part="calc",
            difficulty=5,
            content="3/4 ÷ 2를 계산하면?",
            options=[
                ("3/8", "3/8"),
                ("3/2", "3/2"),
                ("6/4", "6/4"),
                ("4/6", "4/6"),
            ],
            correct="1",
            explanation="분수÷자연수는 분수 × (1/자연수)로 계산합니다. 3/4 ÷ 2 = 3/4 × 1/2 = 3/8입니다.",
        ),
        mc(
            id="e6-comp-003",
            concept_id="concept-e6-frac-div1",
            category="computation",
            part="calc",
            difficulty=4,
            content="3L의 우유를 4명이 똑같이 나누어 마시려 합니다. 한 명이 마시게 되는 우유의 양을 식으로 나타낸 것은?",
            options=[
                ("4 ÷ 3", "4 ÷ 3"),
                ("3 ÷ 4", "3 ÷ 4"),
                ("3 × 4", "3 × 4"),
                ("4 - 3", "4 - 3"),
            ],
            correct="2",
            explanation="3L를 4명이 나눔 → 3÷4입니다. 숫자의 크기가 아니라 '전체를 인원수로 나눈다'는 의미에 집중하세요.",
        ),
        # 1학기 3단원: 소수의 나눗셈1 (e6-comp-004 ~ 006)
        mc(
            id="e6-comp-004",
            concept_id="concept-e6-dec-div1",
            category="computation",
            part="calc",
            difficulty=6,
            content="6.12 ÷ 3을 계산하면?",
            options=[
                ("2.4", "2.4"),
                ("2.04", "2.04"),
                ("20.4", "20.4"),
                ("0.204", "0.204"),
            ],
            correct="2",
            explanation="612 ÷ 3 = 204이므로, 6.12 ÷ 3 = 2.04입니다. 몫의 중간에 0이 들어가는 것을 놓치지 마세요.",
        ),
        mc(
            id="e6-comp-005",
            concept_id="concept-e6-dec-div1",
            category="computation",
            part="calc",
            difficulty=5,
            content="8.32 ÷ 4를 계산하면?",
            options=[
                ("2.8", "2.8"),
                ("2.08", "2.08"),
                ("20.8", "20.8"),
                ("2.008", "2.008"),
            ],
            correct="2",
            explanation="832 ÷ 4 = 208이므로, 8.32 ÷ 4 = 2.08입니다. 소수점 위치를 정확하게 유지하세요.",
        ),
        mc(
            id="e6-comp-006",
            concept_id="concept-e6-dec-div1",
            category="computation",
            part="calc",
            difficulty=4,
            content="24.8 ÷ 4를 계산하면?",
            options=[
                ("6.2", "6.2"),
                ("62", "62"),
                ("0.62", "0.62"),
                ("6.02", "6.02"),
            ],
            correct="1",
            explanation="248 ÷ 4 = 62이므로, 24.8 ÷ 4 = 6.2입니다. 피제수의 소수점 위치를 그대로 올려 찍습니다.",
        ),
        # 1학기 4단원: 비와 비율 (e6-comp-007 ~ 009)
        mc(
            id="e6-comp-007",
            concept_id="concept-e6-ratio",
            category="computation",
            part="calc",
            difficulty=8,
            content="물 100g에 소금 25g을 녹인 소금물의 진하기(농도)는 몇 %입니까?",
            options=[
                ("25%", "25%"),
                ("20%", "20%"),
                ("80%", "80%"),
                ("125%", "125%"),
            ],
            correct="2",
            explanation="소금물 농도 = (소금 무게)/(전체 무게) × 100입니다. 전체 = 소금 + 물 = 25 + 100 = 125g이므로, 25/125 × 100 = 20%입니다. 분모를 '물'로 잡는 오개념에 주의하세요.",
        ),
        mc(
            id="e6-comp-008",
            concept_id="concept-e6-ratio",
            category="computation",
            part="calc",
            difficulty=7,
            content="사과가 3개, 배가 4개 있습니다. 배의 수에 대한 사과의 수의 비는?",
            options=[
                ("3 : 4", "3 : 4"),
                ("4 : 3", "4 : 3"),
                ("3 : 7", "3 : 7"),
                ("4 : 7", "4 : 7"),
            ],
            correct="1",
            explanation="'배에 대한 사과'이므로 기준량은 배(4개)입니다. 비는 사과:배 = 3:4입니다. 문장 어순과 비의 순서가 반대임에 주의하세요.",
        ),
        mc(
            id="e6-comp-009",
            concept_id="concept-e6-ratio",
            category="computation",
            part="calc",
            difficulty=6,
            content="6 : 8과 같은 비는?",
            options=[
                ("12 : 14", "12 : 14"),
                ("3 : 4", "3 : 4"),
                ("8 : 6", "8 : 6"),
                ("6 : 10", "6 : 10"),
            ],
            correct="2",
            explanation="비의 성질에 따라 전항과 후항에 같은 수를 곱하거나 나누어도 비의 값은 같습니다. 6:8 = 3:4입니다.",
        ),
        # 2학기 1단원: 분수의 나눗셈2 (e6-comp-010 ~ 012)
        mc(
            id="e6-comp-010",
            concept_id="concept-e6-frac-div2",
            category="computation",
            part="calc",
            difficulty=7,
            content="2 1/2 ÷ 1 1/3을 계산하면?",
            options=[
                ("15/8", "15/8"),
                ("5/3", "5/3"),
                ("3/2", "3/2"),
                ("8/15", "8/15"),
            ],
            correct="1",
            explanation="대분수는 가분수로 변환 후 계산합니다. 2 1/2 = 5/2, 1 1/3 = 4/3이므로, 5/2 ÷ 4/3 = 5/2 × 3/4 = 15/8입니다.",
        ),
        mc(
            id="e6-comp-011",
            concept_id="concept-e6-frac-div2",
            category="computation",
            part="calc",
            difficulty=6,
            content="3/4 ÷ 2/5를 계산하면?",
            options=[
                ("6/20", "6/20"),
                ("15/8", "15/8"),
                ("8/15", "8/15"),
                ("5/6", "5/6"),
            ],
            correct="2",
            explanation="분수 나눗셈은 나누는 수의 역수를 곱합니다. 3/4 ÷ 2/5 = 3/4 × 5/2 = 15/8입니다.",
        ),
        mc(
            id="e6-comp-012",
            concept_id="concept-e6-frac-div2",
            category="computation",
            part="calc",
            difficulty=5,
            content="5/6 ÷ 5/12를 계산하면?",
            options=[
                ("1/2", "1/2"),
                ("2", "2"),
                ("25/72", "25/72"),
                ("12/6", "12/6"),
            ],
            correct="2",
            explanation="5/6 ÷ 5/12 = 5/6 × 12/5 = 60/30 = 2입니다. 통분 방법으로도 계산 가능: 분모를 12로 통일하면 10/12 ÷ 5/12 = 10÷5 = 2입니다.",
        ),
        # 2학기 2단원: 소수의 나눗셈2 (e6-comp-013 ~ 015)
        mc(
            id="e6-comp-013",
            concept_id="concept-e6-dec-div2",
            category="computation",
            part="calc",
            difficulty=7,
            content="7.8 ÷ 1.2를 계산하면?",
            options=[
                ("6.5", "6.5"),
                ("65", "65"),
                ("0.65", "0.65"),
                ("6.05", "6.05"),
            ],
            correct="1",
            explanation="나누는 수와 나누어지는 수에 10을 곱하면 78 ÷ 12 = 6.5입니다. 소수점 이동의 동치성을 활용하세요.",
        ),
        mc(
            id="e6-comp-014",
            concept_id="concept-e6-dec-div2",
            category="computation",
            part="calc",
            difficulty=8,
            content="5 ÷ 0.8을 '소수 둘째 자리까지' 구하시오.",
            options=[
                ("6.2", "6.2"),
                ("6.25", "6.25"),
                ("6.3", "6.3"),
                ("62.5", "62.5"),
            ],
            correct="2",
            explanation="50 ÷ 8 = 6.25입니다. '소수 둘째 자리까지 구하시오'는 둘째 자리까지 표기하라는 의미입니다. '소수 둘째 자리에서 반올림'과 혼동하지 마세요.",
        ),
        mc(
            id="e6-comp-015",
            concept_id="concept-e6-dec-div2",
            category="computation",
            part="calc",
            difficulty=9,
            content="8.3 ÷ 2.4를 '소수 첫째 자리에서 반올림'하여 구하시오.",
            options=[
                ("3", "3"),
                ("3.5", "3.5"),
                ("4", "4"),
                ("3.4", "3.4"),
            ],
            correct="1",
            explanation="83 ÷ 24 = 3.458...이므로 소수 첫째 자리에서 반올림하면 3입니다. 반올림 조건을 정확히 읽어야 합니다.",
        ),
    ]
