"""초등 6학년 개념 문제."""

from .._base import concept, mc


def get_concepts() -> list[dict]:
    """개념 7개 반환."""
    return [
        concept(
            id="concept-e6-prism-pyramid",
            name="각기둥과 각뿔",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="각기둥과 각뿔의 구성 요소, 밑면과 높이 구별, 전개도",
        ),
        concept(
            id="concept-e6-graphs",
            name="여러 가지 그래프",
            grade="elementary_6",
            category="concept",
            part="data",
            description="띠그래프와 원그래프, 비율 해석과 중심각 계산",
        ),
        concept(
            id="concept-e6-volume",
            name="직육면체의 부피와 겉넓이",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="부피와 겉넓이의 개념, 단위 변환, 부피-겉넓이 관계",
        ),
        concept(
            id="concept-e6-spatial",
            name="공간과 입체",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="투영도 해석, 쌓기나무 최대/최소 개수 추론",
        ),
        concept(
            id="concept-e6-proportion",
            name="비례식과 비례배분",
            grade="elementary_6",
            category="concept",
            part="algebra",
            description="비례식의 성질, 외항과 내항, 비례배분",
        ),
        concept(
            id="concept-e6-circle-area",
            name="원의 넓이",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="원주율, 원의 넓이 공식, 반지름과 넓이의 관계",
        ),
        concept(
            id="concept-e6-solids",
            name="원기둥, 원뿔, 구",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="회전체의 이해, 단면의 종류, 높이와 모선 구별",
        ),
    ]


def get_questions() -> list[dict]:
    """개념 문제 21개 반환 (단원당 3개)."""
    return [
        # 1학기 2단원: 각기둥과 각뿔 (e6-conc-001 ~ 003)
        mc(
            id="e6-conc-001",
            concept_id="concept-e6-prism-pyramid",
            category="concept",
            part="geo",
            difficulty=4,
            content="다음 중 삼각기둥을 옆으로 눕혔을 때, 밑면을 찾는 방법으로 옳은 것은?",
            options=[
                ("가장 아래에 있는 면", "가장 아래에 있는 면"),
                ("합동인 두 면", "합동인 두 면"),
                ("가장 넓은 면", "가장 넓은 면"),
                ("직사각형 모양의 면", "직사각형 모양의 면"),
            ],
            correct="2",
            explanation="각기둥의 밑면은 '합동인 두 면'입니다. 눕혀도 밑면은 바뀌지 않습니다. '밑면 = 바닥면' 오개념에 주의하세요.",
        ),
        mc(
            id="e6-conc-002",
            concept_id="concept-e6-prism-pyramid",
            category="concept",
            part="geo",
            difficulty=6,
            content="사각뿔에서 꼭짓점에서 밑면까지의 거리를 무엇이라 합니까?",
            options=[
                ("모서리", "모서리"),
                ("모선", "모선"),
                ("높이", "높이"),
                ("옆면", "옆면"),
            ],
            correct="3",
            explanation="각뿔의 높이는 꼭짓점에서 밑면에 내린 수선의 길이입니다. 옆 모서리(모선)와 혼동하지 마세요.",
        ),
        mc(
            id="e6-conc-003",
            concept_id="concept-e6-prism-pyramid",
            category="concept",
            part="geo",
            difficulty=5,
            content="오각기둥의 모서리는 모두 몇 개입니까?",
            options=[
                ("10개", "10개"),
                ("15개", "15개"),
                ("20개", "20개"),
                ("25개", "25개"),
            ],
            correct="2",
            explanation="각기둥의 모서리 = 밑면의 변 × 3입니다. 오각기둥은 5 × 3 = 15개입니다.",
        ),
        # 1학기 5단원: 여러 가지 그래프 (e6-conc-004 ~ 006)
        mc(
            id="e6-conc-004",
            concept_id="concept-e6-graphs",
            category="concept",
            part="data",
            difficulty=7,
            content="원그래프에서 30%를 나타내는 부분의 중심각은 몇 도입니까?",
            options=[
                ("30°", "30°"),
                ("60°", "60°"),
                ("90°", "90°"),
                ("108°", "108°"),
            ],
            correct="4",
            explanation="중심각 = 360° × 비율입니다. 360° × 0.3 = 108°입니다. 30%를 30°로 착각하는 오개념에 주의하세요.",
        ),
        mc(
            id="e6-conc-005",
            concept_id="concept-e6-graphs",
            category="concept",
            part="data",
            difficulty=5,
            content="원그래프에서 25%를 나타내는 부분의 중심각은 몇 도입니까?",
            options=[
                ("25°", "25°"),
                ("90°", "90°"),
                ("100°", "100°"),
                ("125°", "125°"),
            ],
            correct="2",
            explanation="360° × 0.25 = 90°입니다.",
        ),
        mc(
            id="e6-conc-006",
            concept_id="concept-e6-graphs",
            category="concept",
            part="data",
            difficulty=6,
            content="띠그래프와 원그래프의 공통점은 무엇입니까?",
            options=[
                ("전체에 대한 각 부분의 비율을 나타낸다", "전체에 대한 각 부분의 비율을 나타낸다"),
                ("정확한 수량을 알 수 있다", "정확한 수량을 알 수 있다"),
                ("시간에 따른 변화를 알 수 있다", "시간에 따른 변화를 알 수 있다"),
                ("두 변수의 관계를 알 수 있다", "두 변수의 관계를 알 수 있다"),
            ],
            correct="1",
            explanation="띠그래프와 원그래프는 모두 전체에 대한 각 부분의 비율을 시각화하는 그래프입니다.",
        ),
        # 1학기 6단원: 직육면체의 부피와 겉넓이 (e6-conc-007 ~ 009)
        mc(
            id="e6-conc-007",
            concept_id="concept-e6-volume",
            category="concept",
            part="geo",
            difficulty=8,
            content="1m³는 몇 cm³입니까?",
            options=[
                ("100 cm³", "100 cm³"),
                ("1,000 cm³", "1,000 cm³"),
                ("10,000 cm³", "10,000 cm³"),
                ("1,000,000 cm³", "1,000,000 cm³"),
            ],
            correct="4",
            explanation="1m = 100cm이므로, 1m³ = 100cm × 100cm × 100cm = 1,000,000cm³입니다. 단위 변환 시 세제곱에 주의하세요.",
        ),
        mc(
            id="e6-conc-008",
            concept_id="concept-e6-volume",
            category="concept",
            part="geo",
            difficulty=7,
            content="직육면체의 부피를 구하는 공식은?",
            options=[
                ("가로 + 세로 + 높이", "가로 + 세로 + 높이"),
                ("가로 × 세로", "가로 × 세로"),
                ("가로 × 세로 × 높이", "가로 × 세로 × 높이"),
                ("2 × (가로 + 세로 + 높이)", "2 × (가로 + 세로 + 높이)"),
            ],
            correct="3",
            explanation="직육면체의 부피 = 밑면의 넓이 × 높이 = 가로 × 세로 × 높이입니다.",
        ),
        mc(
            id="e6-conc-009",
            concept_id="concept-e6-volume",
            category="concept",
            part="geo",
            difficulty=9,
            content="쌓기나무가 12개로 같은 두 입체도형이 있습니다. 이 두 도형의 겉넓이는?",
            options=[
                ("항상 같다", "항상 같다"),
                ("항상 다르다", "항상 다르다"),
                ("같을 수도, 다를 수도 있다", "같을 수도, 다를 수도 있다"),
                ("부피가 같으면 겉넓이도 항상 같다", "부피가 같으면 겉넓이도 항상 같다"),
            ],
            correct="3",
            explanation="부피가 같아도 쌓는 방식에 따라 겉넓이는 달라질 수 있습니다. '부피 같으면 겉넓이도 같다'는 오개념입니다.",
        ),
        # 2학기 3단원: 공간과 입체 (e6-conc-010 ~ 012)
        mc(
            id="e6-conc-010",
            concept_id="concept-e6-spatial",
            category="concept",
            part="geo",
            difficulty=8,
            content="위에서 본 모양이 2×2 정사각형이고, 앞에서 본 모양이 높이 3인 직사각형일 때, 쌓기나무의 최소 개수는?",
            options=[
                ("4개", "4개"),
                ("8개", "8개"),
                ("12개", "12개"),
                ("6개", "6개"),
            ],
            correct="1",
            explanation="최소 개수는 위에서 본 모양의 칸 수와 같습니다. 2×2 = 4개입니다. 높이 조건은 최소 개수에 영향을 주지 않습니다.",
        ),
        mc(
            id="e6-conc-011",
            concept_id="concept-e6-spatial",
            category="concept",
            part="geo",
            difficulty=9,
            content="위에서 본 모양, 앞에서 본 모양, 옆에서 본 모양만으로 쌓기나무의 전체 모양을 정확히 알 수 있습니까?",
            options=[
                ("항상 알 수 있다", "항상 알 수 있다"),
                ("항상 알 수 없다", "항상 알 수 없다"),
                ("경우에 따라 다르다", "경우에 따라 다르다"),
                ("위와 앞만 있으면 알 수 있다", "위와 앞만 있으면 알 수 있다"),
            ],
            correct="3",
            explanation="투영도만으로는 전체 모양이 하나로 결정되지 않을 수 있습니다. 여러 배치가 가능한 경우가 있습니다.",
        ),
        mc(
            id="e6-conc-012",
            concept_id="concept-e6-spatial",
            category="concept",
            part="geo",
            difficulty=7,
            content="쌓기나무로 만든 입체도형을 앞에서 봤을 때 고려해야 할 것은?",
            options=[
                ("가로와 높이만 보인다", "가로와 높이만 보인다"),
                ("깊이 정보도 포함된다", "깊이 정보도 포함된다"),
                ("옆면도 함께 보인다", "옆면도 함께 보인다"),
                ("위에서 본 모양과 같다", "위에서 본 모양과 같다"),
            ],
            correct="1",
            explanation="앞에서 본 모양은 가로와 높이만 나타나고 깊이는 나타나지 않습니다.",
        ),
        # 2학기 4단원: 비례식과 비례배분 (e6-conc-013 ~ 015)
        mc(
            id="e6-conc-013",
            concept_id="concept-e6-proportion",
            category="concept",
            part="algebra",
            difficulty=8,
            content="비례식 2 : 3 = 4 : ☐에서 ☐에 알맞은 수는?",
            options=[
                ("5", "5"),
                ("6", "6"),
                ("7", "7"),
                ("8", "8"),
            ],
            correct="2",
            explanation="외항의 곱 = 내항의 곱이므로, 2 × ☐ = 3 × 4 = 12, ☐ = 6입니다. 덧셈적 사고(2→4는 +2이므로 3→5)는 오류입니다.",
        ),
        mc(
            id="e6-conc-014",
            concept_id="concept-e6-proportion",
            category="concept",
            part="algebra",
            difficulty=9,
            content="24를 2 : 4의 비로 비례배분하면 작은 쪽은?",
            options=[
                ("6", "6"),
                ("8", "8"),
                ("12", "12"),
                ("16", "16"),
            ],
            correct="2",
            explanation="비의 합 = 2 + 4 = 6입니다. 작은 쪽 = 24 × 2/6 = 8입니다. 분모를 4로 잡는 오류에 주의하세요.",
        ),
        mc(
            id="e6-conc-015",
            concept_id="concept-e6-proportion",
            category="concept",
            part="algebra",
            difficulty=7,
            content="비례식 a : b = c : d에서 외항은 무엇입니까?",
            options=[
                ("a와 b", "a와 b"),
                ("b와 c", "b와 c"),
                ("a와 d", "a와 d"),
                ("c와 d", "c와 d"),
            ],
            correct="3",
            explanation="비례식에서 외항은 양 끝의 항인 a와 d입니다. 내항은 가운데 두 항인 b와 c입니다.",
        ),
        # 2학기 5단원: 원의 넓이 (e6-conc-016 ~ 018)
        mc(
            id="e6-conc-016",
            concept_id="concept-e6-circle-area",
            category="concept",
            part="geo",
            difficulty=9,
            content="반지름이 2배가 되면 원의 넓이는 몇 배가 됩니까?",
            options=[
                ("2배", "2배"),
                ("3배", "3배"),
                ("4배", "4배"),
                ("8배", "8배"),
            ],
            correct="3",
            explanation="원의 넓이 = πr²이므로, 반지름이 2배가 되면 넓이는 2² = 4배가 됩니다.",
        ),
        mc(
            id="e6-conc-017",
            concept_id="concept-e6-circle-area",
            category="concept",
            part="geo",
            difficulty=6,
            content="원의 넓이를 구하는 공식에서 r은 무엇을 의미합니까?",
            options=[
                ("원주", "원주"),
                ("지름", "지름"),
                ("반지름", "반지름"),
                ("원주율", "원주율"),
            ],
            correct="3",
            explanation="원의 넓이 = πr²에서 r은 반지름입니다.",
        ),
        mc(
            id="e6-conc-018",
            concept_id="concept-e6-circle-area",
            category="concept",
            part="geo",
            difficulty=8,
            content="반원의 둘레를 구할 때 포함해야 하는 것은?",
            options=[
                ("곡선 부분만", "곡선 부분만"),
                ("곡선 부분 + 지름", "곡선 부분 + 지름"),
                ("곡선 부분 + 반지름 2개", "곡선 부분 + 반지름 2개"),
                ("원주 전체", "원주 전체"),
            ],
            correct="2",
            explanation="반원의 둘레 = (원주의 반) + 지름 = πr + 2r입니다. 곡선 부분만 계산하는 오류에 주의하세요.",
        ),
        # 2학기 6단원: 원기둥, 원뿔, 구 (e6-conc-019 ~ 021)
        mc(
            id="e6-conc-019",
            concept_id="concept-e6-solids",
            category="concept",
            part="geo",
            difficulty=7,
            content="구를 완벽하게 펼친 전개도를 그릴 수 있습니까?",
            options=[
                ("가능하다", "가능하다"),
                ("불가능하다", "불가능하다"),
                ("특정 방법으로만 가능하다", "특정 방법으로만 가능하다"),
                ("작은 구만 가능하다", "작은 구만 가능하다"),
            ],
            correct="2",
            explanation="구는 곡면이므로 평면으로 완벽하게 펼칠 수 없습니다. 지구본을 종이 지도로 그릴 때 왜곡이 생기는 것과 같은 원리입니다.",
        ),
        mc(
            id="e6-conc-020",
            concept_id="concept-e6-solids",
            category="concept",
            part="geo",
            difficulty=8,
            content="원뿔에서 꼭짓점에서 밑면의 원까지 수직으로 내린 선분은 무엇입니까?",
            options=[
                ("모선", "모선"),
                ("높이", "높이"),
                ("반지름", "반지름"),
                ("지름", "지름"),
            ],
            correct="2",
            explanation="원뿔의 높이는 꼭짓점에서 밑면에 수직으로 내린 선분입니다. 옆면을 따라 내려가는 모선과 혼동하지 마세요.",
        ),
        mc(
            id="e6-conc-021",
            concept_id="concept-e6-solids",
            category="concept",
            part="geo",
            difficulty=6,
            content="원기둥을 회전축에 수직으로 자른 단면의 모양은?",
            options=[
                ("직사각형", "직사각형"),
                ("원", "원"),
                ("타원", "타원"),
                ("삼각형", "삼각형"),
            ],
            correct="2",
            explanation="원기둥을 회전축에 수직으로 자르면 단면은 원입니다.",
        ),
    ]
