"""초등 6학년 개념 문제 - 비와 비율, 비례식과 비례배분, 원의 넓이."""
from app.seeds._base import mc, concept


def get_concepts():
    """초등 6학년 개념 반환."""
    return [
        concept(
            id="concept-e6-conc",
            name="비와 비율, 비례식, 원의 넓이",
            grade="elementary_6",
            category="concept",
            part="개념",
            description="비와 비율의 의미, 비례식의 성질과 비례배분, 원의 넓이를 다룹니다.",
        ),
    ]


def get_questions():
    """초등 6학년 개념 문제 반환."""
    return [
        # 비와 비율 (난이도 1-3)
        mc(
            id="e6-conc-001",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=1,
            content="비율은 무엇을 무엇으로 나눈 것입니까?",
            options=[
                ("기준량을 비교하는 양으로 나눈 것",),
                ("비교하는 양을 기준량으로 나눈 것",),
                ("두 양을 더한 것",),
                ("두 양을 곱한 것",),
            ],
            correct="B",
            explanation="비율 = 비교하는 양 ÷ 기준량입니다.",
            points=10,
        ),
        mc(
            id="e6-conc-002",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=2,
            content="남학생이 12명, 여학생이 18명일 때, 남학생 수와 여학생 수의 비를 가장 간단한 자연수의 비로 나타내면?",
            options=[
                ("12 : 18",),
                ("6 : 9",),
                ("2 : 3",),
                ("3 : 2",),
            ],
            correct="C",
            explanation="12 : 18 = 2 : 3입니다.",
            points=10,
        ),
        mc(
            id="e6-conc-003",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=3,
            content="기준량이 20이고 비율이 0.6일 때 비교하는 양은?",
            options=[
                ("10",),
                ("12",),
                ("15",),
                ("18",),
            ],
            correct="B",
            explanation="비교하는 양 = 기준량 × 비율 = 20 × 0.6 = 12입니다.",
            points=10,
        ),
        # 비례식 (난이도 4-6)
        mc(
            id="e6-conc-004",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=4,
            content="비례식 3 : 5 = 6 : □에서 □에 알맞은 수는?",
            options=[
                ("8",),
                ("9",),
                ("10",),
                ("12",),
            ],
            correct="C",
            explanation="3 × □ = 5 × 6이므로, 3 × □ = 30, □ = 10입니다.",
            points=10,
        ),
        mc(
            id="e6-conc-005",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=5,
            content="비례식에서 외항의 곱과 내항의 곱은 어떤 관계입니까?",
            options=[
                ("외항의 곱이 더 크다",),
                ("내항의 곱이 더 크다",),
                ("같다",),
                ("관계가 없다",),
            ],
            correct="C",
            explanation="비례식에서 외항의 곱과 내항의 곱은 항상 같습니다.",
            points=10,
        ),
        mc(
            id="e6-conc-006",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=6,
            content="24를 2 : 4의 비로 나누면 작은 쪽은?",
            options=[
                ("6",),
                ("8",),
                ("12",),
                ("16",),
            ],
            correct="B",
            explanation="2 + 4 = 6, 24 × 2/6 = 8, 24 × 4/6 = 16. 작은 쪽은 8입니다.",
            points=10,
        ),
        # 원의 넓이 (난이도 7-10)
        mc(
            id="e6-conc-007",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=7,
            content="원의 넓이를 구하는 공식은? (원주율을 π라 할 때)",
            options=[
                ("π × r",),
                ("π × r²",),
                ("2 × π × r",),
                ("π × d",),
            ],
            correct="B",
            explanation="원의 넓이 = π × 반지름 × 반지름 = πr²입니다.",
            points=10,
        ),
        mc(
            id="e6-conc-008",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=8,
            content="반지름이 5cm인 원의 넓이는? (π = 3.14로 계산)",
            options=[
                ("15.7 cm²",),
                ("31.4 cm²",),
                ("78.5 cm²",),
                ("157 cm²",),
            ],
            correct="C",
            explanation="원의 넓이 = 3.14 × 5 × 5 = 78.5 cm²입니다.",
            points=10,
        ),
        mc(
            id="e6-conc-009",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=9,
            content="지름이 10cm인 원의 넓이는? (π = 3.14로 계산)",
            options=[
                ("31.4 cm²",),
                ("78.5 cm²",),
                ("100 cm²",),
                ("314 cm²",),
            ],
            correct="B",
            explanation="반지름 = 10 ÷ 2 = 5 cm, 원의 넓이 = 3.14 × 5 × 5 = 78.5 cm²입니다.",
            points=10,
        ),
        mc(
            id="e6-conc-010",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=10,
            content="반지름이 6cm인 원의 넓이는? (π = 3으로 계산)",
            options=[
                ("36 cm²",),
                ("72 cm²",),
                ("108 cm²",),
                ("144 cm²",),
            ],
            correct="C",
            explanation="원의 넓이 = 3 × 6 × 6 = 108 cm²입니다.",
            points=10,
        ),
        # 추가 문제
        mc(
            id="e6-conc-011",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=4,
            content="48을 3 : 5로 비례배분하면 큰 쪽은?",
            options=[
                ("18",),
                ("24",),
                ("30",),
                ("32",),
            ],
            correct="C",
            explanation="3 + 5 = 8, 48 × 5/8 = 30입니다.",
            points=10,
        ),
        mc(
            id="e6-conc-012",
            concept_id="concept-e6-conc",
            category="concept",
            part="개념",
            difficulty=2,
            content="5 : 3 = 15 : 9가 비례식인 이유는?",
            options=[
                ("외항의 곱이 내항의 곱보다 크기 때문",),
                ("외항의 곱과 내항의 곱이 같기 때문",),
                ("모든 수가 3의 배수이기 때문",),
                ("전항과 후항이 같기 때문",),
            ],
            correct="B",
            explanation="5 × 9 = 45, 3 × 15 = 45로 외항의 곱과 내항의 곱이 같습니다.",
            points=10,
        ),
    ]
