"""초등 6학년 개념 문제."""

from .._base import concept, mc


def get_concepts() -> list[dict]:
    """개념 7개 반환."""
    return [
        # ── 2단원: 각기둥과 각뿔 (2개) ──
        concept(
            id="e6-1-2-1",
            name="각기둥의 구성 요소와 전개도",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="각기둥의 밑면, 옆면, 모서리, 꼭짓점, 높이의 정의를 이해하고 전개도를 판별합니다.",
        ),
        concept(
            id="e6-1-2-2",
            name="각뿔의 구성 요소와 특징",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="각뿔의 밑면, 옆면(삼각형), 모서리, 꼭짓점, 높이를 각기둥과 비교하여 이해합니다.",
        ),
        # ── 5단원: 여러 가지 그래프 (2개) ──
        concept(
            id="e6-1-5-1",
            name="띠그래프와 원그래프의 해석",
            grade="elementary_6",
            category="concept",
            part="data",
            description="전체에 대한 각 부분의 비율을 띠와 원 모양으로 나타낸 그래프의 특징과 장점을 이해합니다.",
        ),
        concept(
            id="e6-1-5-2",
            name="그래프의 활용과 통계적 추론",
            grade="elementary_6",
            category="concept",
            part="data",
            description="자료의 특성에 맞는 적절한 그래프(꺾은선, 띠, 원)를 선택하고 정보를 해석합니다.",
        ),
        # ── 6단원: 직육면체의 겉넓이와 부피 (2개) ──
        concept(
            id="e6-1-6-1",
            name="직육면체의 겉넓이 구하기",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="여섯 면의 넓이 합, (밑면×2)+(옆면) 등 다양한 방법으로 겉넓이 공식을 유도합니다.",
        ),
        concept(
            id="e6-1-6-2",
            name="직육면체의 부피와 단위",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="1cm³, 1m³ 단위를 이해하고 (가로×세로×높이) 부피 공식을 직관적으로 파악합니다.",
        ),
        # ── 8학기: 비례식과 비례배분 (2개) ──
        concept(
            id="e6-2-4-1",
            name="비례식의 성질과 풀이",
            grade="elementary_6",
            category="concept",
            part="algebra",
            description="외항의 곱과 내항의 곱이 같음을 이용하여 비례식의 미지수 값을 구합니다.",
        ),
        concept(
            id="e6-2-4-2",
            name="비례배분의 원리와 활용",
            grade="elementary_6",
            category="concept",
            part="algebra",
            description="전체를 주어진 비로 나누는 비례배분의 원리를 이해하고 실제 문장제에 적용합니다.",
        ),
        # ── 10학기: 원의 넓이 (2개) ──
        concept(
            id="e6-2-5-1",
            name="원의 둘레(원주)와 원주율",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="원주와 지름의 관계인 원주율(약 3.14)을 이해하고 원주를 구합니다.",
        ),
        concept(
            id="e6-2-5-2",
            name="원의 넓이 구하는 원리와 공식",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="원 → 직사각형(반지름×원주의 1/2)으로 변형하여 원의 넓이 공식을 유도합니다.",
        ),
        # ── 11학기: 원기둥, 원뿔, 구 (2개) ──
        concept(
            id="e6-2-6-1",
            name="원기둥의 구성 요소와 전개도",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="원기둥의 밑면, 옆면(굽은 면), 높이를 이해하고 전개도의 특징을 파악합니다.",
        ),
        concept(
            id="e6-2-6-2",
            name="원뿔과 구의 특징 비교",
            grade="elementary_6",
            category="concept",
            part="geo",
            description="모선이 있는 원뿔과 어느 방향에서 봐도 원인 구의 입체적 특징을 대비하여 이해합니다.",
        ),
    ]


def get_questions() -> list[dict]:
    """개념 문제 21개 반환 (단원당 3개)."""
    return [
        # 1학기 2단원: 각기둥과 각뿔 (e6-1-2-1-lv04-cc-001 ~ 003)
        mc(
            id="e6-1-2-1-cc-001",
            concept_id="e6-1-2-1",
            category="concept",
            part="geo",
            difficulty=4,
            content="다음 중 삼각기둥을 옆으로 눕혔을 때, 밑면을 찾는 방법으로 옳은 것은?",
            options=[
                "가장 아래에 있는 면",
                "합동인 두 면",
                "가장 넓은 면",
                "직사각형 모양의 면",
            ],
            correct="B",
            explanation="각기둥의 밑면은 '합동인 두 면'입니다. 눕혀도 밑면은 바뀌지 않습니다. '밑면 = 바닥면' 오개념에 주의하세요.",
        ),
        mc(
            id="e6-1-2-2-cc-001",
            concept_id="e6-1-2-2",
            category="concept",
            part="geo",
            difficulty=6,
            content="사각뿔에서 꼭짓점에서 밑면까지의 거리를 무엇이라 합니까?",
            options=[
                "모서리",
                "모선",
                "높이",
                "옆면",
            ],
            correct="C",
            explanation="각뿔의 높이는 꼭짓점에서 밑면에 내린 수선의 길이입니다. 옆 모서리(모선)와 혼동하지 마세요.",
        ),
        mc(
            id="e6-1-2-1-cc-002",
            concept_id="e6-1-2-1",
            category="concept",
            part="geo",
            difficulty=5,
            content="오각기둥의 모서리는 모두 몇 개입니까?",
            options=[
                "10개",
                "15개",
                "20개",
                "25개",
            ],
            correct="B",
            explanation="각기둥의 모서리 = 밑면의 변 × 3입니다. 오각기둥은 5 × 3 = 15개입니다.",
        ),
        # 1학기 5단원: 여러 가지 그래프 (e6-1-5-1-lv07-cc-001 ~ 006)
        mc(
            id="e6-1-5-1-cc-001",
            concept_id="e6-1-5-1",
            category="concept",
            part="data",
            difficulty=7,
            content="원그래프에서 30%를 나타내는 부분의 중심각은 몇 도입니까?",
            options=[
                "30°",
                "60°",
                "90°",
                "108°",
            ],
            correct="D",
            explanation="중심각 = 360° × 비율입니다. 360° × 0.3 = 108°입니다. 30%를 30°로 착각하는 오개념에 주의하세요.",
        ),
        mc(
            id="e6-1-5-1-cc-002",
            concept_id="e6-1-5-1",
            category="concept",
            part="data",
            difficulty=5,
            content="원그래프에서 25%를 나타내는 부분의 중심각은 몇 도입니까?",
            options=[
                "25°",
                "90°",
                "100°",
                "125°",
            ],
            correct="B",
            explanation="360° × 0.25 = 90°입니다.",
        ),
        mc(
            id="e6-1-5-2-cc-001",
            concept_id="e6-1-5-2",
            category="concept",
            part="data",
            difficulty=6,
            content="띠그래프와 원그래프의 공통점은 무엇입니까?",
            options=[
                "전체에 대한 각 부분의 비율을 나타낸다",
                "정확한 수량을 알 수 있다",
                "시간에 따른 변화를 알 수 있다",
                "두 변수의 관계를 알 수 있다",
            ],
            correct="A",
            explanation="띠그래프와 원그래프는 모두 전체에 대한 각 부분의 비율을 시각화하는 그래프입니다.",
        ),
        # 1학기 6단원: 직육면체의 부피와 겉넓이 (e6-1-6-1-lv08-cc-001 ~ 009)
        mc(
            id="e6-1-6-2-cc-001",
            concept_id="e6-1-6-2",
            category="concept",
            part="geo",
            difficulty=8,
            content="1m³는 몇 cm³입니까?",
            options=[
                "100 cm³",
                "1,000 cm³",
                "10,000 cm³",
                "1,000,000 cm³",
            ],
            correct="D",
            explanation="1m = 100cm이므로, 1m³ = 100cm × 100cm × 100cm = 1,000,000cm³입니다. 단위 변환 시 세제곱에 주의하세요.",
        ),
        mc(
            id="e6-1-6-2-cc-002",
            concept_id="e6-1-6-2",
            category="concept",
            part="geo",
            difficulty=7,
            content="직육면체의 부피를 구하는 공식은?",
            options=[
                "가로 + 세로 + 높이",
                "가로 × 세로",
                "가로 × 세로 × 높이",
                "2 × (가로 + 세로 + 높이)",
            ],
            correct="C",
            explanation="직육면체의 부피 = 밑면의 넓이 × 높이 = 가로 × 세로 × 높이입니다.",
        ),
        mc(
            id="e6-1-6-1-cc-001",
            concept_id="e6-1-6-1",
            category="concept",
            part="geo",
            difficulty=9,
            content="쌓기나무가 12개로 같은 두 입체도형이 있습니다. 이 두 도형의 겉넓이는?",
            options=[
                "항상 같다",
                "항상 다르다",
                "같을 수도, 다를 수도 있다",
                "부피가 같으면 겉넓이도 항상 같다",
            ],
            correct="C",
            explanation="부피가 같아도 쌓는 방식에 따라 겉넓이는 달라질 수 있습니다. '부피 같으면 겉넓이도 같다'는 오개념입니다.",
        ),
        # 2학기 3단원: 공간과 입체 (e6-2-3-1-lv08-cc-001 ~ 012)
        mc(
            id="e6-2-3-1-cc-001",
            concept_id="e6-2-3-1",
            category="concept",
            part="geo",
            difficulty=8,
            content="위에서 본 모양이 2×2 정사각형이고, 앞에서 본 모양이 높이 3인 직사각형일 때, 쌓기나무의 최소 개수는?",
            options=[
                "4개",
                "8개",
                "12개",
                "6개",
            ],
            correct="A",
            explanation="최소 개수는 위에서 본 모양의 칸 수와 같습니다. 2×2 = 4개입니다. 높이 조건은 최소 개수에 영향을 주지 않습니다.",
        ),
        mc(
            id="e6-2-3-1-cc-002",
            concept_id="e6-2-3-1",
            category="concept",
            part="geo",
            difficulty=9,
            content="위에서 본 모양, 앞에서 본 모양, 옆에서 본 모양만으로 쌓기나무의 전체 모양을 정확히 알 수 있습니까?",
            options=[
                "항상 알 수 있다",
                "항상 알 수 없다",
                "경우에 따라 다르다",
                "위와 앞만 있으면 알 수 있다",
            ],
            correct="C",
            explanation="투영도만으로는 전체 모양이 하나로 결정되지 않을 수 있습니다. 여러 배치가 가능한 경우가 있습니다.",
        ),
        mc(
            id="e6-2-3-1-cc-003",
            concept_id="e6-2-3-1",
            category="concept",
            part="geo",
            difficulty=7,
            content="쌓기나무로 만든 입체도형을 앞에서 봤을 때 고려해야 할 것은?",
            options=[
                "가로와 높이만 보인다",
                "깊이 정보도 포함된다",
                "옆면도 함께 보인다",
                "위에서 본 모양과 같다",
            ],
            correct="A",
            explanation="앞에서 본 모양은 가로와 높이만 나타나고 깊이는 나타나지 않습니다.",
        ),
        # 2학기 4단원: 비례식과 비례배분 (e6-2-4-1-lv08-cc-001 ~ 015)
        mc(
            id="e6-2-4-1-cc-001",
            concept_id="e6-2-4-1",
            category="concept",
            part="algebra",
            difficulty=8,
            content="비례식 2 : 3 = 4 : ☐에서 ☐에 알맞은 수는?",
            options=[
                "5",
                "6",
                "7",
                "8",
            ],
            correct="B",
            explanation="외항의 곱 = 내항의 곱이므로, 2 × ☐ = 3 × 4 = 12, ☐ = 6입니다. 덧셈적 사고(2→4는 +2이므로 3→5)는 오류입니다.",
        ),
        mc(
            id="e6-2-4-2-cc-001",
            concept_id="e6-2-4-2",
            category="concept",
            part="algebra",
            difficulty=9,
            content="24를 2 : 4의 비로 비례배분하면 작은 쪽은?",
            options=[
                "6",
                "8",
                "12",
                "16",
            ],
            correct="B",
            explanation="비의 합 = 2 + 4 = 6입니다. 작은 쪽 = 24 × 2/6 = 8입니다. 분모를 4로 잡는 오류에 주의하세요.",
        ),
        mc(
            id="e6-2-4-1-cc-002",
            concept_id="e6-2-4-1",
            category="concept",
            part="algebra",
            difficulty=7,
            content="비례식 a : b = c : d에서 외항은 무엇입니까?",
            options=[
                "a와 b",
                "b와 c",
                "a와 d",
                "c와 d",
            ],
            correct="C",
            explanation="비례식에서 외항은 양 끝의 항인 a와 d입니다. 내항은 가운데 두 항인 b와 c입니다.",
        ),
        # 2학기 5단원: 원의 넓이 (e6-2-5-1-lv09-cc-001 ~ 018)
        mc(
            id="e6-2-5-2-cc-001",
            concept_id="e6-2-5-2",
            category="concept",
            part="geo",
            difficulty=9,
            content="반지름이 2배가 되면 원의 넓이는 몇 배가 됩니까?",
            options=[
                "2배",
                "3배",
                "4배",
                "8배",
            ],
            correct="C",
            explanation="원의 넓이 = πr²이므로, 반지름이 2배가 되면 넓이는 2² = 4배가 됩니다.",
        ),
        mc(
            id="e6-2-5-2-cc-002",
            concept_id="e6-2-5-2",
            category="concept",
            part="geo",
            difficulty=6,
            content="원의 넓이를 구하는 공식에서 r은 무엇을 의미합니까?",
            options=[
                "원주",
                "지름",
                "반지름",
                "원주율",
            ],
            correct="C",
            explanation="원의 넓이 = πr²에서 r은 반지름입니다.",
        ),
        mc(
            id="e6-2-5-1-cc-001",
            concept_id="e6-2-5-1",
            category="concept",
            part="geo",
            difficulty=8,
            content="반원의 둘레를 구할 때 포함해야 하는 것은?",
            options=[
                "곡선 부분만",
                "곡선 부분 + 지름",
                "곡선 부분 + 반지름 2개",
                "원주 전체",
            ],
            correct="B",
            explanation="반원의 둘레 = (원주의 반) + 지름 = πr + 2r입니다. 곡선 부분만 계산하는 오류에 주의하세요.",
        ),
        # 2학기 6단원: 원기둥, 원뿔, 구 (e6-2-6-1-lv07-cc-001 ~ 021)
        mc(
            id="e6-2-6-1-cc-001",
            concept_id="e6-2-6-1",
            category="concept",
            part="geo",
            difficulty=7,
            content="구를 완벽하게 펼친 전개도를 그릴 수 있습니까?",
            options=[
                "가능하다",
                "불가능하다",
                "특정 방법으로만 가능하다",
                "작은 구만 가능하다",
            ],
            correct="B",
            explanation="구는 곡면이므로 평면으로 완벽하게 펼칠 수 없습니다. 지구본을 종이 지도로 그릴 때 왜곡이 생기는 것과 같은 원리입니다.",
        ),
        mc(
            id="e6-2-6-2-cc-001",
            concept_id="e6-2-6-2",
            category="concept",
            part="geo",
            difficulty=8,
            content="원뿔에서 꼭짓점에서 밑면의 원까지 수직으로 내린 선분은 무엇입니까?",
            options=[
                "모선",
                "높이",
                "반지름",
                "지름",
            ],
            correct="B",
            explanation="원뿔의 높이는 꼭짓점에서 밑면에 수직으로 내린 선분입니다. 옆면을 따라 내려가는 모선과 혼동하지 마세요.",
        ),
        mc(
            id="e6-2-6-1-cc-002",
            concept_id="e6-2-6-1",
            category="concept",
            part="geo",
            difficulty=6,
            content="원기둥을 회전축에 수직으로 자른 단면의 모양은?",
            options=[
                "직사각형",
                "원",
                "타원",
                "삼각형",
            ],
            correct="B",
            explanation="원기둥을 회전축에 수직으로 자르면 단면은 원입니다.",
        ),
    ]
