"""초등 6학년 빈칸 채우기 문제."""

from .._base import fb


def get_questions() -> list[dict]:
    """빈칸 채우기 문제 24개 반환 (단원당 2개)."""
    return [
        # 1학기 1단원: 분수의 나눗셈1 (e6-fb-001 ~ 002)
        fb(
            id="e6-fb-001",
            concept_id="concept-e6-frac-div1",
            category="computation",
            part="calc",
            difficulty=4,
            content="5를 6으로 나눈 몫을 분수로 나타내면 __입니다.",
            answer="5/6",
            explanation="5 ÷ 6 = 5/6입니다. 나눗셈의 몫을 분수로 표현할 수 있습니다.",
            accept_formats=["5/6"],
        ),
        fb(
            id="e6-fb-002",
            concept_id="concept-e6-frac-div1",
            category="computation",
            part="calc",
            difficulty=5,
            content="2/3 ÷ 4 = __입니다. 답을 분수로 쓰세요.",
            answer="1/6",
            explanation="2/3 ÷ 4 = 2/3 × 1/4 = 2/12 = 1/6입니다.",
            accept_formats=["1/6"],
        ),
        # 1학기 2단원: 각기둥과 각뿔 (e6-fb-003 ~ 004)
        fb(
            id="e6-fb-003",
            concept_id="concept-e6-prism-pyramid",
            category="concept",
            part="geo",
            difficulty=6,
            content="육각기둥의 꼭짓점은 모두 __개입니다.",
            answer="12",
            explanation="각기둥의 꼭짓점 = 밑면의 꼭짓점 × 2입니다. 육각기둥은 6 × 2 = 12개입니다.",
            accept_formats=["12"],
        ),
        fb(
            id="e6-fb-004",
            concept_id="concept-e6-prism-pyramid",
            category="concept",
            part="geo",
            difficulty=7,
            content="오각뿔의 면은 모두 __개입니다.",
            answer="6",
            explanation="각뿔의 면 = 밑면의 변의 수 + 1입니다. 오각뿔은 5 + 1 = 6개입니다.",
            accept_formats=["6"],
        ),
        # 1학기 3단원: 소수의 나눗셈1 (e6-fb-005 ~ 006)
        fb(
            id="e6-fb-005",
            concept_id="concept-e6-dec-div1",
            category="computation",
            part="calc",
            difficulty=6,
            content="4.2 ÷ 7 = __입니다.",
            answer="0.6",
            explanation="42 ÷ 7 = 6이므로, 4.2 ÷ 7 = 0.6입니다.",
            accept_formats=["0.6"],
        ),
        fb(
            id="e6-fb-006",
            concept_id="concept-e6-dec-div1",
            category="computation",
            part="calc",
            difficulty=7,
            content="9.15 ÷ 5 = __입니다.",
            answer="1.83",
            explanation="915 ÷ 5 = 183이므로, 9.15 ÷ 5 = 1.83입니다.",
            accept_formats=["1.83"],
        ),
        # 1학기 4단원: 비와 비율 (e6-fb-007 ~ 008)
        fb(
            id="e6-fb-007",
            concept_id="concept-e6-ratio",
            category="computation",
            part="calc",
            difficulty=8,
            content="12 : 16을 가장 간단한 자연수의 비로 나타내면 __ : __입니다.",
            answer="3:4",
            explanation="12 : 16 = 3 : 4입니다. 공약수 4로 나누면 가장 간단한 비가 됩니다.",
            accept_formats=["3:4", "3 : 4"],
        ),
        fb(
            id="e6-fb-008",
            concept_id="concept-e6-ratio",
            category="computation",
            part="calc",
            difficulty=9,
            content="물 200g에 소금 50g을 녹인 소금물의 진하기는 __%입니다.",
            answer="20",
            explanation="소금물 농도 = (소금)/(전체) × 100 = 50/(50+200) × 100 = 50/250 × 100 = 20%입니다.",
            accept_formats=["20"],
        ),
        # 1학기 5단원: 여러 가지 그래프 (e6-fb-009 ~ 010)
        fb(
            id="e6-fb-009",
            concept_id="concept-e6-graphs",
            category="concept",
            part="data",
            difficulty=7,
            content="원그래프에서 20%를 나타내는 부분의 중심각은 __도입니다.",
            answer="72",
            explanation="360° × 0.2 = 72°입니다.",
            accept_formats=["72"],
        ),
        fb(
            id="e6-fb-010",
            concept_id="concept-e6-graphs",
            category="concept",
            part="data",
            difficulty=8,
            content="원그래프에서 중심각이 90°인 부분이 나타내는 비율은 __%입니다.",
            answer="25",
            explanation="90° ÷ 360° = 0.25 = 25%입니다.",
            accept_formats=["25"],
        ),
        # 1학기 6단원: 직육면체의 부피와 겉넓이 (e6-fb-011 ~ 012)
        fb(
            id="e6-fb-011",
            concept_id="concept-e6-volume",
            category="concept",
            part="geo",
            difficulty=8,
            content="가로 3cm, 세로 4cm, 높이 5cm인 직육면체의 부피는 __cm³입니다.",
            answer="60",
            explanation="부피 = 3 × 4 × 5 = 60cm³입니다.",
            accept_formats=["60"],
        ),
        fb(
            id="e6-fb-012",
            concept_id="concept-e6-volume",
            category="concept",
            part="geo",
            difficulty=9,
            content="한 모서리가 10cm인 정육면체의 겉넓이는 __cm²입니다.",
            answer="600",
            explanation="겉넓이 = 한 면의 넓이 × 6 = 10 × 10 × 6 = 600cm²입니다.",
            accept_formats=["600"],
        ),
        # 2학기 1단원: 분수의 나눗셈2 (e6-fb-013 ~ 014)
        fb(
            id="e6-fb-013",
            concept_id="concept-e6-frac-div2",
            category="computation",
            part="calc",
            difficulty=7,
            content="2/5 ÷ 3/5 = __입니다. 답을 분수 또는 자연수로 쓰세요.",
            answer="2/3",
            explanation="2/5 ÷ 3/5 = 2/5 × 5/3 = 10/15 = 2/3입니다.",
            accept_formats=["2/3"],
        ),
        fb(
            id="e6-fb-014",
            concept_id="concept-e6-frac-div2",
            category="computation",
            part="calc",
            difficulty=8,
            content="4/7 ÷ 2/7 = __입니다.",
            answer="2",
            explanation="4/7 ÷ 2/7 = 4/7 × 7/2 = 28/14 = 2입니다. 통분으로도 계산 가능: 분모가 같으므로 4 ÷ 2 = 2입니다.",
            accept_formats=["2"],
        ),
        # 2학기 2단원: 소수의 나눗셈2 (e6-fb-015 ~ 016)
        fb(
            id="e6-fb-015",
            concept_id="concept-e6-dec-div2",
            category="computation",
            part="calc",
            difficulty=8,
            content="3.6 ÷ 1.2 = __입니다.",
            answer="3",
            explanation="36 ÷ 12 = 3입니다. 나누는 수와 나누어지는 수에 10을 곱해 계산합니다.",
            accept_formats=["3"],
        ),
        fb(
            id="e6-fb-016",
            concept_id="concept-e6-dec-div2",
            category="computation",
            part="calc",
            difficulty=9,
            content="6 ÷ 1.5 = __입니다.",
            answer="4",
            explanation="60 ÷ 15 = 4입니다.",
            accept_formats=["4"],
        ),
        # 2학기 3단원: 공간과 입체 (e6-fb-017 ~ 018)
        fb(
            id="e6-fb-017",
            concept_id="concept-e6-spatial",
            category="concept",
            part="geo",
            difficulty=8,
            content="위에서 본 모양이 3×3 정사각형일 때, 쌓기나무의 최소 개수는 __개입니다.",
            answer="9",
            explanation="최소 개수는 위에서 본 모양의 칸 수와 같습니다. 3 × 3 = 9개입니다.",
            accept_formats=["9"],
        ),
        fb(
            id="e6-fb-018",
            concept_id="concept-e6-spatial",
            category="concept",
            part="geo",
            difficulty=9,
            content="위에서 본 모양이 2×3 직사각형이고 각 칸에 쓰인 수가 최댓값일 때, 쌓기나무의 최대 개수를 구하려면 각 칸에 쓰인 __를 모두 더하면 됩니다.",
            answer="높이",
            explanation="각 칸에 쌓인 높이를 모두 더하면 전체 개수가 됩니다.",
            accept_formats=["높이", "수"],
        ),
        # 2학기 4단원: 비례식과 비례배분 (e6-fb-019 ~ 020)
        fb(
            id="e6-fb-019",
            concept_id="concept-e6-proportion",
            category="concept",
            part="algebra",
            difficulty=9,
            content="비례식 3 : 4 = 9 : ☐에서 ☐는 __입니다.",
            answer="12",
            explanation="외항의 곱 = 내항의 곱이므로, 3 × ☐ = 4 × 9 = 36, ☐ = 12입니다.",
            accept_formats=["12"],
        ),
        fb(
            id="e6-fb-020",
            concept_id="concept-e6-proportion",
            category="concept",
            part="algebra",
            difficulty=10,
            content="30을 3 : 2의 비로 비례배분하면 큰 쪽은 __입니다.",
            answer="18",
            explanation="비의 합 = 3 + 2 = 5입니다. 큰 쪽 = 30 × 3/5 = 18입니다.",
            accept_formats=["18"],
        ),
        # 2학기 5단원: 원의 넓이 (e6-fb-021 ~ 022)
        fb(
            id="e6-fb-021",
            concept_id="concept-e6-circle-area",
            category="concept",
            part="geo",
            difficulty=8,
            content="반지름이 5cm인 원의 넓이는 __cm²입니다. (π = 3.14로 계산)",
            answer="78.5",
            explanation="원의 넓이 = 3.14 × 5 × 5 = 78.5cm²입니다.",
            accept_formats=["78.5"],
        ),
        fb(
            id="e6-fb-022",
            concept_id="concept-e6-circle-area",
            category="concept",
            part="geo",
            difficulty=9,
            content="지름이 8cm인 원의 넓이는 __cm²입니다. (π = 3으로 계산)",
            answer="48",
            explanation="반지름 = 8 ÷ 2 = 4cm, 넓이 = 3 × 4 × 4 = 48cm²입니다.",
            accept_formats=["48"],
        ),
        # 2학기 6단원: 원기둥, 원뿔, 구 (e6-fb-023 ~ 024)
        fb(
            id="e6-fb-023",
            concept_id="concept-e6-solids",
            category="concept",
            part="geo",
            difficulty=7,
            content="원기둥의 밑면은 모두 __개입니다.",
            answer="2",
            explanation="원기둥은 합동인 두 개의 원을 밑면으로 가집니다.",
            accept_formats=["2"],
        ),
        fb(
            id="e6-fb-024",
            concept_id="concept-e6-solids",
            category="concept",
            part="geo",
            difficulty=8,
            content="원뿔의 옆면을 펼쳤을 때 나타나는 도형은 __입니다.",
            answer="부채꼴",
            explanation="원뿔의 전개도에서 옆면은 부채꼴 모양입니다.",
            accept_formats=["부채꼴", "부채형"],
        ),
    ]
