"""초등 6학년 빈칸 채우기 문제."""

from .._base import fb


def get_questions() -> list[dict]:
    """빈칸 채우기 문제 68개 반환 (개념당 1개)."""
    return [
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 1단원: 분수의 나눗셈 (e6-1-1-01~04)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-1-1-01-fb-001",
            concept_id="e6-1-1-01",
            category="computation",
            part="calc",
            difficulty=3,
            content="5를 6으로 나눈 몫을 분수로 나타내면 __입니다.",
            answer="5/6",
            explanation="5 ÷ 6 = 5/6입니다. 나눗셈의 몫을 분수로 표현할 수 있습니다.",
            accept_formats=["5/6"],
        ),
        fb(
            id="e6-1-1-02-fb-001",
            concept_id="e6-1-1-02",
            category="computation",
            part="calc",
            difficulty=4,
            content="8 ÷ 3 = 2__/3입니다. 빈칸에 들어갈 자연수는?",
            answer="2",
            explanation="8 ÷ 3 = 2...2이므로, 대분수로 나타내면 2²⁄₃입니다.",
            accept_formats=["2"],
        ),
        fb(
            id="e6-1-1-03-fb-001",
            concept_id="e6-1-1-03",
            category="computation",
            part="calc",
            difficulty=5,
            content="2/3 ÷ 4 = __입니다. 답을 기약분수로 쓰세요.",
            answer="1/6",
            explanation="2/3 ÷ 4 = 2/3 × 1/4 = 2/12 = 1/6입니다.",
            accept_formats=["1/6"],
        ),
        fb(
            id="e6-1-1-04-fb-001",
            concept_id="e6-1-1-04",
            category="computation",
            part="calc",
            difficulty=6,
            content="3/5 ÷ 2 = __입니다.",
            answer="3/10",
            explanation="3/5 ÷ 2 = 3/5 × 1/2 = 3/10입니다.",
            accept_formats=["3/10"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 2단원: 각기둥과 각뿔 (e6-1-2-01~06)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-1-2-01-fb-001",
            concept_id="e6-1-2-01",
            category="concept",
            part="geo",
            difficulty=4,
            content="오각기둥의 면은 모두 __개입니다.",
            answer="7",
            explanation="각기둥의 면 = 밑면의 변의 수 + 2입니다. 오각기둥은 5 + 2 = 7개입니다.",
            accept_formats=["7"],
        ),
        fb(
            id="e6-1-2-02-fb-001",
            concept_id="e6-1-2-02",
            category="concept",
            part="geo",
            difficulty=5,
            content="육각기둥의 꼭짓점은 모두 __개입니다.",
            answer="12",
            explanation="각기둥의 꼭짓점 = 밑면의 꼭짓점 × 2입니다. 육각기둥은 6 × 2 = 12개입니다.",
            accept_formats=["12"],
        ),
        fb(
            id="e6-1-2-03-fb-001",
            concept_id="e6-1-2-03",
            category="concept",
            part="geo",
            difficulty=5,
            content="칠각기둥의 모서리는 모두 __개입니다.",
            answer="21",
            explanation="각기둥의 모서리 = 밑면의 변의 수 × 3입니다. 칠각기둥은 7 × 3 = 21개입니다.",
            accept_formats=["21"],
        ),
        fb(
            id="e6-1-2-04-fb-001",
            concept_id="e6-1-2-04",
            category="concept",
            part="geo",
            difficulty=6,
            content="오각뿔의 면은 모두 __개입니다.",
            answer="6",
            explanation="각뿔의 면 = 밑면의 변의 수 + 1입니다. 오각뿔은 5 + 1 = 6개입니다.",
            accept_formats=["6"],
        ),
        fb(
            id="e6-1-2-05-fb-001",
            concept_id="e6-1-2-05",
            category="concept",
            part="geo",
            difficulty=6,
            content="육각뿔의 꼭짓점은 모두 __개입니다.",
            answer="7",
            explanation="각뿔의 꼭짓점 = 밑면의 꼭짓점 + 1입니다. 육각뿔은 6 + 1 = 7개입니다.",
            accept_formats=["7"],
        ),
        fb(
            id="e6-1-2-06-fb-001",
            concept_id="e6-1-2-06",
            category="concept",
            part="geo",
            difficulty=7,
            content="팔각뿔의 모서리는 모두 __개입니다.",
            answer="16",
            explanation="각뿔의 모서리 = 밑면의 변의 수 × 2입니다. 팔각뿔은 8 × 2 = 16개입니다.",
            accept_formats=["16"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 3단원: 소수의 나눗셈 (e6-1-3-01~07)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-1-3-01-fb-001",
            concept_id="e6-1-3-01",
            category="computation",
            part="calc",
            difficulty=4,
            content="3.5 ÷ 5 = __입니다.",
            answer="0.7",
            explanation="35 ÷ 5 = 7이므로, 3.5 ÷ 5 = 0.7입니다.",
            accept_formats=["0.7"],
        ),
        fb(
            id="e6-1-3-02-fb-001",
            concept_id="e6-1-3-02",
            category="computation",
            part="calc",
            difficulty=5,
            content="4.2 ÷ 7 = __입니다.",
            answer="0.6",
            explanation="42 ÷ 7 = 6이므로, 4.2 ÷ 7 = 0.6입니다.",
            accept_formats=["0.6"],
        ),
        fb(
            id="e6-1-3-03-fb-001",
            concept_id="e6-1-3-03",
            category="computation",
            part="calc",
            difficulty=6,
            content="9.15 ÷ 5 = __입니다.",
            answer="1.83",
            explanation="915 ÷ 5 = 183이므로, 9.15 ÷ 5 = 1.83입니다.",
            accept_formats=["1.83"],
        ),
        fb(
            id="e6-1-3-04-fb-001",
            concept_id="e6-1-3-04",
            category="computation",
            part="calc",
            difficulty=6,
            content="12.8 ÷ 4 = __입니다.",
            answer="3.2",
            explanation="128 ÷ 4 = 32이므로, 12.8 ÷ 4 = 3.2입니다.",
            accept_formats=["3.2"],
        ),
        fb(
            id="e6-1-3-05-fb-001",
            concept_id="e6-1-3-05",
            category="computation",
            part="calc",
            difficulty=7,
            content="6.48 ÷ 8 = __입니다.",
            answer="0.81",
            explanation="648 ÷ 8 = 81이므로, 6.48 ÷ 8 = 0.81입니다.",
            accept_formats=["0.81"],
        ),
        fb(
            id="e6-1-3-06-fb-001",
            concept_id="e6-1-3-06",
            category="computation",
            part="calc",
            difficulty=7,
            content="15.75 ÷ 3 = __입니다.",
            answer="5.25",
            explanation="1575 ÷ 3 = 525이므로, 15.75 ÷ 3 = 5.25입니다.",
            accept_formats=["5.25"],
        ),
        fb(
            id="e6-1-3-07-fb-001",
            concept_id="e6-1-3-07",
            category="computation",
            part="calc",
            difficulty=8,
            content="7을 8로 나눈 몫을 소수 첫째 자리까지 구하면 __입니다.",
            answer="0.9",
            explanation="7 ÷ 8 = 0.875입니다. 둘째 자리에서 반올림하면 0.9입니다.",
            accept_formats=["0.9"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 4단원: 비와 비율 (e6-1-4-01~06)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-1-4-01-fb-001",
            concept_id="e6-1-4-01",
            category="concept",
            part="algebra",
            difficulty=5,
            content="6과 9의 비를 기호를 사용하여 나타내면 __입니다.",
            answer="6:9",
            explanation="6과 9의 비는 6 : 9입니다.",
            accept_formats=["6:9", "6 : 9"],
        ),
        fb(
            id="e6-1-4-02-fb-001",
            concept_id="e6-1-4-02",
            category="concept",
            part="algebra",
            difficulty=6,
            content="비 12 : 16을 가장 간단한 자연수의 비로 나타내면 __입니다.",
            answer="3:4",
            explanation="12 : 16 = 3 : 4입니다. 공약수 4로 나누면 가장 간단한 비가 됩니다.",
            accept_formats=["3:4", "3 : 4"],
        ),
        fb(
            id="e6-1-4-03-fb-001",
            concept_id="e6-1-4-03",
            category="concept",
            part="algebra",
            difficulty=7,
            content="기준량이 40이고 비교하는 양이 32일 때, 비율은 __입니다.",
            answer="0.8",
            explanation="비율 = 비교하는 양 ÷ 기준량 = 32 ÷ 40 = 0.8입니다.",
            accept_formats=["0.8", "4/5"],
        ),
        fb(
            id="e6-1-4-04-fb-001",
            concept_id="e6-1-4-04",
            category="concept",
            part="algebra",
            difficulty=8,
            content="비율 0.35를 백분율로 나타내면 __%입니다.",
            answer="35",
            explanation="백분율 = 비율 × 100 = 0.35 × 100 = 35%입니다.",
            accept_formats=["35"],
        ),
        fb(
            id="e6-1-4-05-fb-001",
            concept_id="e6-1-4-05",
            category="concept",
            part="algebra",
            difficulty=8,
            content="물 200g에 소금 50g을 녹인 소금물의 진하기는 __%입니다.",
            answer="20",
            explanation="소금물 농도 = (소금)/(전체) × 100 = 50/(50+200) × 100 = 50/250 × 100 = 20%입니다.",
            accept_formats=["20"],
        ),
        fb(
            id="e6-1-4-06-fb-001",
            concept_id="e6-1-4-06",
            category="fill_in_blank",
            part="algebra",
            difficulty=9,
            content="정가 10000원인 물건을 20% 할인하면 __원입니다.",
            answer="8000",
            explanation="할인액 = 10000 × 0.2 = 2000원. 판매가 = 10000 - 2000 = 8000원입니다.",
            accept_formats=["8000"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 5단원: 여러 가지 그래프 (e6-1-5-01~07)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-1-5-01-fb-001",
            concept_id="e6-1-5-01",
            category="concept",
            part="data",
            difficulty=5,
            content="띠그래프는 전체에 대한 각 부분의 __을 한눈에 비교할 수 있습니다.",
            answer="비율",
            explanation="띠그래프는 전체를 100%로 보고 각 부분의 비율을 비교합니다.",
            accept_formats=["비율", "백분율"],
        ),
        fb(
            id="e6-1-5-02-fb-001",
            concept_id="e6-1-5-02",
            category="concept",
            part="data",
            difficulty=6,
            content="원그래프에서 20%를 나타내는 부분의 중심각은 __도입니다.",
            answer="72",
            explanation="360° × 0.2 = 72°입니다.",
            accept_formats=["72"],
        ),
        fb(
            id="e6-1-5-03-fb-001",
            concept_id="e6-1-5-03",
            category="concept",
            part="data",
            difficulty=7,
            content="원그래프에서 중심각이 90°인 부분이 나타내는 비율은 __%입니다.",
            answer="25",
            explanation="90° ÷ 360° = 0.25 = 25%입니다.",
            accept_formats=["25"],
        ),
        fb(
            id="e6-1-5-04-fb-001",
            concept_id="e6-1-5-04",
            category="concept",
            part="data",
            difficulty=7,
            content="원그래프에서 중심각이 120°인 부분을 띠그래프로 나타내면 전체 길이의 __배입니다.",
            answer="1/3",
            explanation="120° ÷ 360° = 1/3입니다.",
            accept_formats=["1/3", "0.333"],
        ),
        fb(
            id="e6-1-5-05-fb-001",
            concept_id="e6-1-5-05",
            category="concept",
            part="data",
            difficulty=8,
            content="전체 200명 중 25%를 원그래프로 나타낼 때 중심각은 __도입니다.",
            answer="90",
            explanation="360° × 0.25 = 90°입니다.",
            accept_formats=["90"],
        ),
        fb(
            id="e6-1-5-06-fb-001",
            concept_id="e6-1-5-06",
            category="fill_in_blank",
            part="data",
            difficulty=8,
            content="원그래프에서 A 항목이 30%, B 항목이 50%일 때, 나머지 항목은 __%입니다.",
            answer="20",
            explanation="전체 = 100%, 나머지 = 100 - 30 - 50 = 20%입니다.",
            accept_formats=["20"],
        ),
        fb(
            id="e6-1-5-07-fb-001",
            concept_id="e6-1-5-07",
            category="fill_in_blank",
            part="data",
            difficulty=9,
            content="띠그래프에서 길이가 12cm이고 A 항목이 4cm일 때, A의 백분율은 약 __%입니다. (소수 첫째 자리에서 반올림)",
            answer="33",
            explanation="4 ÷ 12 = 0.333... ≈ 0.33 = 33%입니다.",
            accept_formats=["33"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 1학기 6단원: 직육면체의 부피와 겉넓이 (e6-1-6-01~04)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-1-6-01-fb-001",
            concept_id="e6-1-6-01",
            category="concept",
            part="geo",
            difficulty=6,
            content="1m³는 __cm³와 같습니다.",
            answer="1000000",
            explanation="1m = 100cm이므로, 1m³ = 100 × 100 × 100 = 1,000,000cm³입니다.",
            accept_formats=["1000000"],
        ),
        fb(
            id="e6-1-6-02-fb-001",
            concept_id="e6-1-6-02",
            category="concept",
            part="geo",
            difficulty=7,
            content="가로 3cm, 세로 4cm, 높이 5cm인 직육면체의 부피는 __cm³입니다.",
            answer="60",
            explanation="부피 = 3 × 4 × 5 = 60cm³입니다.",
            accept_formats=["60"],
        ),
        fb(
            id="e6-1-6-03-fb-001",
            concept_id="e6-1-6-03",
            category="concept",
            part="geo",
            difficulty=8,
            content="가로 3cm, 세로 4cm, 높이 5cm인 직육면체의 겉넓이는 __cm²입니다.",
            answer="94",
            explanation="겉넓이 = 2(3×4 + 4×5 + 5×3) = 2(12 + 20 + 15) = 2 × 47 = 94cm²입니다.",
            accept_formats=["94"],
        ),
        fb(
            id="e6-1-6-04-fb-001",
            concept_id="e6-1-6-04",
            category="concept",
            part="geo",
            difficulty=8,
            content="한 모서리가 10cm인 정육면체의 겉넓이는 __cm²입니다.",
            answer="600",
            explanation="겉넓이 = 한 면의 넓이 × 6 = 10 × 10 × 6 = 600cm²입니다.",
            accept_formats=["600"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 1단원: 분수의 나눗셈 (e6-2-1-01~06)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-2-1-01-fb-001",
            concept_id="e6-2-1-01",
            category="computation",
            part="calc",
            difficulty=6,
            content="3/4의 역수는 __입니다.",
            answer="4/3",
            explanation="분자와 분모를 바꾸면 역수가 됩니다. 3/4의 역수는 4/3입니다.",
            accept_formats=["4/3"],
        ),
        fb(
            id="e6-2-1-02-fb-001",
            concept_id="e6-2-1-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="2/5 ÷ 3/5 = __입니다. 답을 기약분수로 쓰세요.",
            answer="2/3",
            explanation="2/5 ÷ 3/5 = 2/5 × 5/3 = 10/15 = 2/3입니다.",
            accept_formats=["2/3"],
        ),
        fb(
            id="e6-2-1-03-fb-001",
            concept_id="e6-2-1-03",
            category="computation",
            part="calc",
            difficulty=7,
            content="4/7 ÷ 2/7 = __입니다.",
            answer="2",
            explanation="4/7 ÷ 2/7 = 4/7 × 7/2 = 28/14 = 2입니다. 분모가 같으므로 4 ÷ 2 = 2로도 계산 가능합니다.",
            accept_formats=["2"],
        ),
        fb(
            id="e6-2-1-04-fb-001",
            concept_id="e6-2-1-04",
            category="computation",
            part="calc",
            difficulty=8,
            content="3/8 ÷ 5/6 = __입니다. 답을 기약분수로 쓰세요.",
            answer="9/20",
            explanation="3/8 ÷ 5/6 = 3/8 × 6/5 = 18/40 = 9/20입니다.",
            accept_formats=["9/20"],
        ),
        fb(
            id="e6-2-1-05-fb-001",
            concept_id="e6-2-1-05",
            category="computation",
            part="calc",
            difficulty=9,
            content="1²⁄₃ ÷ 2¹⁄₄ = __입니다. 답을 기약분수 또는 대분수로 쓰세요.",
            answer="20/27",
            explanation="1²⁄₃ = 5/3, 2¹⁄₄ = 9/4. 5/3 ÷ 9/4 = 5/3 × 4/9 = 20/27입니다.",
            accept_formats=["20/27"],
        ),
        fb(
            id="e6-2-1-06-fb-001",
            concept_id="e6-2-1-06",
            category="fill_in_blank",
            part="calc",
            difficulty=9,
            content="끈 3/4 m를 1/8 m씩 자르면 __도막이 됩니다.",
            answer="6",
            explanation="3/4 ÷ 1/8 = 3/4 × 8/1 = 24/4 = 6도막입니다.",
            accept_formats=["6"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 2단원: 소수의 나눗셈 (e6-2-2-01~06)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-2-2-01-fb-001",
            concept_id="e6-2-2-01",
            category="computation",
            part="calc",
            difficulty=6,
            content="3.6 ÷ 1.2 = __입니다.",
            answer="3",
            explanation="36 ÷ 12 = 3입니다. 나누는 수와 나누어지는 수에 10을 곱해 계산합니다.",
            accept_formats=["3"],
        ),
        fb(
            id="e6-2-2-02-fb-001",
            concept_id="e6-2-2-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="6 ÷ 1.5 = __입니다.",
            answer="4",
            explanation="60 ÷ 15 = 4입니다. 나누는 수를 자연수로 만든 후 계산합니다.",
            accept_formats=["4"],
        ),
        fb(
            id="e6-2-2-03-fb-001",
            concept_id="e6-2-2-03",
            category="computation",
            part="calc",
            difficulty=7,
            content="8.4 ÷ 2.1 = __입니다.",
            answer="4",
            explanation="84 ÷ 21 = 4입니다.",
            accept_formats=["4"],
        ),
        fb(
            id="e6-2-2-04-fb-001",
            concept_id="e6-2-2-04",
            category="computation",
            part="calc",
            difficulty=8,
            content="7.5 ÷ 0.25 = __입니다.",
            answer="30",
            explanation="750 ÷ 25 = 30입니다. 나누는 수와 나누어지는 수에 100을 곱해 계산합니다.",
            accept_formats=["30"],
        ),
        fb(
            id="e6-2-2-05-fb-001",
            concept_id="e6-2-2-05",
            category="computation",
            part="calc",
            difficulty=8,
            content="5.6 ÷ 0.08 = __입니다.",
            answer="70",
            explanation="560 ÷ 8 = 70입니다.",
            accept_formats=["70"],
        ),
        fb(
            id="e6-2-2-06-fb-001",
            concept_id="e6-2-2-06",
            category="fill_in_blank",
            part="calc",
            difficulty=9,
            content="2.7 m의 철사를 0.3 m씩 자르면 __도막이 됩니다.",
            answer="9",
            explanation="2.7 ÷ 0.3 = 27 ÷ 3 = 9도막입니다.",
            accept_formats=["9"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 3단원: 공간과 입체 (e6-2-3-01~06)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-2-3-01-fb-001",
            concept_id="e6-2-3-01",
            category="concept",
            part="geo",
            difficulty=6,
            content="위에서 본 모양이 3×3 정사각형일 때, 쌓기나무의 최소 개수는 __개입니다.",
            answer="9",
            explanation="최소 개수는 위에서 본 모양의 칸 수와 같습니다. 3 × 3 = 9개입니다.",
            accept_formats=["9"],
        ),
        fb(
            id="e6-2-3-02-fb-001",
            concept_id="e6-2-3-02",
            category="concept",
            part="geo",
            difficulty=7,
            content="위에서 본 모양이 2×3 직사각형이고 각 칸에 쓰인 수가 최댓값일 때, 쌓기나무의 최대 개수를 구하려면 각 칸에 쓰인 __를 모두 더하면 됩니다.",
            answer="높이",
            explanation="각 칸에 쌓인 높이를 모두 더하면 전체 개수가 됩니다.",
            accept_formats=["높이", "수"],
        ),
        fb(
            id="e6-2-3-03-fb-001",
            concept_id="e6-2-3-03",
            category="concept",
            part="geo",
            difficulty=8,
            content="앞에서 본 모양과 옆에서 본 모양을 보고 쌓기나무의 개수를 구하는 것을 __ 분석이라고 합니다.",
            answer="투영도",
            explanation="투영도는 입체도형을 여러 방향에서 본 모양으로 분석하는 방법입니다.",
            accept_formats=["투영도", "정투영"],
        ),
        fb(
            id="e6-2-3-04-fb-001",
            concept_id="e6-2-3-04",
            category="concept",
            part="geo",
            difficulty=8,
            content="쌓기나무로 쌓은 모양에서 위, 앞, 옆에서 본 모양이 모두 주어졌을 때, 이 세 투영도로부터 원래 입체의 구조를 __할 수 있습니다.",
            answer="복원",
            explanation="세 방향의 투영도를 종합하면 원래 입체 구조를 복원할 수 있습니다.",
            accept_formats=["복원", "재구성"],
        ),
        fb(
            id="e6-2-3-05-fb-001",
            concept_id="e6-2-3-05",
            category="concept",
            part="geo",
            difficulty=9,
            content="2층으로 쌓은 쌓기나무를 위에서 본 모양에 각 칸의 층수를 쓸 때, 가장 큰 수는 __입니다.",
            answer="2",
            explanation="2층까지 쌓았으므로 가장 큰 수는 2입니다.",
            accept_formats=["2"],
        ),
        fb(
            id="e6-2-3-06-fb-001",
            concept_id="e6-2-3-06",
            category="fill_in_blank",
            part="geo",
            difficulty=9,
            content="앞에서 본 모양이 가로 3칸, 세로 2칸이고 모든 칸이 채워져 있을 때, 쌓기나무의 최소 개수는 __개입니다.",
            answer="6",
            explanation="앞에서 본 모양의 칸 수 = 3 × 2 = 6개가 최소 개수입니다.",
            accept_formats=["6"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 4단원: 비례식과 비례배분 (e6-2-4-01~06)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-2-4-01-fb-001",
            concept_id="e6-2-4-01",
            category="concept",
            part="algebra",
            difficulty=7,
            content="비례식 3 : 4 = 6 : 8에서 외항은 __와 __입니다.",
            answer="3과8",
            explanation="비례식 a:b = c:d에서 외항은 a와 d입니다. 따라서 3과 8입니다.",
            accept_formats=["3과8", "3, 8", "3 8"],
        ),
        fb(
            id="e6-2-4-02-fb-001",
            concept_id="e6-2-4-02",
            category="concept",
            part="algebra",
            difficulty=8,
            content="비례식 3 : 4 = 9 : ☐에서 ☐는 __입니다.",
            answer="12",
            explanation="외항의 곱 = 내항의 곱이므로, 3 × ☐ = 4 × 9 = 36, ☐ = 12입니다.",
            accept_formats=["12"],
        ),
        fb(
            id="e6-2-4-03-fb-001",
            concept_id="e6-2-4-03",
            category="concept",
            part="algebra",
            difficulty=8,
            content="비례식 5 : 8 = ☐ : 24에서 ☐는 __입니다.",
            answer="15",
            explanation="5 × 24 = 8 × ☐, 120 = 8 × ☐, ☐ = 15입니다.",
            accept_formats=["15"],
        ),
        fb(
            id="e6-2-4-04-fb-001",
            concept_id="e6-2-4-04",
            category="concept",
            part="algebra",
            difficulty=9,
            content="30을 3 : 2의 비로 비례배분하면 큰 쪽은 __입니다.",
            answer="18",
            explanation="비의 합 = 3 + 2 = 5입니다. 큰 쪽 = 30 × 3/5 = 18입니다.",
            accept_formats=["18"],
        ),
        fb(
            id="e6-2-4-05-fb-001",
            concept_id="e6-2-4-05",
            category="concept",
            part="algebra",
            difficulty=9,
            content="40을 5 : 3으로 비례배분하면 작은 쪽은 __입니다.",
            answer="15",
            explanation="비의 합 = 5 + 3 = 8입니다. 작은 쪽 = 40 × 3/8 = 15입니다.",
            accept_formats=["15"],
        ),
        fb(
            id="e6-2-4-06-fb-001",
            concept_id="e6-2-4-06",
            category="fill_in_blank",
            part="algebra",
            difficulty=10,
            content="형과 동생이 56000원을 3 : 4로 나누면 동생은 __원을 받습니다.",
            answer="32000",
            explanation="비의 합 = 3 + 4 = 7입니다. 동생 = 56000 × 4/7 = 32000원입니다.",
            accept_formats=["32000"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 5단원: 원의 넓이 (e6-2-5-01~06)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-2-5-01-fb-001",
            concept_id="e6-2-5-01",
            category="concept",
            part="geo",
            difficulty=6,
            content="원주율은 원주를 __로 나눈 값입니다.",
            answer="지름",
            explanation="원주율 π = 원주 ÷ 지름 ≈ 3.14입니다.",
            accept_formats=["지름", "직경"],
        ),
        fb(
            id="e6-2-5-02-fb-001",
            concept_id="e6-2-5-02",
            category="concept",
            part="geo",
            difficulty=7,
            content="반지름이 5cm인 원의 넓이는 __cm²입니다. (π = 3.14로 계산)",
            answer="78.5",
            explanation="원의 넓이 = π × r² = 3.14 × 5 × 5 = 78.5cm²입니다.",
            accept_formats=["78.5"],
        ),
        fb(
            id="e6-2-5-03-fb-001",
            concept_id="e6-2-5-03",
            category="concept",
            part="geo",
            difficulty=7,
            content="지름이 8cm인 원의 넓이는 __cm²입니다. (π = 3으로 계산)",
            answer="48",
            explanation="반지름 = 8 ÷ 2 = 4cm, 넓이 = 3 × 4 × 4 = 48cm²입니다.",
            accept_formats=["48"],
        ),
        fb(
            id="e6-2-5-04-fb-001",
            concept_id="e6-2-5-04",
            category="concept",
            part="geo",
            difficulty=8,
            content="반지름이 7cm인 원의 넓이는 __cm²입니다. (π = 3.14로 계산)",
            answer="153.86",
            explanation="원의 넓이 = 3.14 × 7 × 7 = 153.86cm²입니다.",
            accept_formats=["153.86"],
        ),
        fb(
            id="e6-2-5-05-fb-001",
            concept_id="e6-2-5-05",
            category="concept",
            part="geo",
            difficulty=9,
            content="원의 넓이가 28.26cm²일 때, 반지름은 __cm입니다. (π = 3.14로 계산)",
            answer="3",
            explanation="π × r² = 28.26, 3.14 × r² = 28.26, r² = 9, r = 3cm입니다.",
            accept_formats=["3"],
        ),
        fb(
            id="e6-2-5-06-fb-001",
            concept_id="e6-2-5-06",
            category="fill_in_blank",
            part="geo",
            difficulty=9,
            content="반지름이 10cm인 원 안에 반지름이 5cm인 원이 있을 때, 두 원 사이의 넓이는 __cm²입니다. (π = 3으로 계산)",
            answer="225",
            explanation="큰 원 = 3 × 10 × 10 = 300cm². 작은 원 = 3 × 5 × 5 = 75cm². 차이 = 300 - 75 = 225cm²입니다.",
            accept_formats=["225"],
        ),
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # 2학기 6단원: 원기둥, 원뿔, 구 (e6-2-6-01~04)
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        fb(
            id="e6-2-6-01-fb-001",
            concept_id="e6-2-6-01",
            category="concept",
            part="geo",
            difficulty=6,
            content="원기둥의 밑면은 모두 __개입니다.",
            answer="2",
            explanation="원기둥은 합동인 두 개의 원을 밑면으로 가집니다.",
            accept_formats=["2"],
        ),
        fb(
            id="e6-2-6-02-fb-001",
            concept_id="e6-2-6-02",
            category="concept",
            part="geo",
            difficulty=7,
            content="원뿔의 옆면을 펼쳤을 때 나타나는 도형은 __입니다.",
            answer="부채꼴",
            explanation="원뿔의 전개도에서 옆면은 부채꼴 모양입니다.",
            accept_formats=["부채꼴", "부채형"],
        ),
        fb(
            id="e6-2-6-03-fb-001",
            concept_id="e6-2-6-03",
            category="concept",
            part="geo",
            difficulty=8,
            content="반원을 지름을 축으로 회전시키면 __이 만들어집니다.",
            answer="구",
            explanation="반원을 지름을 축으로 한 바퀴 회전시키면 구가 됩니다.",
            accept_formats=["구", "공"],
        ),
        fb(
            id="e6-2-6-04-fb-001",
            concept_id="e6-2-6-04",
            category="fill_in_blank",
            part="geo",
            difficulty=9,
            content="직각삼각형을 직각을 낀 한 변을 축으로 회전시키면 __이 만들어집니다.",
            answer="원뿔",
            explanation="직각삼각형을 직각을 낀 변을 축으로 회전시키면 원뿔이 됩니다.",
            accept_formats=["원뿔"],
        ),
    ]
