"""초등 3학년 빈칸 채우기 문제 시드 데이터."""
from app.seeds._base import fb


def get_questions():
    """빈칸 채우기 문제 반환."""
    return [
        # 난이도 1-3: 기초
        fb(
            id="e3-fb-001",
            concept_id="concept-e3-comp",
            category="computation",
            part="arithmetic",
            difficulty=2,
            content="145 + 238 = ____",
            answer="383",
            explanation="145 + 238 = 383입니다. 각 자리를 차례로 더하면 됩니다.",
            points=10,
            accept_formats=["383"],
        ),
        fb(
            id="e3-fb-002",
            concept_id="concept-e3-comp",
            category="computation",
            part="arithmetic",
            difficulty=3,
            content="456 - 189 = ____",
            answer="267",
            explanation="456 - 189 = 267입니다. 받아내림하여 계산합니다.",
            points=10,
            accept_formats=["267"],
        ),
        fb(
            id="e3-fb-003",
            concept_id="concept-e3-comp",
            category="computation",
            part="arithmetic",
            difficulty=3,
            content="23 × 5 = ____",
            answer="115",
            explanation="23 × 5 = 115입니다. 3×5=15(1 올림), 2×5+1=11이므로 115입니다.",
            points=10,
            accept_formats=["115"],
        ),

        # 난이도 4-6: 중급
        fb(
            id="e3-fb-004",
            concept_id="concept-e3-conc",
            category="concept",
            part="fractions",
            difficulty=4,
            content="전체를 7등분했을 때, 한 조각은 전체의 ____입니다. (분수로 답하세요)",
            answer="1/7",
            explanation="전체를 7등분했을 때 한 조각은 1/7입니다.",
            points=10,
            accept_formats=["1/7"],
        ),
        fb(
            id="e3-fb-005",
            concept_id="concept-e3-comp",
            category="computation",
            part="arithmetic",
            difficulty=5,
            content="67 × 8 = ____",
            answer="536",
            explanation="67 × 8 = 536입니다. 7×8=56(5 올림), 6×8+5=53이므로 536입니다.",
            points=10,
            accept_formats=["536"],
        ),
        fb(
            id="e3-fb-006",
            concept_id="concept-e3-comp",
            category="computation",
            part="arithmetic",
            difficulty=6,
            content="812 - 347 = ____",
            answer="465",
            explanation="812 - 347 = 465입니다.",
            points=10,
            accept_formats=["465"],
        ),

        # 난이도 7-10: 고급
        fb(
            id="e3-fb-007",
            concept_id="concept-e3-conc",
            category="concept",
            part="fractions",
            difficulty=7,
            content="분모가 같은 분수 중 3/8보다 크고 6/8보다 작은 분수는 ____, ____입니다. (작은 것부터 순서대로)",
            answer="4/8, 5/8",
            explanation="분모가 8로 같으므로 분자가 3보다 크고 6보다 작은 수는 4, 5입니다. 따라서 4/8, 5/8입니다.",
            points=10,
            accept_formats=["4/8, 5/8", "4/8,5/8"],
        ),
        fb(
            id="e3-fb-008",
            concept_id="concept-e3-comp",
            category="computation",
            part="arithmetic",
            difficulty=8,
            content="94 × 7 = ____",
            answer="658",
            explanation="94 × 7 = 658입니다. 4×7=28(2 올림), 9×7+2=65이므로 658입니다.",
            points=10,
            accept_formats=["658"],
        ),
        fb(
            id="e3-fb-009",
            concept_id="concept-e3-comp",
            category="computation",
            part="arithmetic",
            difficulty=9,
            content="1000 - 456 = ____",
            answer="544",
            explanation="1000 - 456 = 544입니다.",
            points=10,
            accept_formats=["544"],
        ),
        fb(
            id="e3-fb-010",
            concept_id="concept-e3-conc",
            category="concept",
            part="fractions",
            difficulty=10,
            content="단위분수 1/2, 1/4, 1/5, 1/10 중 두 번째로 큰 분수는 ____입니다.",
            answer="1/4",
            explanation="단위분수는 분모가 작을수록 크므로 1/2 > 1/4 > 1/5 > 1/10 순서입니다. 두 번째로 큰 분수는 1/4입니다.",
            points=10,
            accept_formats=["1/4"],
        ),
    ]
