"""중2 빈칸 채우기 시드 데이터 - 2022 개정 교육과정.

10단원 × 2문제 = 20문제
"""

from .._base import fb, test


def get_fill_blank_data() -> dict:
    """빈칸 채우기 데이터 반환."""
    questions = [
        # ── 유리수와 순환소수 (2문제) ──
        fb(
            id="m2-fb-001",
            concept_id="concept-m2-rational-01",
            category="computation",
            part="calc",
            difficulty=5,
            content="기약분수 7/24를 소수로 나타낼 수 없는 이유는 분모 24의 소인수에 2와 5 외에 [answer]가 포함되어 있기 때문이다.",
            answer="3",
            explanation="24 = 2³×3이므로 소인수 중 3이 포함되어 있어 유한소수로 나타낼 수 없다.",
            points=10,
            accept_formats=["3"],
        ),
        fb(
            id="m2-fb-002",
            concept_id="concept-m2-rational-02",
            category="computation",
            part="calc",
            difficulty=7,
            content="순환소수 0.272727...을 분수로 나타내면 [answer]/[answer]이다. (기약분수, 분자부터)",
            answer="3|11",
            explanation="x = 0.272727..., 100x = 27.272727...이므로 99x = 27, x = 27/99 = 3/11",
            points=10,
            accept_formats=["3|11"],
        ),

        # ── 식의 계산 (2문제) ──
        fb(
            id="m2-fb-003",
            concept_id="concept-m2-expr-01",
            category="computation",
            part="algebra",
            difficulty=4,
            content="a⁴ × a³ = a[answer]",
            answer="7",
            explanation="지수법칙 a^m × a^n = a^(m+n)이므로 a⁴ × a³ = a⁷",
            points=10,
            accept_formats=["7", "^7"],
        ),
        fb(
            id="m2-fb-004",
            concept_id="concept-m2-expr-02",
            category="computation",
            part="algebra",
            difficulty=8,
            content="(3a²b³)² = [answer]a[answer]b[answer]",
            answer="9|4|6",
            explanation="각 인수에 지수 2를 적용: 3² × (a²)² × (b³)² = 9a⁴b⁶",
            points=10,
            accept_formats=["9|4|6"],
        ),

        # ── 일차부등식 (2문제) ──
        fb(
            id="m2-fb-005",
            concept_id="concept-m2-ineq-01",
            category="computation",
            part="algebra",
            difficulty=6,
            content="일차부등식 -3x ≥ 9를 풀면 x [answer] [answer]이다. (부등호 기호, 숫자 순)",
            answer="≤|-3",
            explanation="양변을 -3으로 나누면 부등호 방향이 바뀐다: x ≤ -3",
            points=10,
            accept_formats=["≤|-3", "<=|-3"],
        ),
        fb(
            id="m2-fb-006",
            concept_id="concept-m2-ineq-01",
            category="computation",
            part="algebra",
            difficulty=5,
            content="부등식에서 양변에 [answer]를 곱하거나 나누면 부등호의 방향이 바뀐다.",
            answer="음수",
            explanation="부등식의 핵심 성질: 양변에 음수를 곱하거나 나누면 부등호 방향이 반전된다.",
            points=10,
            accept_formats=["음수", "(-)", "마이너스"],
        ),

        # ── 연립일차방정식 (2문제) ──
        fb(
            id="m2-fb-007",
            concept_id="concept-m2-simul-01",
            category="computation",
            part="algebra",
            difficulty=7,
            content="연립방정식 x+y=7, 2x-y=5를 풀면 x=[answer], y=[answer]이다.",
            answer="4|3",
            explanation="두 식을 더하면 3x=12, x=4. 첫째 식에 대입하면 4+y=7, y=3",
            points=10,
            accept_formats=["4|3"],
        ),
        fb(
            id="m2-fb-008",
            concept_id="concept-m2-simul-02",
            category="computation",
            part="algebra",
            difficulty=9,
            content="연립방정식의 해가 없는 경우를 [answer]이라 하고, 해가 무수히 많은 경우를 [answer]이라 한다.",
            answer="불능|부정",
            explanation="불능: 두 직선이 평행(해 없음), 부정: 두 직선이 일치(해 무수히 많음)",
            points=10,
            accept_formats=["불능|부정"],
        ),

        # ── 일차함수 (2문제) ──
        fb(
            id="m2-fb-009",
            concept_id="concept-m2-linfn-01",
            category="concept",
            part="func",
            difficulty=5,
            content="일차함수 y=-4x+7의 기울기는 [answer]이고, y절편은 [answer]이다.",
            answer="-4|7",
            explanation="y=ax+b에서 a는 기울기, b는 y절편이므로 기울기는 -4, y절편은 7이다.",
            points=10,
            accept_formats=["-4|7"],
        ),
        fb(
            id="m2-fb-010",
            concept_id="concept-m2-linfn-02",
            category="concept",
            part="func",
            difficulty=8,
            content="두 점 (2, 5)와 (4, 11)을 지나는 직선의 방정식은 y=[answer]x+[answer]이다.",
            answer="3|-1",
            explanation="기울기 = (11-5)/(4-2) = 3. 점 (2,5)를 대입: 5=3(2)+b, b=-1. 따라서 y=3x-1",
            points=10,
            accept_formats=["3|-1"],
        ),

        # ── 삼각형의 성질 (2문제) ──
        fb(
            id="m2-fb-011",
            concept_id="concept-m2-tri-02",
            category="concept",
            part="geo",
            difficulty=6,
            content="삼각형의 외심은 세 변의 [answer]의 교점이고, 내심은 세 내각의 [answer]의 교점이다.",
            answer="수직이등분선|이등분선",
            explanation="外心은 세 변의 수직이등분선의 교점(외접원의 중심), 內心은 세 내각의 이등분선의 교점(내접원의 중심)",
            points=10,
            accept_formats=["수직이등분선|이등분선"],
        ),
        fb(
            id="m2-fb-012",
            concept_id="concept-m2-tri-01",
            category="concept",
            part="geo",
            difficulty=7,
            content="이등변삼각형에서 두 변의 길이가 같다는 것은 [answer]이고, 두 밑각이 같다는 것은 [answer]이다. (정의/성질)",
            answer="정의|성질",
            explanation="정의는 증명 없이 사용하는 전제이고, 성질은 정의로부터 증명해야 하는 대상이다.",
            points=10,
            accept_formats=["정의|성질"],
        ),

        # ── 사각형의 성질 (2문제) ──
        fb(
            id="m2-fb-013",
            concept_id="concept-m2-quad-01",
            category="concept",
            part="geo",
            difficulty=5,
            content="평행사변형에서 두 대각선은 서로를 [answer]한다.",
            answer="이등분",
            explanation="평행사변형의 성질: 두 대각선은 서로를 이등분한다.",
            points=10,
            accept_formats=["이등분"],
        ),
        fb(
            id="m2-fb-014",
            concept_id="concept-m2-quad-02",
            category="concept",
            part="geo",
            difficulty=7,
            content="네 변의 길이가 모두 같은 사각형은 [answer]이고, 네 각이 모두 직각인 사각형은 [answer]이다.",
            answer="마름모|직사각형",
            explanation="마름모: 네 변의 길이가 같음. 직사각형: 네 각이 모두 직각.",
            points=10,
            accept_formats=["마름모|직사각형"],
        ),

        # ── 도형의 닮음 (2문제) ──
        fb(
            id="m2-fb-015",
            concept_id="concept-m2-simil-01",
            category="concept",
            part="geo",
            difficulty=6,
            content="두 삼각형의 대응각 중 두 쌍이 각각 같으면 닮음이라는 조건을 [answer] 닮음이라 한다.",
            answer="AA",
            explanation="AA(Angle-Angle) 닮음 조건: 두 쌍의 대응각이 같으면 닮음이다.",
            points=10,
            accept_formats=["AA"],
        ),
        fb(
            id="m2-fb-016",
            concept_id="concept-m2-simil-02",
            category="concept",
            part="geo",
            difficulty=9,
            content="닮음비가 3:5인 두 삼각형의 넓이의 비는 [answer]:[answer]이다.",
            answer="9|25",
            explanation="닮음비가 m:n이면 넓이비는 m²:n² = 9:25",
            points=10,
            accept_formats=["9|25"],
        ),

        # ── 피타고라스 정리 (2문제) ──
        fb(
            id="m2-fb-017",
            concept_id="concept-m2-pytha-01",
            category="concept",
            part="geo",
            difficulty=5,
            content="직각삼각형에서 빗변을 c, 다른 두 변을 a, b라 할 때, a²+b²=[answer]²이다.",
            answer="c",
            explanation="피타고라스 정리: 직각삼각형에서 a²+b²=c² (c는 빗변)",
            points=10,
            accept_formats=["c"],
        ),
        fb(
            id="m2-fb-018",
            concept_id="concept-m2-pytha-02",
            category="concept",
            part="geo",
            difficulty=8,
            content="삼각형의 무게중심은 각 중선을 꼭짓점으로부터 [answer]:[answer]의 비율로 내분한다.",
            answer="2|1",
            explanation="삼각형의 무게중심은 세 중선의 교점이며, 각 중선을 꼭짓점으로부터 2:1로 내분한다.",
            points=10,
            accept_formats=["2|1"],
        ),

        # ── 확률 (2문제) ──
        fb(
            id="m2-fb-019",
            concept_id="concept-m2-prob-01",
            category="concept",
            part="data",
            difficulty=7,
            content="A가 m가지, B가 n가지일 때, A 또는 B가 일어나는 경우는 [answer]가지(합의 법칙), A와 B가 동시에 일어나는 경우는 [answer]가지(곱의 법칙)이다.",
            answer="m+n|m×n",
            explanation="합의 법칙: A 또는 B = m+n, 곱의 법칙: A와 B = m×n",
            points=10,
            accept_formats=["m+n|m×n", "m+n|m*n", "m+n|mn"],
        ),
        fb(
            id="m2-fb-020",
            concept_id="concept-m2-prob-02",
            category="concept",
            part="data",
            difficulty=10,
            content="주머니에 빨간 공 3개, 파란 공 2개가 있을 때, 빨간 공이 나올 확률은 [answer]/[answer]이다.",
            answer="3|5",
            explanation="전체 경우의 수는 5(빨1, 빨2, 빨3, 파1, 파2), 빨간 공은 3가지이므로 3/5",
            points=10,
            accept_formats=["3|5"],
        ),
    ]

    tests = [
        test(
            id="test-m2-fb",
            title="중2 빈칸 채우기 종합 테스트",
            description="10개 단원 빈칸 채우기",
            grade="middle_2",
            concept_ids=[
                "concept-m2-rational-01", "concept-m2-rational-02",
                "concept-m2-expr-01", "concept-m2-expr-02",
                "concept-m2-ineq-01", "concept-m2-ineq-02",
                "concept-m2-simul-01", "concept-m2-simul-02",
                "concept-m2-linfn-01", "concept-m2-linfn-02",
                "concept-m2-tri-01", "concept-m2-tri-02",
                "concept-m2-quad-01", "concept-m2-quad-02",
                "concept-m2-simil-01", "concept-m2-simil-02",
                "concept-m2-pytha-01", "concept-m2-pytha-02",
                "concept-m2-prob-01", "concept-m2-prob-02",
            ],
            question_ids=[q["id"] for q in questions],
            time_limit_minutes=30,
            use_question_pool=True,
            questions_per_attempt=10,
        ),
    ]

    return {"concepts": [], "questions": questions, "tests": tests}
